namespace Tempo.Blazor.Components.NotionEditor.UI;

public enum EmojiCategory { Smileys, People, Animals, Food, Travel, Activities, Objects, Symbols, Flags }

public sealed record EmojiEntry(string Emoji, string Name, EmojiCategory Category, string[] Keywords);

public static class EmojiData
{
    public static readonly IReadOnlyList<EmojiEntry> All = new EmojiEntry[]
    {
        // ── Smileys & Emotion ─────────────────────────────────────────────────
        new("😀", "grinning face",                    EmojiCategory.Smileys,     ["happy","smile","grin"]),
        new("😃", "grinning face with big eyes",       EmojiCategory.Smileys,     ["happy","smile","open"]),
        new("😄", "grinning face with smiling eyes",   EmojiCategory.Smileys,     ["happy","laugh","joy"]),
        new("😁", "beaming face",                      EmojiCategory.Smileys,     ["happy","grin","ear to ear"]),
        new("😆", "grinning squinting face",           EmojiCategory.Smileys,     ["laugh","lol","funny"]),
        new("😅", "grinning face with sweat",          EmojiCategory.Smileys,     ["nervous","whew","phew"]),
        new("😂", "face with tears of joy",            EmojiCategory.Smileys,     ["funny","laugh","lol","cry"]),
        new("🤣", "rolling on the floor laughing",     EmojiCategory.Smileys,     ["rofl","funny","laugh"]),
        new("😊", "smiling face with smiling eyes",    EmojiCategory.Smileys,     ["happy","blush","warm"]),
        new("😇", "smiling face with halo",            EmojiCategory.Smileys,     ["innocent","angel","good"]),
        new("🙂", "slightly smiling face",             EmojiCategory.Smileys,     ["smile","ok","meh"]),
        new("🙃", "upside-down face",                  EmojiCategory.Smileys,     ["sarcasm","silly","irony"]),
        new("😉", "winking face",                      EmojiCategory.Smileys,     ["wink","flirt","cheeky"]),
        new("😍", "smiling face with heart-eyes",      EmojiCategory.Smileys,     ["love","heart","crush"]),
        new("🥰", "smiling face with hearts",          EmojiCategory.Smileys,     ["love","affection","warm"]),
        new("😘", "face blowing a kiss",               EmojiCategory.Smileys,     ["kiss","love","mwah"]),
        new("😋", "face savoring food",                EmojiCategory.Smileys,     ["yummy","delicious","food"]),
        new("😛", "face with tongue",                  EmojiCategory.Smileys,     ["tongue","playful","silly"]),
        new("😜", "winking face with tongue",          EmojiCategory.Smileys,     ["playful","silly","wink"]),
        new("🤪", "zany face",                         EmojiCategory.Smileys,     ["crazy","silly","goofy"]),
        new("😎", "smiling face with sunglasses",      EmojiCategory.Smileys,     ["cool","sunglasses","awesome"]),
        new("🥳", "partying face",                     EmojiCategory.Smileys,     ["party","celebrate","birthday"]),
        new("😏", "smirking face",                     EmojiCategory.Smileys,     ["smirk","confident","flirty"]),
        new("😔", "pensive face",                      EmojiCategory.Smileys,     ["sad","thoughtful","down"]),
        new("😢", "crying face",                       EmojiCategory.Smileys,     ["sad","cry","tear"]),
        new("😭", "loudly crying face",                EmojiCategory.Smileys,     ["cry","sob","upset"]),
        new("😤", "face with steam from nose",         EmojiCategory.Smileys,     ["frustrated","angry","huff"]),
        new("😠", "angry face",                        EmojiCategory.Smileys,     ["angry","mad","grumpy"]),
        new("🤯", "exploding head",                    EmojiCategory.Smileys,     ["mind blown","shocked","wow"]),
        new("😱", "face screaming in fear",            EmojiCategory.Smileys,     ["scream","scared","shocked"]),

        // ── People & Body ─────────────────────────────────────────────────────
        new("👋", "waving hand",                       EmojiCategory.People,      ["wave","hello","hi","bye"]),
        new("🤚", "raised back of hand",               EmojiCategory.People,      ["stop","hand","raise"]),
        new("🖐️", "hand with fingers splayed",         EmojiCategory.People,      ["five","hand","high five"]),
        new("✋", "raised hand",                        EmojiCategory.People,      ["stop","agree","high five"]),
        new("👌", "ok hand",                           EmojiCategory.People,      ["ok","perfect","fine"]),
        new("✌️", "victory hand",                      EmojiCategory.People,      ["peace","two","victory"]),
        new("🤞", "crossed fingers",                   EmojiCategory.People,      ["luck","hope","wish"]),
        new("👍", "thumbs up",                         EmojiCategory.People,      ["good","like","approve","yes"]),
        new("👎", "thumbs down",                       EmojiCategory.People,      ["bad","dislike","no","disagree"]),
        new("✊", "raised fist",                        EmojiCategory.People,      ["fist","strength","power"]),
        new("👏", "clapping hands",                    EmojiCategory.People,      ["applause","clap","bravo"]),
        new("🙌", "raising hands",                     EmojiCategory.People,      ["celebrate","hooray","praise"]),
        new("🙏", "folded hands",                      EmojiCategory.People,      ["please","thank you","pray"]),
        new("🤝", "handshake",                         EmojiCategory.People,      ["deal","agree","partnership"]),
        new("💪", "flexed biceps",                     EmojiCategory.People,      ["strong","muscle","strength"]),
        new("🫶", "heart hands",                       EmojiCategory.People,      ["love","care","heart"]),
        new("👶", "baby",                              EmojiCategory.People,      ["infant","child","newborn"]),
        new("🧒", "child",                             EmojiCategory.People,      ["kid","child","young"]),
        new("👦", "boy",                               EmojiCategory.People,      ["boy","male","kid"]),
        new("👧", "girl",                              EmojiCategory.People,      ["girl","female","kid"]),
        new("🧑", "person",                            EmojiCategory.People,      ["person","adult"]),
        new("👨", "man",                               EmojiCategory.People,      ["man","male","adult"]),
        new("👩", "woman",                             EmojiCategory.People,      ["woman","female","adult"]),
        new("👴", "old man",                           EmojiCategory.People,      ["elderly","grandfather","old"]),
        new("👵", "old woman",                         EmojiCategory.People,      ["elderly","grandmother","old"]),

        // ── Animals & Nature ──────────────────────────────────────────────────
        new("🐶", "dog face",                          EmojiCategory.Animals,     ["dog","pet","puppy","woof"]),
        new("🐱", "cat face",                          EmojiCategory.Animals,     ["cat","pet","kitten","meow"]),
        new("🐭", "mouse face",                        EmojiCategory.Animals,     ["mouse","rodent","squeak"]),
        new("🐹", "hamster",                           EmojiCategory.Animals,     ["hamster","pet","cute"]),
        new("🐰", "rabbit face",                       EmojiCategory.Animals,     ["rabbit","bunny","hop"]),
        new("🦊", "fox",                               EmojiCategory.Animals,     ["fox","cunning","orange"]),
        new("🐻", "bear",                              EmojiCategory.Animals,     ["bear","teddy","grizzly"]),
        new("🐼", "panda",                             EmojiCategory.Animals,     ["panda","china","bamboo"]),
        new("🐨", "koala",                             EmojiCategory.Animals,     ["koala","australia","bear"]),
        new("🐯", "tiger face",                        EmojiCategory.Animals,     ["tiger","fierce","stripe"]),
        new("🦁", "lion",                              EmojiCategory.Animals,     ["lion","king","pride","roar"]),
        new("🐮", "cow face",                          EmojiCategory.Animals,     ["cow","moo","farm"]),
        new("🐷", "pig face",                          EmojiCategory.Animals,     ["pig","oink","farm"]),
        new("🐸", "frog",                              EmojiCategory.Animals,     ["frog","green","ribbit"]),
        new("🐵", "monkey face",                       EmojiCategory.Animals,     ["monkey","primate","ape"]),
        new("🐔", "chicken",                           EmojiCategory.Animals,     ["chicken","bird","farm","cluck"]),
        new("🐧", "penguin",                           EmojiCategory.Animals,     ["penguin","cold","ice","arctic"]),
        new("🐦", "bird",                              EmojiCategory.Animals,     ["bird","tweet","fly"]),
        new("🦆", "duck",                              EmojiCategory.Animals,     ["duck","quack","water"]),
        new("🦉", "owl",                               EmojiCategory.Animals,     ["owl","wise","night","hoot"]),
        new("🐺", "wolf",                              EmojiCategory.Animals,     ["wolf","howl","wild"]),
        new("🦄", "unicorn",                           EmojiCategory.Animals,     ["unicorn","magic","mythical"]),
        new("🐝", "honeybee",                          EmojiCategory.Animals,     ["bee","honey","sting","insect"]),
        new("🐢", "turtle",                            EmojiCategory.Animals,     ["turtle","slow","shell"]),
        new("🦋", "butterfly",                         EmojiCategory.Animals,     ["butterfly","beautiful","insect"]),

        // ── Food & Drink ──────────────────────────────────────────────────────
        new("🍎", "red apple",                         EmojiCategory.Food,        ["apple","fruit","red"]),
        new("🍊", "tangerine",                         EmojiCategory.Food,        ["orange","tangerine","citrus"]),
        new("🍋", "lemon",                             EmojiCategory.Food,        ["lemon","sour","citrus","yellow"]),
        new("🍇", "grapes",                            EmojiCategory.Food,        ["grapes","fruit","wine","purple"]),
        new("🍓", "strawberry",                        EmojiCategory.Food,        ["strawberry","fruit","red"]),
        new("🫐", "blueberries",                       EmojiCategory.Food,        ["blueberry","fruit","blue"]),
        new("🍒", "cherries",                          EmojiCategory.Food,        ["cherry","fruit","red"]),
        new("🍑", "peach",                             EmojiCategory.Food,        ["peach","fruit","yellow"]),
        new("🥭", "mango",                             EmojiCategory.Food,        ["mango","tropical","fruit"]),
        new("🍍", "pineapple",                         EmojiCategory.Food,        ["pineapple","tropical","fruit"]),
        new("🥥", "coconut",                           EmojiCategory.Food,        ["coconut","tropical","white"]),
        new("🍅", "tomato",                            EmojiCategory.Food,        ["tomato","red","vegetable"]),
        new("🥑", "avocado",                           EmojiCategory.Food,        ["avocado","healthy","green"]),
        new("🥦", "broccoli",                          EmojiCategory.Food,        ["broccoli","vegetable","green"]),
        new("🌽", "ear of corn",                       EmojiCategory.Food,        ["corn","vegetable","yellow"]),
        new("🥕", "carrot",                            EmojiCategory.Food,        ["carrot","vegetable","orange"]),
        new("🍞", "bread",                             EmojiCategory.Food,        ["bread","loaf","bake"]),
        new("🥐", "croissant",                         EmojiCategory.Food,        ["croissant","french","pastry"]),
        new("🧀", "cheese wedge",                      EmojiCategory.Food,        ["cheese","dairy","yellow"]),
        new("🥚", "egg",                               EmojiCategory.Food,        ["egg","breakfast","oval"]),
        new("🍳", "cooking",                           EmojiCategory.Food,        ["egg","frying","breakfast","pan"]),
        new("🥓", "bacon",                             EmojiCategory.Food,        ["bacon","meat","breakfast"]),
        new("🍔", "hamburger",                         EmojiCategory.Food,        ["burger","fast food","beef"]),
        new("🍕", "pizza",                             EmojiCategory.Food,        ["pizza","italian","slice"]),
        new("🍟", "french fries",                      EmojiCategory.Food,        ["fries","fast food","potato"]),

        // ── Travel & Places ───────────────────────────────────────────────────
        new("🚗", "automobile",                        EmojiCategory.Travel,      ["car","drive","vehicle"]),
        new("🚕", "taxi",                              EmojiCategory.Travel,      ["taxi","cab","yellow"]),
        new("🚙", "sport utility vehicle",             EmojiCategory.Travel,      ["suv","car","vehicle"]),
        new("🏎️", "racing car",                        EmojiCategory.Travel,      ["race","fast","car","formula"]),
        new("🚑", "ambulance",                         EmojiCategory.Travel,      ["ambulance","emergency","hospital"]),
        new("🚒", "fire engine",                       EmojiCategory.Travel,      ["firetruck","emergency","fire"]),
        new("🚲", "bicycle",                           EmojiCategory.Travel,      ["bike","cycle","eco"]),
        new("🏍️", "motorcycle",                        EmojiCategory.Travel,      ["motorbike","motorcycle","bike"]),
        new("✈️", "airplane",                          EmojiCategory.Travel,      ["plane","fly","travel","flight"]),
        new("🚀", "rocket",                            EmojiCategory.Travel,      ["rocket","space","launch","ship"]),
        new("🛸", "flying saucer",                     EmojiCategory.Travel,      ["ufo","alien","space"]),
        new("🚁", "helicopter",                        EmojiCategory.Travel,      ["helicopter","fly","rotor"]),
        new("🚢", "ship",                              EmojiCategory.Travel,      ["ship","cruise","ocean","boat"]),
        new("⛵", "sailboat",                           EmojiCategory.Travel,      ["sail","boat","sea","wind"]),
        new("🚤", "speedboat",                         EmojiCategory.Travel,      ["boat","speed","water"]),
        new("🏠", "house",                             EmojiCategory.Travel,      ["home","house","building"]),
        new("🏡", "house with garden",                 EmojiCategory.Travel,      ["home","garden","house"]),
        new("🏢", "office building",                   EmojiCategory.Travel,      ["office","building","work"]),
        new("🏨", "hotel",                             EmojiCategory.Travel,      ["hotel","accommodation","stay"]),
        new("🏦", "bank",                              EmojiCategory.Travel,      ["bank","money","finance"]),
        new("🗺️", "world map",                         EmojiCategory.Travel,      ["map","travel","world","globe"]),
        new("🏔️", "snow-capped mountain",              EmojiCategory.Travel,      ["mountain","peak","snow","hike"]),
        new("🌋", "volcano",                           EmojiCategory.Travel,      ["volcano","eruption","lava"]),
        new("🏖️", "beach with umbrella",               EmojiCategory.Travel,      ["beach","summer","vacation","sun"]),
        new("🏝️", "desert island",                     EmojiCategory.Travel,      ["island","tropical","vacation"]),

        // ── Activities ────────────────────────────────────────────────────────
        new("⚽", "soccer ball",                        EmojiCategory.Activities,  ["soccer","football","sport"]),
        new("🏀", "basketball",                        EmojiCategory.Activities,  ["basketball","sport","nba"]),
        new("🏈", "american football",                 EmojiCategory.Activities,  ["football","nfl","sport"]),
        new("⚾", "baseball",                           EmojiCategory.Activities,  ["baseball","sport","mlb"]),
        new("🎾", "tennis",                            EmojiCategory.Activities,  ["tennis","sport","wimbledon"]),
        new("🏸", "badminton",                         EmojiCategory.Activities,  ["badminton","sport","shuttle"]),
        new("🥊", "boxing glove",                      EmojiCategory.Activities,  ["boxing","fight","sport"]),
        new("🥋", "martial arts uniform",              EmojiCategory.Activities,  ["karate","taekwondo","martial arts"]),
        new("🏊", "person swimming",                   EmojiCategory.Activities,  ["swim","pool","water","sport"]),
        new("🏋️", "person lifting weights",            EmojiCategory.Activities,  ["gym","weights","strong","sport"]),
        new("🧘", "person in lotus position",          EmojiCategory.Activities,  ["yoga","meditation","calm"]),
        new("🎯", "bullseye",                          EmojiCategory.Activities,  ["target","darts","accuracy"]),
        new("🎱", "pool 8 ball",                       EmojiCategory.Activities,  ["billiards","pool","eight ball"]),
        new("♟️", "chess pawn",                        EmojiCategory.Activities,  ["chess","strategy","game"]),
        new("🧩", "puzzle piece",                      EmojiCategory.Activities,  ["puzzle","jigsaw","problem"]),
        new("🎲", "game die",                          EmojiCategory.Activities,  ["dice","roll","random","game"]),
        new("🎭", "performing arts",                   EmojiCategory.Activities,  ["theater","drama","masks","show"]),
        new("🎨", "artist palette",                    EmojiCategory.Activities,  ["art","paint","creative","draw"]),
        new("🎬", "clapper board",                     EmojiCategory.Activities,  ["film","movie","action","cinema"]),
        new("🎤", "microphone",                        EmojiCategory.Activities,  ["mic","sing","karaoke","voice"]),
        new("🎧", "headphone",                         EmojiCategory.Activities,  ["music","listen","audio","headset"]),
        new("🎸", "guitar",                            EmojiCategory.Activities,  ["guitar","music","rock","string"]),
        new("🎹", "musical keyboard",                  EmojiCategory.Activities,  ["piano","keyboard","music","keys"]),
        new("🎺", "trumpet",                           EmojiCategory.Activities,  ["trumpet","music","jazz","brass"]),
        new("🎻", "violin",                            EmojiCategory.Activities,  ["violin","music","classical","string"]),

        // ── Objects ───────────────────────────────────────────────────────────
        new("💡", "light bulb",                        EmojiCategory.Objects,     ["idea","light","bright","think"]),
        new("📱", "mobile phone",                      EmojiCategory.Objects,     ["phone","smartphone","mobile","cell"]),
        new("💻", "laptop",                            EmojiCategory.Objects,     ["laptop","computer","work","pc"]),
        new("🖥️", "desktop computer",                  EmojiCategory.Objects,     ["desktop","computer","monitor","screen"]),
        new("⌨️", "keyboard",                          EmojiCategory.Objects,     ["keyboard","type","computer","input"]),
        new("📺", "television",                        EmojiCategory.Objects,     ["tv","television","watch","screen"]),
        new("📷", "camera",                            EmojiCategory.Objects,     ["camera","photo","picture","snap"]),
        new("📹", "video camera",                      EmojiCategory.Objects,     ["video","camera","record","film"]),
        new("📞", "telephone receiver",                EmojiCategory.Objects,     ["phone","call","talk","ring"]),
        new("🔋", "battery",                           EmojiCategory.Objects,     ["battery","power","charge","energy"]),
        new("🔧", "wrench",                            EmojiCategory.Objects,     ["wrench","fix","tool","repair"]),
        new("🔩", "nut and bolt",                      EmojiCategory.Objects,     ["bolt","nut","screw","tool","fix"]),
        new("⚙️", "gear",                              EmojiCategory.Objects,     ["gear","settings","cog","config"]),
        new("🔑", "key",                               EmojiCategory.Objects,     ["key","lock","access","open"]),
        new("🗝️", "old key",                           EmojiCategory.Objects,     ["key","antique","lock","old"]),
        new("🔒", "locked",                            EmojiCategory.Objects,     ["lock","secure","private","closed"]),
        new("🔓", "unlocked",                          EmojiCategory.Objects,     ["unlock","open","access","free"]),
        new("📚", "books",                             EmojiCategory.Objects,     ["books","study","library","education"]),
        new("📖", "open book",                         EmojiCategory.Objects,     ["book","read","study","learn"]),
        new("📝", "memo",                              EmojiCategory.Objects,     ["note","write","memo","pencil"]),
        new("✏️", "pencil",                            EmojiCategory.Objects,     ["pencil","write","draw","edit"]),
        new("🖊️", "pen",                               EmojiCategory.Objects,     ["pen","write","ink","sign"]),
        new("📌", "pushpin",                           EmojiCategory.Objects,     ["pin","location","mark","map"]),
        new("📎", "paperclip",                         EmojiCategory.Objects,     ["clip","attach","paperclip","link"]),
        new("🧲", "magnet",                            EmojiCategory.Objects,     ["magnet","attract","magnetic","metal"]),

        // ── Symbols ───────────────────────────────────────────────────────────
        new("❤️", "red heart",                         EmojiCategory.Symbols,     ["love","heart","red"]),
        new("🧡", "orange heart",                      EmojiCategory.Symbols,     ["love","heart","orange"]),
        new("💛", "yellow heart",                      EmojiCategory.Symbols,     ["love","heart","yellow"]),
        new("💚", "green heart",                       EmojiCategory.Symbols,     ["love","heart","green"]),
        new("💙", "blue heart",                        EmojiCategory.Symbols,     ["love","heart","blue"]),
        new("💜", "purple heart",                      EmojiCategory.Symbols,     ["love","heart","purple"]),
        new("🖤", "black heart",                       EmojiCategory.Symbols,     ["love","heart","black"]),
        new("🤍", "white heart",                       EmojiCategory.Symbols,     ["love","heart","white"]),
        new("🤎", "brown heart",                       EmojiCategory.Symbols,     ["love","heart","brown"]),
        new("💔", "broken heart",                      EmojiCategory.Symbols,     ["heartbreak","sad","love"]),
        new("💕", "two hearts",                        EmojiCategory.Symbols,     ["love","hearts","couple"]),
        new("💯", "hundred points",                    EmojiCategory.Symbols,     ["perfect","100","score","full"]),
        new("✅", "check mark button",                  EmojiCategory.Symbols,     ["check","done","correct","yes","ok"]),
        new("❌", "cross mark",                        EmojiCategory.Symbols,     ["no","wrong","cancel","x","remove"]),
        new("⚠️", "warning",                           EmojiCategory.Symbols,     ["warning","caution","alert","danger"]),
        new("⬆️", "up arrow",                          EmojiCategory.Symbols,     ["up","arrow","increase","north"]),
        new("⬇️", "down arrow",                        EmojiCategory.Symbols,     ["down","arrow","decrease","south"]),
        new("⬅️", "left arrow",                        EmojiCategory.Symbols,     ["left","arrow","back","west"]),
        new("➡️", "right arrow",                       EmojiCategory.Symbols,     ["right","arrow","next","east"]),
        new("🔴", "red circle",                        EmojiCategory.Symbols,     ["red","circle","dot","stop"]),
        new("🟡", "yellow circle",                     EmojiCategory.Symbols,     ["yellow","circle","dot"]),
        new("🟢", "green circle",                      EmojiCategory.Symbols,     ["green","circle","dot","ok","go"]),
        new("🔵", "blue circle",                       EmojiCategory.Symbols,     ["blue","circle","dot"]),
        new("🟣", "purple circle",                     EmojiCategory.Symbols,     ["purple","circle","dot"]),
        new("⭐", "star",                               EmojiCategory.Symbols,     ["star","favorite","rating","gold"]),

        // ── Flags ─────────────────────────────────────────────────────────────
        new("🏁", "chequered flag",                    EmojiCategory.Flags,       ["race","finish","flag","checkered"]),
        new("🚩", "triangular flag",                   EmojiCategory.Flags,       ["flag","red","mark","point"]),
        new("🎌", "crossed flags",                     EmojiCategory.Flags,       ["japan","flag","celebration"]),
        new("🏴", "black flag",                        EmojiCategory.Flags,       ["pirate","flag","dark","black"]),
        new("🏳️", "white flag",                        EmojiCategory.Flags,       ["surrender","peace","flag","white"]),
        new("🏳️‍🌈", "rainbow flag",                  EmojiCategory.Flags,       ["pride","rainbow","lgbtq","flag"]),
        new("🏴‍☠️", "pirate flag",                    EmojiCategory.Flags,       ["pirate","skull","jolly roger","flag"]),
        new("🇺🇸", "United States",                   EmojiCategory.Flags,       ["usa","america","flag","us"]),
        new("🇬🇧", "United Kingdom",                  EmojiCategory.Flags,       ["uk","britain","england","flag"]),
        new("🇪🇺", "European Union",                  EmojiCategory.Flags,       ["eu","europe","flag","union"]),
        new("🇩🇪", "Germany",                         EmojiCategory.Flags,       ["germany","deutsch","flag","de"]),
        new("🇫🇷", "France",                          EmojiCategory.Flags,       ["france","french","flag","fr"]),
        new("🇯🇵", "Japan",                           EmojiCategory.Flags,       ["japan","japanese","flag","jp"]),
        new("🇨🇳", "China",                           EmojiCategory.Flags,       ["china","chinese","flag","cn"]),
        new("🇮🇳", "India",                           EmojiCategory.Flags,       ["india","indian","flag","in"]),
        new("🇧🇷", "Brazil",                          EmojiCategory.Flags,       ["brazil","brazilian","flag","br"]),
        new("🇨🇦", "Canada",                          EmojiCategory.Flags,       ["canada","canadian","flag","ca"]),
        new("🇦🇺", "Australia",                       EmojiCategory.Flags,       ["australia","australian","flag","au"]),
        new("🇰🇷", "South Korea",                     EmojiCategory.Flags,       ["korea","korean","flag","kr"]),
        new("🇪🇸", "Spain",                           EmojiCategory.Flags,       ["spain","spanish","flag","es"]),
    };
}
