using System.Text.Json.Serialization;

namespace Tempo.Blazor.DocumentEditor.Models;

/// <summary>Block type used by the document editor JSON model.</summary>
public enum DocumentBlockType
{
    /// <summary>Paragraph block.</summary>
    Paragraph,

    /// <summary>Heading block.</summary>
    Heading,

    /// <summary>List block.</summary>
    List,

    /// <summary>Quote block.</summary>
    Quote,

    /// <summary>Table block.</summary>
    Table,

    /// <summary>Image block.</summary>
    Image,

    /// <summary>Page break block.</summary>
    PageBreak,

    /// <summary>Structured document tag block.</summary>
    ContentControl,

    /// <summary>Preformatted code block. Its text is never parsed for inline markup.</summary>
    Code
}

/// <summary>Text alignment for paragraph-like document blocks.</summary>
public enum DocumentTextAlignment
{
    /// <summary>Align text to the start edge.</summary>
    Left,

    /// <summary>Center text horizontally.</summary>
    Center,

    /// <summary>Align text to the end edge.</summary>
    Right,

    /// <summary>Justify text across the paragraph width.</summary>
    Justify
}

/// <summary>Alignment mode used by a paragraph tab stop.</summary>
public enum DocumentTabStopAlignment
{
    /// <summary>Start following text at the tab stop position.</summary>
    Left,

    /// <summary>Center following text around the tab stop position.</summary>
    Center,

    /// <summary>End following text at the tab stop position.</summary>
    Right,

    /// <summary>Align the decimal separator of following text to the tab stop position.</summary>
    Decimal,

    /// <summary>Draw a vertical bar at the tab stop position.</summary>
    Bar
}

/// <summary>Leader style drawn across the tab advance.</summary>
public enum DocumentTabStopLeader
{
    /// <summary>No leader is drawn.</summary>
    None,

    /// <summary>Dotted leader.</summary>
    Dots,

    /// <summary>Dashed leader.</summary>
    Dash,

    /// <summary>Underline leader.</summary>
    Underline
}

/// <summary>Paragraph tab stop definition measured in points from the paragraph left edge.</summary>
public sealed class DocumentTabStop
{
    /// <summary>Tab stop position in points from the paragraph left edge.</summary>
    public double Position { get; set; }

    /// <summary>Alignment mode applied to the text after the tab character.</summary>
    public DocumentTabStopAlignment Alignment { get; set; } = DocumentTabStopAlignment.Left;

    /// <summary>Leader drawn between the tab character and aligned text.</summary>
    public DocumentTabStopLeader Leader { get; set; } = DocumentTabStopLeader.None;
}

/// <summary>Paragraph-level formatting for text blocks.</summary>
public class DocumentParagraphProperties
{
    /// <summary>Paragraph text alignment.</summary>
    public DocumentTextAlignment Alignment { get; set; } = DocumentTextAlignment.Left;

    /// <summary>Line spacing multiplier, for example 1, 1.15, 1.5, or 2.</summary>
    public double LineSpacing { get; set; } = 1;

    /// <summary>Spacing before the paragraph in points.</summary>
    public double SpacingBefore { get; set; }

    /// <summary>Spacing after the paragraph in points.</summary>
    public double SpacingAfter { get; set; }

    /// <summary>Left paragraph indent in points.</summary>
    public double LeftIndent { get; set; }

    /// <summary>Right paragraph indent in points.</summary>
    public double RightIndent { get; set; }

    /// <summary>First-line indent in points. Negative values represent hanging indent.</summary>
    public double FirstLineIndent { get; set; }

    /// <summary>Default tab interval in points used when no explicit tab stop follows the current position.</summary>
    public double DefaultTabWidth { get; set; } = 36;

    /// <summary>Explicit paragraph tab stops ordered by position in points.</summary>
    public List<DocumentTabStop> TabStops { get; set; } = [];
}

/// <summary>Partial paragraph formatting update generated by editor commands.</summary>
public class DocumentParagraphPropertiesPatch
{
    /// <summary>Optional paragraph text alignment.</summary>
    public DocumentTextAlignment? Alignment { get; set; }

    /// <summary>Optional line spacing multiplier.</summary>
    public double? LineSpacing { get; set; }

    /// <summary>Optional spacing before the paragraph in points.</summary>
    public double? SpacingBefore { get; set; }

    /// <summary>Optional spacing after the paragraph in points.</summary>
    public double? SpacingAfter { get; set; }

    /// <summary>Optional absolute left paragraph indent in points.</summary>
    public double? LeftIndent { get; set; }

    /// <summary>Optional absolute right paragraph indent in points.</summary>
    public double? RightIndent { get; set; }

    /// <summary>Optional absolute first-line indent in points.</summary>
    public double? FirstLineIndent { get; set; }

    /// <summary>Optional left indent delta in points.</summary>
    public double? LeftIndentDelta { get; set; }

    /// <summary>Optional right indent delta in points.</summary>
    public double? RightIndentDelta { get; set; }

    /// <summary>Optional first-line indent delta in points.</summary>
    public double? FirstLineIndentDelta { get; set; }

    /// <summary>Optional default tab interval in points.</summary>
    public double? DefaultTabWidth { get; set; }

    /// <summary>Optional replacement list of explicit paragraph tab stops.</summary>
    public List<DocumentTabStop>? TabStops { get; set; }
}

/// <summary>Single ordered document block.</summary>
public class DocumentBlock
{
    /// <summary>Stable block identifier.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Optional section identifier.</summary>
    public string? SectionId { get; set; }

    /// <summary>Block type.</summary>
    public DocumentBlockType Type { get; set; } = DocumentBlockType.Paragraph;

    /// <summary>Sort order within the document.</summary>
    public double Order { get; set; }

    /// <summary>Paragraph-level formatting for text-like blocks.</summary>
    public DocumentParagraphProperties ParagraphProperties { get; set; } = new();

    /// <summary>Block content.</summary>
    public DocumentBlockContent Content { get; set; } = new ParagraphBlockContent();
}

/// <summary>Base class for block content payloads.</summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(ParagraphBlockContent), "paragraph")]
[JsonDerivedType(typeof(HeadingBlockContent), "heading")]
[JsonDerivedType(typeof(ListBlockContent), "list")]
[JsonDerivedType(typeof(QuoteBlockContent), "quote")]
[JsonDerivedType(typeof(TableBlockContent), "table")]
[JsonDerivedType(typeof(ImageBlockContent), "image")]
[JsonDerivedType(typeof(PageBreakBlockContent), "pageBreak")]
[JsonDerivedType(typeof(ContentControlBlockContent), "contentControl")]
public abstract class DocumentBlockContent
{
}

/// <summary>Preformatted code block content. The code is stored verbatim, never as inlines.</summary>
public class CodeBlockContent : DocumentBlockContent
{
    /// <summary>Language identifier from the opening fence, or <c>null</c> when the fence carried none.</summary>
    public string? Language { get; set; }

    /// <summary>The code, with newlines preserved and no inline markup applied.</summary>
    public string Code { get; set; } = string.Empty;
}

/// <summary>Paragraph block content.</summary>
public class ParagraphBlockContent : DocumentBlockContent
{
    /// <summary>Inline paragraph content.</summary>
    public List<InlineContent> Inlines { get; set; } = [];

    /// <summary>Optional caption metadata when this paragraph represents a generated figure, table, or equation caption.</summary>
    public DocumentCaptionMetadata? Caption { get; set; }

    /// <summary>Optional generated table-of-contents metadata when this paragraph represents a TOC entry.</summary>
    public DocumentTableOfContentsMetadata? TableOfContents { get; set; }
}

/// <summary>Block-level structured document tag content.</summary>
public class ContentControlBlockContent : DocumentBlockContent
{
    /// <summary>Structured document tag metadata and value.</summary>
    public DocumentContentControl Control { get; set; } = new()
    {
        Scope = DocumentContentControlScope.Block
    };

    /// <summary>Nested blocks owned by this structured document tag.</summary>
    public List<DocumentBlock> Blocks { get; set; } = [];
}

/// <summary>Caption metadata preserved for generated captions, SEQ fields, and tables of figures.</summary>
public sealed class DocumentCaptionMetadata
{
    /// <summary>Stable caption identifier used by cross-reference fields.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Caption kind, for example figure, table, or equation.</summary>
    public string Kind { get; set; } = "figure";

    /// <summary>Displayed caption label.</summary>
    public string Label { get; set; } = "Figure";

    /// <summary>Caption text after the generated sequence label.</summary>
    public string Text { get; set; } = string.Empty;

    /// <summary>Resolved sequence number.</summary>
    public int? Number { get; set; }

    /// <summary>Resolved label and number, for example Figure 2.</summary>
    public string? NumberLabel { get; set; }
}

/// <summary>Semantic metadata preserved for generated table-of-contents entry paragraphs.</summary>
public sealed class DocumentTableOfContentsMetadata
{
    /// <summary>Stable table-of-contents identifier shared by all entry paragraphs in one generated TOC.</summary>
    public string TocId { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Whether this paragraph is a generated TOC entry.</summary>
    public bool IsEntry { get; set; }

    /// <summary>Heading block targeted by the TOC entry.</summary>
    public string TargetBlockId { get; set; } = string.Empty;

    /// <summary>Heading outline level represented by the entry.</summary>
    public int Level { get; set; } = 1;

    /// <summary>Heading text captured when the TOC was generated.</summary>
    public string Text { get; set; } = string.Empty;

    /// <summary>One-based page number captured from the canvas layout cache.</summary>
    public int PageNumber { get; set; } = 1;

    /// <summary>Zero-based page index captured from the canvas layout cache.</summary>
    public int PageIndex { get; set; }

    /// <summary>Vertical coordinate of the target heading on its page.</summary>
    public double Y { get; set; }

    /// <summary>Maximum heading levels included by this generated TOC.</summary>
    public int Levels { get; set; } = 3;
}

/// <summary>Heading block content.</summary>
public class HeadingBlockContent : DocumentBlockContent
{
    /// <summary>Heading level, usually 1-6.</summary>
    public int Level { get; set; } = 1;

    /// <summary>Inline heading content.</summary>
    public List<InlineContent> Inlines { get; set; } = [];
}

/// <summary>List block content.</summary>
public class ListBlockContent : DocumentBlockContent
{
    /// <summary>Whether the list is ordered.</summary>
    public bool Ordered { get; set; }

    /// <summary>Zero-based nesting level.</summary>
    public int IndentLevel { get; set; }

    /// <summary>Starting number for ordered lists.</summary>
    public int StartNumber { get; set; } = 1;

    /// <summary>Optional concrete numbering instance identifier.</summary>
    public string? NumberingId { get; set; }

    /// <summary>Optional abstract numbering definition identifier.</summary>
    public string? AbstractNumberingId { get; set; }

    /// <summary>Optional list style identifier.</summary>
    public string? ListStyleId { get; set; }

    /// <summary>Optional numbering format override for this item level.</summary>
    public string? NumberFormat { get; set; }

    /// <summary>Optional numbering text template override, for example <c>%1.%2.</c>.</summary>
    public string? LevelText { get; set; }

    /// <summary>Optional suffix after the list label: tab, space, or none.</summary>
    public string? Suffix { get; set; }

    /// <summary>Optional absolute label indent for this list item in points.</summary>
    public double? LabelIndent { get; set; }

    /// <summary>Optional hanging indent for this list item in points.</summary>
    public double? HangingIndent { get; set; }

    /// <summary>Whether this item restarts numbering at its level.</summary>
    public bool RestartNumbering { get; set; }

    /// <summary>
    /// Checkbox state of a GFM task-list item (<c>- [ ]</c> / <c>- [x]</c>).
    /// <c>null</c> for an ordinary list item, which has no checkbox at all.
    /// </summary>
    public bool? IsChecked { get; set; }

    /// <summary>Whether this item explicitly continues the previous numbering sequence.</summary>
    public bool ContinueNumbering { get; set; }

    /// <summary>Optional explicit numbering value for this item.</summary>
    public int? NumberingValue { get; set; }

    /// <summary>Inline list item content.</summary>
    public List<InlineContent> Inlines { get; set; } = [];
}

/// <summary>Document-level numbering definition used by list blocks.</summary>
public class DocumentNumberingDefinition
{
    /// <summary>Concrete numbering instance identifier.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Abstract numbering definition identifier shared by compatible list instances.</summary>
    public string AbstractId { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Optional display name.</summary>
    public string? Name { get; set; }

    /// <summary>Optional list style identifier.</summary>
    public string? StyleId { get; set; }

    /// <summary>Level definitions from 0 to 8.</summary>
    public List<DocumentNumberingLevel> Levels { get; set; } = [];
}

/// <summary>Numbering level definition.</summary>
public class DocumentNumberingLevel
{
    /// <summary>Zero-based list level.</summary>
    public int Level { get; set; }

    /// <summary>Numbering format: decimal, lower-roman, upper-roman, lower-letter, upper-letter, bullet, legal, or none.</summary>
    public string Format { get; set; } = "decimal";

    /// <summary>Label text template, for example <c>%1.</c> or <c>%1.%2.</c>.</summary>
    public string Text { get; set; } = "%1.";

    /// <summary>First value used by this level.</summary>
    public int StartAt { get; set; } = 1;

    /// <summary>Suffix after the label: tab, space, or none.</summary>
    public string Suffix { get; set; } = "tab";

    /// <summary>Label indent in points.</summary>
    public double Indent { get; set; }

    /// <summary>Hanging indent in points.</summary>
    public double Hanging { get; set; } = 18;

    /// <summary>Bullet glyph when <see cref="Format"/> is bullet.</summary>
    public string? Bullet { get; set; }
}

/// <summary>Named list style referencing a numbering definition.</summary>
public class DocumentListStyle
{
    /// <summary>Stable list style identifier.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>User-facing style name.</summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>Referenced concrete numbering identifier.</summary>
    public string NumberingId { get; set; } = string.Empty;

    /// <summary>Whether the style should be shown in quick style pickers.</summary>
    public bool IsQuickStyle { get; set; }
}

/// <summary>Quote block content.</summary>
public class QuoteBlockContent : DocumentBlockContent
{
    /// <summary>Inline quote content.</summary>
    public List<InlineContent> Inlines { get; set; } = [];
}

/// <summary>Table block content.</summary>
public class TableBlockContent : DocumentBlockContent
{
    /// <summary>Rows in the table.</summary>
    public List<TableRowContent> Rows { get; set; } = [];

    /// <summary>Presentation properties for the table as a whole.</summary>
    public TableLayoutContent Layout { get; set; } = new();

    /// <summary>
    /// Per-column horizontal alignment, indexed by column. Shorter than the widest row means the
    /// remaining columns are <see cref="TableColumnAlignment.None"/>.
    /// </summary>
    public List<TableColumnAlignment> ColumnAlignments { get; set; } = [];
}

/// <summary>Horizontal alignment of a table column, as expressed by a GFM table separator row.</summary>
public enum TableColumnAlignment
{
    /// <summary>No explicit alignment (<c>---</c>); the renderer decides.</summary>
    None = 0,

    /// <summary>Align column content to the leading edge (<c>:---</c>).</summary>
    Left,

    /// <summary>Center column content (<c>:---:</c>).</summary>
    Center,

    /// <summary>Align column content to the trailing edge (<c>---:</c>).</summary>
    Right
}

/// <summary>Presentation properties for a document table.</summary>
public class TableLayoutContent
{
    /// <summary>Optional table width in pixels or percent, depending on renderer context.</summary>
    public double? Width { get; set; }

    /// <summary>Horizontal table alignment.</summary>
    public TableHorizontalAlignment Alignment { get; set; } = TableHorizontalAlignment.Left;

    /// <summary>Default cell padding in pixels.</summary>
    public double? CellPadding { get; set; }

    /// <summary>Optional table background color.</summary>
    public string? BackgroundColor { get; set; }

    /// <summary>Table border styles.</summary>
    public TableCellBorders Borders { get; set; } = new();

    /// <summary>Optional named table style identifier.</summary>
    public string? StyleId { get; set; }

    /// <summary>Whether the first row should repeat when the table crosses a page boundary.</summary>
    public bool RepeatHeaderRows { get; set; }

    /// <summary>Whether alternating row banding should be applied.</summary>
    public bool BandedRows { get; set; }

    /// <summary>Whether alternating column banding should be applied.</summary>
    public bool BandedColumns { get; set; }

    /// <summary>Whether the first row should use the header style.</summary>
    public bool HeaderRow { get; set; }

    /// <summary>Whether the last row should use the total-row style.</summary>
    public bool TotalRow { get; set; }

    /// <summary>Optional spacing between adjacent cells in CSS pixels.</summary>
    public double? CellSpacing { get; set; }

    /// <summary>Table style palette used by canvas rendering.</summary>
    public TableStyleOptions Style { get; set; } = new();
}

/// <summary>Table style palette and conditional formatting toggles.</summary>
public class TableStyleOptions
{
    /// <summary>Header row fill.</summary>
    public string? HeaderBackgroundColor { get; set; }

    /// <summary>Total row fill.</summary>
    public string? TotalBackgroundColor { get; set; }

    /// <summary>Odd band fill.</summary>
    public string? BandedRowBackgroundColor { get; set; }

    /// <summary>Alternating column band fill.</summary>
    public string? BandedColumnBackgroundColor { get; set; }

    /// <summary>Default cell fill.</summary>
    public string? CellBackgroundColor { get; set; }

    /// <summary>Default border color.</summary>
    public string? BorderColor { get; set; }
}

/// <summary>Horizontal table alignment.</summary>
public enum TableHorizontalAlignment
{
    /// <summary>Align the table to the leading edge.</summary>
    Left,

    /// <summary>Center the table.</summary>
    Center,

    /// <summary>Align the table to the trailing edge.</summary>
    Right
}

/// <summary>Table row content.</summary>
public class TableRowContent
{
    /// <summary>Cells in the row.</summary>
    public List<TableCellContent> Cells { get; set; } = [];
}

/// <summary>Table cell content.</summary>
public class TableCellContent
{
    /// <summary>Stable cell identifier.</summary>
    public string Id { get; set; } = Guid.NewGuid().ToString("N");

    /// <summary>Column span for merged cells.</summary>
    public int ColumnSpan { get; set; } = 1;

    /// <summary>Row span for merged cells.</summary>
    public int RowSpan { get; set; } = 1;

    /// <summary>Whether this cell is rendered as a header cell (&lt;th&gt;).</summary>
    public bool IsHeader { get; set; }

    /// <summary>Merge metadata.</summary>
    public TableCellMerge Merge { get; set; } = new();

    /// <summary>Optional cell width in points or pixels, depending on renderer context.</summary>
    public double? Width { get; set; }

    /// <summary>Optional cell background color.</summary>
    public string? BackgroundColor { get; set; }

    /// <summary>Cell border styles.</summary>
    public TableCellBorders Borders { get; set; } = new();

    /// <summary>Vertical alignment for content inside the cell.</summary>
    public TableCellVerticalAlignment VerticalAlignment { get; set; } = TableCellVerticalAlignment.Top;

    /// <summary>Optional cell padding in pixels.</summary>
    public double? Padding { get; set; }

    /// <summary>Blocks nested in the table cell.</summary>
    public List<DocumentBlock> Blocks { get; set; } = [];
}

/// <summary>Vertical alignment for content inside a table cell.</summary>
public enum TableCellVerticalAlignment
{
    /// <summary>Align content to the top of the cell.</summary>
    Top,

    /// <summary>Align content to the middle of the cell.</summary>
    Middle,

    /// <summary>Align content to the bottom of the cell.</summary>
    Bottom
}

/// <summary>CSS-like border styles for a table cell.</summary>
public class TableCellBorders
{
    /// <summary>Top border style.</summary>
    public string? Top { get; set; }

    /// <summary>Right border style.</summary>
    public string? Right { get; set; }

    /// <summary>Bottom border style.</summary>
    public string? Bottom { get; set; }

    /// <summary>Left border style.</summary>
    public string? Left { get; set; }
}

/// <summary>Metadata describing how a table cell participates in a merge.</summary>
public class TableCellMerge
{
    /// <summary>Whether this cell is the origin of a merged area.</summary>
    public bool IsOrigin { get; set; } = true;

    /// <summary>Optional origin cell id when this cell is covered by another merged cell.</summary>
    public string? OriginCellId { get; set; }
}

/// <summary>Table cell span value object.</summary>
public class TableCellSpan
{
    /// <summary>Column span.</summary>
    public int Columns { get; set; } = 1;

    /// <summary>Row span.</summary>
    public int Rows { get; set; } = 1;
}

/// <summary>Image block content.</summary>
public class ImageBlockContent : DocumentBlockContent
{
    /// <summary>Image source kind.</summary>
    public DocumentImageSource Source { get; set; } = DocumentImageSource.Url;

    /// <summary>Direct image URL when <see cref="Source"/> is <see cref="DocumentImageSource.Url"/>.</summary>
    public string? Url { get; set; }

    /// <summary>Provider asset id when <see cref="Source"/> is asset-backed.</summary>
    public string? AssetId { get; set; }

    /// <summary>Alternative text.</summary>
    public string? AltText { get; set; }

    /// <summary>Whether assistive technology should ignore this image as decorative.</summary>
    public bool IsDecorative { get; set; }

    /// <summary>Optional caption.</summary>
    public string? Caption { get; set; }

    /// <summary>Source/default image size. User-controlled rendered size is stored in <see cref="Layout"/>.</summary>
    public DocumentImageSize Size { get; set; } = new();

    /// <summary>Intrinsic image size reported by the image asset once loaded.</summary>
    public DocumentImageSize NaturalSize { get; set; } = new();

    /// <summary>Image alignment.</summary>
    public DocumentImageAlignment Alignment { get; set; } = DocumentImageAlignment.Center;

    /// <summary>Canonical object layout used for inline, anchored, and fixed image positioning.</summary>
    public DocumentObjectLayout Layout { get; set; } = DocumentObjectLayout.Inline();

    /// <summary>Previous floating layout DTO kept as a non-serialized transition shim for internal call sites.</summary>
    [JsonIgnore]
    public DocumentFloatingLayout? FloatingLayout
    {
        get => Layout?.ToFloatingLayout();
        set => Layout = DocumentObjectLayout.FromFloatingLayout(value);
    }

    /// <summary>Optional hyperlink URL wrapping the image.</summary>
    public string? LinkUrl { get; set; }
}

/// <summary>Source kind for a document image.</summary>
public enum DocumentImageSource
{
    /// <summary>Image is loaded from a direct URL.</summary>
    Url,

    /// <summary>Image is loaded from a provider-managed asset.</summary>
    Asset,

    /// <summary>Image is a local/pending clipboard asset.</summary>
    Clipboard
}

/// <summary>Image alignment in the document flow.</summary>
public enum DocumentImageAlignment
{
    /// <summary>Align to start/left.</summary>
    Start,

    /// <summary>Center align.</summary>
    Center,

    /// <summary>Align to end/right.</summary>
    End
}

/// <summary>Document image size metadata.</summary>
public class DocumentImageSize
{
    /// <summary>Image width in points or pixels, depending on renderer context.</summary>
    public double? Width { get; set; }

    /// <summary>Image height in points or pixels, depending on renderer context.</summary>
    public double? Height { get; set; }

    /// <summary>Whether aspect ratio should be preserved during resize.</summary>
    public bool LockAspectRatio { get; set; } = true;
}

/// <summary>Page break block content.</summary>
public class PageBreakBlockContent : DocumentBlockContent
{
    /// <summary>Section or column break behavior represented by this break block.</summary>
    public DocumentSectionBreakType BreakType { get; set; } = DocumentSectionBreakType.Page;

    /// <summary>Optional next section identifier.</summary>
    public string? NextSectionId { get; set; }
}

/// <summary>Document break behavior for page, section, and column breaks.</summary>
public enum DocumentSectionBreakType
{
    /// <summary>Regular page break.</summary>
    Page,

    /// <summary>Section break that starts the next section on the following page.</summary>
    NextPage,

    /// <summary>Section break that starts the next section at the current position when possible.</summary>
    Continuous,

    /// <summary>Section break that starts the next section on an even page number.</summary>
    EvenPage,

    /// <summary>Section break that starts the next section on an odd page number.</summary>
    OddPage,

    /// <summary>Column break that starts content in the next text column.</summary>
    Column
}
