namespace Tempo.Blazor.DocumentEditor.Models;

/// <summary>Patch generated by the WYSIWYG JS engine and applied by Blazor.</summary>
public sealed class WysiwygPatch
{
    /// <summary>Patch type: InsertText, InsertInline, DeleteRange, SetMarks, SetParagraphProperties, InsertBlock, SplitBlock, InsertSoftBreak, UpdateBlock, RemoveBlock, Paste.</summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>Stable JS runtime operation identifier for persistence, collaboration, and undo metadata.</summary>
    public string? OperationId { get; set; }

    /// <summary>Input data (e.g. inserted text).</summary>
    public string? Data { get; set; }

    /// <summary>Optional hyperlink title for link mark patches.</summary>
    public string? LinkTitle { get; set; }

    /// <summary>Inline content payload for InsertInline patches.</summary>
    public InlineContent? Inline { get; set; }

    /// <summary>Selection snapshot at the time of the patch.</summary>
    public WysiwygSelectionSnapshot? Selection { get; set; }

    /// <summary>Selection snapshot before the browser/input transaction changed the DOM.</summary>
    public WysiwygSelectionSnapshot? BeforeSelection { get; set; }

    /// <summary>Expected selection snapshot after the browser/input transaction changed the DOM.</summary>
    public WysiwygSelectionSnapshot? AfterSelection { get; set; }

    /// <summary>Transaction id for undo batching.</summary>
    public string? TransactionId { get; set; }

    /// <summary>Protocol version of the patch.</summary>
    public int ProtocolVersion { get; set; } = 1;

    /// <summary>Pasted HTML content.</summary>
    public string? Html { get; set; }

    /// <summary>Pasted plain text content.</summary>
    public string? Plain { get; set; }

    /// <summary>Whether the clipboard contained an image.</summary>
    public bool HasImage { get; set; }

    /// <summary>Mark type for SetMarks patches (e.g. Bold, Italic, Underline).</summary>
    public string? MarkType { get; set; }

    /// <summary>Block type for InsertBlock patches (e.g. Paragraph, Heading, Image).</summary>
    public string? BlockType { get; set; }

    /// <summary>Block data payload for InsertBlock or UpdateBlock patches.</summary>
    public DocumentBlock? Block { get; set; }

    /// <summary>Partial paragraph formatting payload for SetParagraphProperties patches.</summary>
    public DocumentParagraphPropertiesPatch? ParagraphProperties { get; set; }

    /// <summary>Number of characters to delete for DeleteRange patches.</summary>
    public int DeleteLength { get; set; }

    /// <summary>Heading level when BlockType is Heading.</summary>
    public int? HeadingLevel { get; set; }

    /// <summary>Stable revision identifier for track-changes patches generated by the JS engine.</summary>
    public string? RevisionId { get; set; }

    /// <summary>Revision type for track-changes patches (Insertion or Deletion).</summary>
    public string? RevisionType { get; set; }
}
