using System.Globalization;
using System.Net;
using System.Net.Sockets;
using System.Text.Json;
using Tempo.Blazor.E2E.CanvasEngine;
using Tempo.Reporting.Abstractions.Definitions;
using Tempo.Reporting.Engine.Fonts;
using Tempo.Reporting.Engine.Layout;
using Tempo.Reporting.Engine.Snapshot;

namespace Tempo.Blazor.E2E;

/// <summary>F5 reporting text layout visual gate.</summary>
[TestClass]
[TestCategory("Reporting")]
[TestCategory("Reporting:F5")]
[DoNotParallelize]
public sealed class ReportingF5TextLayoutE2ETests
{
    public TestContext TestContext { get; set; } = default!;

    [TestMethod]
    public async Task F5_ReportingHarness_RendersTextBoxLayoutScreenshot()
    {
        var snapshot = BuildSnapshot();
        var snapshotJson = ReportSnapshotJsonSerializer.Serialize(snapshot);

        await using var host = ReportingHarnessHost.Start(FindRepositoryRoot());
        using var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {
            Headless = true,
        });
        var browserContext = await browser.NewContextAsync(new BrowserNewContextOptions
        {
            ViewportSize = new ViewportSize { Width = 980, Height = 760 },
        });
        var page = await browserContext.NewPageAsync();
        await page.GotoAsync($"{host.BaseUrl}/reporting-harness.html", new PageGotoOptions
        {
            WaitUntil = WaitUntilState.Load,
            Timeout = 60_000,
        });
        await page.WaitForFunctionAsync("() => window.__tempoReportingHarness?.ready === true", new PageWaitForFunctionOptions { Timeout = 30_000 });

        var loadResultJson = await page.EvaluateAsync<string>(
            """
            async snapshotJson => {
                try {
                    return JSON.stringify({
                        ok: true,
                        summary: await window.__tempoReportingHarness.loadSnapshot(JSON.parse(snapshotJson), []),
                        message: ''
                    });
                } catch (error) {
                    return JSON.stringify({
                        ok: false,
                        summary: null,
                        message: `${error?.name || 'Error'}: ${error?.message || error}`
                    });
                }
            }
            """,
            snapshotJson);
        var loadResult = JsonSerializer.Deserialize<ReportingHarnessLoadResult>(
            loadResultJson,
            new JsonSerializerOptions(JsonSerializerDefaults.Web))
            ?? throw new AssertFailedException("Reporting harness returned an empty load result.");
        Assert.IsTrue(loadResult.Ok, loadResult.Message);
        var summary = loadResult.Summary ?? throw new AssertFailedException("Reporting harness did not return a summary.");

        Assert.IsTrue(summary.TextRunCount >= 24, "F5 snapshot must paint all text box runs.");
        Assert.IsTrue(summary.PaintedCommandCount >= summary.TextRunCount + 10, "F5 snapshot must include text, box, highlight, decoration and clip commands.");
        Assert.IsTrue(summary.TextRects.Any(rect => rect.Text.EndsWith("\u2026", StringComparison.Ordinal)), "Clipped textbox must expose an ellipsis run.");

        var canvasMetrics = await DocumentEditorCanvasVisualAssert.AssertCanvasNonBlankAsync(page.GetByTestId("reporting-canvas"));
        await DocumentEditorCanvasVisualAssert.AssertNoTextOverlapAsync(page);

        var screenshotDirectory = CreateScreenshotDirectory();
        var screenshotPath = Path.Combine(screenshotDirectory, "01-textbox-layout.png");
        await page.GetByTestId("reporting-harness-page").ScreenshotAsync(new LocatorScreenshotOptions
        {
            Path = screenshotPath,
            Type = ScreenshotType.Png,
        });

        var manifestPath = Path.Combine(screenshotDirectory, "manifest.json");
        await File.WriteAllTextAsync(
            manifestPath,
            JsonSerializer.Serialize(
                new
                {
                    phase = "F5",
                    testName = nameof(F5_ReportingHarness_RendersTextBoxLayoutScreenshot),
                    screenshotPath,
                    functionalReview = "The snapshot contains left, center, right, justify, grow and clipped text boxes generated by the C# text layout core; clipped text emits an ellipsis and a canvas clip region.",
                    uxReview = "The sample uses restrained report typography, visible alignment differences, readable line rhythm, subtle highlight/decoration examples and no overlapping text rectangles.",
                    canvasMetrics,
                    summary.TextRunCount,
                    summary.PaintedCommandCount,
                },
                new JsonSerializerOptions(JsonSerializerDefaults.Web) { WriteIndented = true }));

        TestContext.AddResultFile(screenshotPath);
        TestContext.AddResultFile(manifestPath);
        await browserContext.CloseAsync();
    }

    private static ReportSnapshot BuildSnapshot()
    {
        var measurer = new F5FixedTextMeasurer();
        var baseStyle = new ReportTextStyle
        {
            FontFamily = "Arial",
            FontSize = 14,
            Color = "#111827",
        };
        var accentStyle = baseStyle with
        {
            Bold = true,
            Underline = true,
            BackgroundColor = "#fef3c7",
            Color = "#1d4ed8",
        };
        var commands = new List<ReportSnapshotCommand>
        {
            ReportSnapshotCommand.Rectangle("page", 0, 0, 760, 560, "#ffffff", "#cbd5e1", 1),
            ReportSnapshotCommand.Rectangle("title-band", 34, 28, 692, 38, "#f8fafc", "#e2e8f0", 1),
            ReportSnapshotCommand.TextRun("title", "F5 TextBox layout core", 50, 54, 210, 18, "Arial", 18, "#0f172a", "700"),
        };

        AddBox(commands, measurer, "left", 48, 92, 206, 86, ReportHorizontalAlignment.Left, ReportVerticalAlignment.Top, false, baseStyle, "Left aligned text wraps at spaces and keeps a steady report rhythm.");
        AddBox(commands, measurer, "center", 278, 92, 206, 86, ReportHorizontalAlignment.Center, ReportVerticalAlignment.Middle, false, baseStyle, "Centered content stays balanced inside the padded text box.");
        AddBox(commands, measurer, "right", 508, 92, 206, 86, ReportHorizontalAlignment.Right, ReportVerticalAlignment.Bottom, false, baseStyle, "Right aligned totals sit against the trailing edge cleanly.");
        AddBox(commands, measurer, "justify", 48, 210, 306, 94, ReportHorizontalAlignment.Justify, ReportVerticalAlignment.Top, false, baseStyle, "Justified text expands spaces on wrapped lines only and leaves the final line natural.");
        AddBox(
            commands,
            measurer,
            "grow",
            384,
            210,
            330,
            46,
            ReportHorizontalAlignment.Left,
            ReportVerticalAlignment.Top,
            true,
            [
                new ReportRichTextRun("CanGrow ", accentStyle),
                new ReportRichTextRun("increases the text box height so styled runs keep all wrapped lines visible.", baseStyle),
            ]);
        AddBox(commands, measurer, "clip", 48, 350, 666, 42, ReportHorizontalAlignment.Left, ReportVerticalAlignment.Top, false, baseStyle, "Clipped text boxes keep their frame height and show an ellipsis when additional wrapped lines would overflow.");

        return new ReportSnapshot
        {
            SnapshotId = "f5-text-layout",
            Pages =
            [
                new ReportSnapshotPage
                {
                    PageNumber = 1,
                    Width = 760,
                    Height = 560,
                    Commands = commands,
                },
            ],
        };
    }

    private static void AddBox(
        List<ReportSnapshotCommand> commands,
        ITextMeasurer measurer,
        string id,
        double x,
        double y,
        double width,
        double height,
        ReportHorizontalAlignment horizontalAlignment,
        ReportVerticalAlignment verticalAlignment,
        bool canGrow,
        ReportTextStyle style,
        string text)
        => AddBox(
            commands,
            measurer,
            id,
            x,
            y,
            width,
            height,
            horizontalAlignment,
            verticalAlignment,
            canGrow,
            [new ReportRichTextRun(text, style)]);

    private static void AddBox(
        List<ReportSnapshotCommand> commands,
        ITextMeasurer measurer,
        string id,
        double x,
        double y,
        double width,
        double height,
        ReportHorizontalAlignment horizontalAlignment,
        ReportVerticalAlignment verticalAlignment,
        bool canGrow,
        IReadOnlyList<ReportRichTextRun> runs)
    {
        var layout = ReportTextBoxLayouter.Layout(
            new ReportTextBoxLayoutRequest
            {
                Id = id,
                X = x,
                Y = y,
                Width = width,
                Height = height,
                FillColor = "#ffffff",
                Border = ReportBorder.All("#cbd5e1", 1),
                Padding = new ReportThickness(10, 8, 10, 8),
                HorizontalAlignment = horizontalAlignment,
                VerticalAlignment = verticalAlignment,
                CanGrow = canGrow,
                Runs = runs.ToList(),
            },
            measurer);
        commands.AddRange(layout.ToSnapshotCommands());
    }

    private static string CreateScreenshotDirectory()
    {
        var directory = Path.Combine(
            FindRepositoryRoot().FullName,
            "tests",
            "Tempo.Blazor.E2E",
            "__screenshots__",
            "reporting",
            "f5");
        Directory.CreateDirectory(directory);
        return directory;
    }

    private static DirectoryInfo FindRepositoryRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null)
        {
            if (File.Exists(Path.Combine(current.FullName, "TempoBlazor.slnx")))
            {
                return current;
            }

            current = current.Parent;
        }

        throw new DirectoryNotFoundException("Could not locate TempoBlazor.slnx.");
    }

    private sealed class ReportingHarnessLoadResult
    {
        public bool Ok { get; set; }

        public ReportingHarnessSummary? Summary { get; set; }

        public string Message { get; set; } = string.Empty;
    }

    private sealed class ReportingHarnessSummary
    {
        public int CommandCount { get; set; }

        public int PaintedCommandCount { get; set; }

        public int TextRunCount { get; set; }

        public List<ReportingTextRect> TextRects { get; set; } = [];
    }

    private sealed class ReportingTextRect
    {
        public string Id { get; set; } = string.Empty;

        public string Text { get; set; } = string.Empty;

        public double X { get; set; }

        public double Y { get; set; }

        public double Width { get; set; }

        public double Height { get; set; }
    }

    private sealed class F5FixedTextMeasurer : ITextMeasurer
    {
        public TextMeasurement MeasureRun(TextMeasureRequest request)
        {
            var width = request.Text.EnumerateRunes().Sum(rune => char.IsWhiteSpace(rune.ToString(), 0) ? 4d : 7d);
            return new TextMeasurement(
                width + Math.Max(0, request.Text.EnumerateRunes().Count() - 1) * request.LetterSpacing,
                Ascent: request.FontSize * 0.78,
                Descent: request.FontSize * 0.22,
                LineGap: 0,
                LineHeight: request.FontSize * 1.2,
                GlyphCount: request.Text.EnumerateRunes().Count(),
                FallbackGlyphCount: 0,
                MissingGlyphCount: 0);
        }
    }

    private sealed class ReportingHarnessHost : IAsyncDisposable
    {
        private readonly DirectoryInfo _repositoryRoot;
        private readonly HttpListener _listener;
        private readonly CancellationTokenSource _cancellation = new();
        private readonly Task _serverTask;

        private ReportingHarnessHost(DirectoryInfo repositoryRoot, int port)
        {
            _repositoryRoot = repositoryRoot;
            BaseUrl = $"http://127.0.0.1:{port}";
            _listener = new HttpListener();
            _listener.Prefixes.Add($"{BaseUrl}/");
            _listener.Start();
            _serverTask = Task.Run(() => ServeAsync(_cancellation.Token));
        }

        public string BaseUrl { get; }

        public static ReportingHarnessHost Start(DirectoryInfo repositoryRoot)
            => new(repositoryRoot, GetFreePort());

        public async ValueTask DisposeAsync()
        {
            _cancellation.Cancel();
            _listener.Stop();
            try
            {
                await _serverTask;
            }
            catch (HttpListenerException)
            {
            }
            catch (ObjectDisposedException)
            {
            }
            finally
            {
                _listener.Close();
                _cancellation.Dispose();
            }
        }

        private async Task ServeAsync(CancellationToken cancellationToken)
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                var context = await _listener.GetContextAsync();
                _ = Task.Run(() => ServeRequestAsync(context, cancellationToken), cancellationToken);
            }
        }

        private async Task ServeRequestAsync(HttpListenerContext context, CancellationToken cancellationToken)
        {
            try
            {
                var path = ResolvePath(context.Request.Url?.AbsolutePath ?? "/");
                if (path is null || !File.Exists(path))
                {
                    context.Response.StatusCode = 404;
                    context.Response.Close();
                    return;
                }

                var bytes = await File.ReadAllBytesAsync(path, cancellationToken);
                context.Response.ContentType = ContentTypeFor(path);
                context.Response.ContentLength64 = bytes.Length;
                await context.Response.OutputStream.WriteAsync(bytes, cancellationToken);
            }
            finally
            {
                context.Response.Close();
            }
        }

        private string? ResolvePath(string requestPath)
        {
            var decoded = WebUtility.UrlDecode(requestPath).Replace('\\', '/');
            if (decoded == "/")
            {
                decoded = "/reporting-harness.html";
            }

            if (decoded.StartsWith("/_content/Tempo.Blazor/", StringComparison.Ordinal))
            {
                var relative = decoded["/_content/Tempo.Blazor/".Length..];
                return SafeCombine(Path.Combine(_repositoryRoot.FullName, "src", "Tempo.Blazor", "wwwroot"), relative);
            }

            return SafeCombine(Path.Combine(_repositoryRoot.FullName, "src", "Tempo.Blazor.Demo", "wwwroot"), decoded.TrimStart('/'));
        }

        private static string? SafeCombine(string root, string relativePath)
        {
            var fullRoot = Path.GetFullPath(root);
            var fullPath = Path.GetFullPath(Path.Combine(fullRoot, relativePath));
            return fullPath.StartsWith(fullRoot, StringComparison.Ordinal) ? fullPath : null;
        }

        private static string ContentTypeFor(string path)
            => Path.GetExtension(path).ToLowerInvariant() switch
            {
                ".css" => "text/css; charset=utf-8",
                ".html" => "text/html; charset=utf-8",
                ".js" or ".mjs" => "application/javascript; charset=utf-8",
                ".json" => "application/json; charset=utf-8",
                ".png" => "image/png",
                ".svg" => "image/svg+xml",
                _ => "application/octet-stream",
            };

        private static int GetFreePort()
        {
            var listener = new TcpListener(IPAddress.Loopback, 0);
            listener.Start();
            var port = ((IPEndPoint)listener.LocalEndpoint).Port;
            listener.Stop();
            return port;
        }
    }
}
