using FluentAssertions;
using Tempo.Blazor.DocumentFormats.HeadlessLayout;

namespace Tempo.Blazor.DocumentFormats.Tests;

/// <summary>
/// Phase 0 of the headless document runtime: the canvas layout chain (layout snapshot export →
/// display list → pagination → line breaker/paragraph engine/font metrics) ships as a single ESM
/// bundle embedded in Tempo.Blazor.DocumentFormats, so a server-side JS engine can run the SAME
/// layout code the editor paints with. These tests pin the embedded artifact contract the
/// upcoming layout service builds on.
/// </summary>
public class TempoDocumentHeadlessLayoutBundleTests
{
    [Fact]
    public void ReadJavaScript_ReturnsTheEmbeddedEsmBundle()
    {
        var script = TempoDocumentHeadlessLayoutBundle.ReadJavaScript();

        script.Should().NotBeNullOrWhiteSpace();
        script.Should().Contain("Generated by scripts/build-document-editor.mjs",
            "the artifact must be the generated bundle, not a hand-edited file");
    }

    [Fact]
    public void Bundle_ExportsTheHeadlessLayoutChainApi()
    {
        var script = TempoDocumentHeadlessLayoutBundle.ReadJavaScript();

        // The ESM export surface the server-side layout host consumes.
        script.Should().Contain("buildLayoutSnapshotExport");
        script.Should().Contain("translateDisplayListToLayoutSnapshot");
        script.Should().Contain("layoutCanvasDocument");
        script.Should().Contain("buildDisplayList");
        script.Should().Contain("createFontMetricsService");
        script.Should().Contain("collectRedactedRunIds");
    }

    [Fact]
    public void Bundle_DoesNotContainBrowserOnlyEngineModules()
    {
        var script = TempoDocumentHeadlessLayoutBundle.ReadJavaScript();

        // interop.mjs / paint stack markers must never leak into the headless bundle.
        script.Should().NotContain("createCanvasDocumentEngine");
        script.Should().NotContain("ResizeObserver");
        script.Should().NotContain("addEventListener");
    }

    [Fact]
    public void OpenStream_ReturnsAFreshReadableStreamPerCall()
    {
        using var first = TempoDocumentHeadlessLayoutBundle.OpenStream();
        using var second = TempoDocumentHeadlessLayoutBundle.OpenStream();

        first.Should().NotBeSameAs(second);
        first.CanRead.Should().BeTrue();
        first.Length.Should().BeGreaterThan(100_000, "the bundle packages the whole layout chain");
    }
}
