<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tempo.Blazor\Tempo.Blazor.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Codes\Tempo.Blazor.Codes.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Collaboration\Tempo.Blazor.Collaboration.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.DiagramEditor\Tempo.Blazor.DiagramEditor.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.DocumentEditor\Tempo.Blazor.DocumentEditor.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.FluentValidation\Tempo.Blazor.FluentValidation.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Modeling\Tempo.Blazor.Modeling.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.NotionEditor\Tempo.Blazor.NotionEditor.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.PdfViewer\Tempo.Blazor.PdfViewer.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Spreadsheet\Tempo.Blazor.Spreadsheet.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Wireframe\Tempo.Blazor.Wireframe.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Demo.Shared\Tempo.Blazor.Demo.Shared.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.EmailTemplates\Tempo.Blazor.EmailTemplates.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.EmailTemplates.Abstractions\Tempo.Blazor.EmailTemplates.Abstractions.csproj" />
    <ProjectReference Include="..\Tempo.Blazor.Reporting\Tempo.Blazor.Reporting.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.5" />
  </ItemGroup>

</Project>
