using System.Reflection;
using System.Text.Json;
using Microsoft.Extensions.DependencyInjection;
using ModelContextProtocol.Server;
using Tempo.Blazor.Mcp.Reporting;
using Tempo.Reporting.Abstractions.Data;
using Tempo.Reporting.Engine.Fonts;
using Tempo.Reporting.Engine.Pdf;

namespace Tempo.Blazor.Mcp.Tests;

/// <summary>Tests for Tempo Reporting MCP tools and the AI-friendly schema contract.</summary>
public sealed class ReportingToolsTests
{
    private static JsonElement Parse(string json) => JsonDocument.Parse(json).RootElement;

    [Fact]
    public void ReportingToolNames_MatchPhase18Contract()
    {
        var names = TempoReportingMcp.ToolTypes
            .SelectMany(type => type.GetMethods(BindingFlags.Public | BindingFlags.Static))
            .Where(method => method.GetCustomAttribute<McpServerToolAttribute>() is not null)
            .Select(method => method.GetCustomAttribute<McpServerToolAttribute>()!.Name)
            .OrderBy(name => name, StringComparer.Ordinal)
            .ToArray();

        names.Should().Equal(
            "create_report",
            "get_report_definition",
            "list_reports",
            "render_report_preview",
            "update_report_elements",
            "validate_report");
    }

    [Fact]
    public void AddTempoReportingMcpTools_RegistersPreviewFallbackServices()
    {
        var services = new ServiceCollection();
        services.AddTempoReportingMcpTools();

        using var provider = services.BuildServiceProvider();
        provider.GetRequiredService<IReportDataProvider>().Should().BeOfType<ReportingMcpFallbackDataProvider>();
        provider.GetRequiredService<ITextMeasurer>().Should().BeOfType<ReportingMcpTextMeasurer>();
        provider.GetRequiredService<ReportPdfRenderer>().Should().NotBeNull();
    }

    [Fact]
    public void PromptSchema_DocumentsEveryRuntimeReportElementType()
    {
        var documented = ReportDefinitionPromptSchema.ElementTypes
            .Select(item => item.Type)
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();
        var runtime = ReportDefinitionPromptSchema.RuntimeElementDiscriminators()
            .OrderBy(item => item, StringComparer.Ordinal)
            .ToArray();

        documented.Should().Equal(runtime);
        ReportDefinitionPromptSchema.ElementTypes.Should().OnlyContain(item =>
            !string.IsNullOrWhiteSpace(item.Description) &&
            item.Required.Count > 0 &&
            item.Properties.Count > 0);
    }

    [Fact]
    public async Task CreateListGetUpdateValidate_FollowsReportDefinitionStoreContract()
    {
        var store = new InMemoryReportDefinitionStore();
        var created = Parse(await ReportDefinitionTools.CreateReport(store, "Agent Revenue Pack"));
        var reportId = created.GetProperty("reportId").GetString();

        var listed = Parse(await ReportCatalogTools.ListReports(store));
        listed.GetProperty("success").GetBoolean().Should().BeTrue();
        listed.GetProperty("items").EnumerateArray()
            .Select(item => item.GetProperty("reportId").GetString())
            .Should().Contain(reportId);

        var ops = JsonSerializer.Serialize(new object[]
        {
            new
            {
                op = "addElement",
                band = "detail",
                element = new
                {
                    type = "textBox",
                    id = "detail-note",
                    x = 0,
                    y = 0,
                    width = 280,
                    height = 24,
                    text = "Generated by MCP"
                }
            }
        });
        var updated = Parse(await ReportDefinitionTools.UpdateReportElements(store, reportId!, ops));
        updated.GetProperty("success").GetBoolean().Should().BeTrue();
        updated.GetProperty("applied").GetInt32().Should().Be(1);
        updated.GetProperty("createdIds").EnumerateArray().Select(item => item.GetString())
            .Should().Contain("detail-note");

        var loaded = Parse(await ReportDefinitionTools.GetReportDefinition(store, reportId!));
        var definitionJson = loaded.GetProperty("definition").GetRawText();
        loaded.GetProperty("definition").GetProperty("bands").GetProperty("detail")
            .GetProperty("elements").GetArrayLength().Should().Be(1);

        var validation = Parse(ReportValidationTools.ValidateReport(definitionJson, includeSchema: true));
        validation.GetProperty("success").GetBoolean().Should().BeTrue();
        validation.GetProperty("valid").GetBoolean().Should().BeTrue();
        validation.GetProperty("schema").GetProperty("elementTypes").GetArrayLength().Should().BeGreaterThan(0);
    }

    [Fact]
    public async Task AiFriendlyFlow_CreateValidatePreview_ReturnsPng()
    {
        var store = new InMemoryReportDefinitionStore();
        var created = Parse(await ReportDefinitionTools.CreateReport(store, "Preview Smoke"));
        var reportId = created.GetProperty("reportId").GetString();

        var ops = JsonSerializer.Serialize(new object[]
        {
            new { op = "setBandHeight", band = "detail", height = 72 },
            new
            {
                op = "addElement",
                band = "detail",
                element = new
                {
                    type = "shape",
                    id = "accent-box",
                    x = 0,
                    y = 0,
                    width = 180,
                    height = 36,
                    fillColor = "#dbeafe"
                }
            },
            new
            {
                op = "addElement",
                band = "detail",
                element = new
                {
                    type = "textBox",
                    id = "accent-label",
                    x = 12,
                    y = 8,
                    width = 220,
                    height = 20,
                    text = "Preview rendered"
                }
            }
        });
        await ReportDefinitionTools.UpdateReportElements(store, reportId!, ops);
        var loaded = Parse(await ReportDefinitionTools.GetReportDefinition(store, reportId!));
        var valid = Parse(ReportValidationTools.ValidateReport(loaded.GetProperty("definition").GetRawText()));
        valid.GetProperty("valid").GetBoolean().Should().BeTrue();

        var preview = Parse(await ReportPreviewTools.RenderReportPreview(
            store,
            new ReportingMcpFallbackDataProvider(),
            new ReportingMcpTextMeasurer(),
            new ReportPdfRenderer(),
            reportId: reportId));

        preview.GetProperty("success").GetBoolean().Should().BeTrue();
        preview.GetProperty("contentType").GetString().Should().Be("image/png");
        var bytes = Convert.FromBase64String(preview.GetProperty("base64").GetString()!);
        bytes[..8].Should().Equal([0x89, (byte)'P', (byte)'N', (byte)'G', 0x0D, 0x0A, 0x1A, 0x0A]);
    }
}
