using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Tempo.Blazor.Localization;
using Tempo.Blazor.Services;

namespace Tempo.Blazor.Tests.Localization;

/// <summary>
/// Base class for all bUnit component tests.
/// Registers a default English MockTmLocalizer so that @inject ITmLocalizer Loc
/// is always resolved in the test DI container.
/// Tests can override specific keys by calling Services.AddSingleton&lt;ITmLocalizer&gt;(...)
/// AFTER base registration (last registration wins in .NET DI).
/// </summary>
public abstract class LocalizationTestBase : TestContext
{
    protected LocalizationTestBase()
    {
        Services.AddSingleton<ITmLocalizer>(BuildEnglishLocalizer());
        Services.AddScoped<DragDropService>();
        Services.AddSingleton<Tempo.Blazor.Components.Diagram.Stencils.DiagramStencilRegistry>();
        Services.AddSingleton<Tempo.Blazor.Components.Diagram.Templates.DiagramTemplateRegistry>();
        Services.AddHttpClient();
        JSInterop.Mode = JSRuntimeMode.Loose;
    }

    /// <summary>Registers a Czech localizer for this test context.</summary>
    protected void UseCzechLocalization()
    {
        Services.AddSingleton<ITmLocalizer>(BuildCzechLocalizer());
    }

    /// <summary>Registers a custom localizer with the provided key/value pairs.</summary>
    protected void UseCustomLocalization(Dictionary<string, string> keys)
    {
        Services.AddSingleton<ITmLocalizer>(new MockTmLocalizer(keys));
    }

    private static MockTmLocalizer BuildEnglishLocalizer() => new(new Dictionary<string, string>
    {
        // Shared
        ["Tm_Loading"]          = "Loading...",
        ["Tm_Close"]            = "Close",
        ["Tm_Cancel"]           = "Cancel",
        ["Tm_Save"]             = "Save",
        ["Tm_Delete"]           = "Delete",
        ["Tm_Confirm"]          = "Confirm",
        ["Tm_NoResults"]        = "No results found",
        ["Tm_Error"]            = "An error occurred",
        ["Tm_Retry"]            = "Retry",
        ["Tm_Search"]           = "Search",
        ["Tm_Clear"]            = "Clear",
        ["Tm_Select"]           = "Select",
        ["Tm_SelectAll"]        = "Select all",
        ["Tm_DeselectAll"]      = "Deselect all",
        ["Tm_Edit"]             = "Edit",
        ["Tm_Add"]              = "Add",
        ["Tm_Remove"]           = "Remove",
        ["Tm_Apply"]            = "Apply",
        ["Tm_Reset"]            = "Reset",
        ["Tm_Previous"]         = "Previous",
        ["Tm_Next"]             = "Next",
        ["Tm_Download"]         = "Download",
        ["Tm_Upload"]           = "Upload",
        ["Tm_Create"]           = "Create",
        ["Tm_Optional"]         = "Optional",
        ["Tm_Required"]         = "Required",
        ["Tm_Yes"]              = "Yes",
        ["Tm_No"]               = "No",

        // TmButton
        ["TmButton_Loading"] = "Loading",

        // TmSearchInput
        ["TmSearchInput_Placeholder"] = "Search...",
        ["TmSearchInput_Clear"]       = "Clear search",

        // TmEmptyState
        ["TmEmptyState_DefaultTitle"] = "No data available",

        // TmDataTable
        ["TmDataTable_NoResults"]          = "No results found",
        ["TmDataTable_Loading"]            = "Loading data...",
        ["TmDataTable_PageSize"]           = "Items per page",
        ["TmDataTable_Pagination"]         = "{0}–{1} of {2}",
        ["TmDataTable_SelectAll"]          = "Select all rows",
        ["TmDataTable_DeselectAll"]        = "Deselect all rows",
        ["TmDataTable_ColumnPicker"]       = "Choose columns",
        ["TmDataTable_ResetColumns"]       = "Reset to default",
        ["TmDataTable_SaveView"]           = "Save view",
        ["TmDataTable_ManageViews"]        = "Manage views",
        ["TmDataTable_DefaultView"]        = "Default view",
        ["TmDataTable_Filter"]             = "Filter",
        ["TmDataTable_ClearFilters"]       = "Clear filters",
        ["TmDataTable_SortAscending"]      = "Sort ascending",
        ["TmDataTable_SortDescending"]     = "Sort descending",
        ["TmDataTable_BulkActions"]        = "{0} selected",
        ["TmDataTable_DeleteSelected"]     = "Delete selected",
        ["TmDataTable_EditInline"]         = "Edit",
        ["TmDataTable_SaveInline"]         = "Save changes",
        ["TmDataTable_CancelInline"]       = "Cancel edit",
        ["TmDataTable_FirstPage"]          = "First page",
        ["TmDataTable_LastPage"]           = "Last page",
        ["TmDataTable_ViewName"]           = "View name",
        ["TmDataTable_ViewNamePlaceholder"]= "Enter view name...",
        ["TmDataTable_DeleteView"]         = "Delete view",

        // TmFilterableDropdown
        ["TmFilterableDropdown_Search"]        = "Search...",
        ["TmFilterableDropdown_NoResults"]     = "No results found",
        ["TmFilterableDropdown_Loading"]       = "Loading...",
        ["TmFilterableDropdown_Error"]         = "Failed to load options",
        ["TmFilterableDropdown_Retry"]         = "Retry",
        ["TmFilterableDropdown_CreateNew"]     = "Create \"{0}\"",
        ["TmFilterableDropdown_ClearSelection"]= "Clear selection",
        ["TmFilterableDropdown_Placeholder"]   = "Select an option...",

        // TmFileDropZone
        ["TmFileDropZone_DragDrop"]      = "Drag and drop files here",
        ["TmFileDropZone_Or"]            = "or",
        ["TmFileDropZone_Browse"]        = "Browse files",
        ["TmFileDropZone_Uploading"]     = "Uploading...",
        ["TmFileDropZone_Remove"]        = "Remove file",
        ["TmFileDropZone_MaxSize"]       = "Maximum file size: {0}",
        ["TmFileDropZone_AcceptedTypes"] = "Accepted types: {0}",

        // TmTimeline
        ["TmTimeline_NoEntries"]   = "No activity yet",
        ["TmTimeline_Internal"]    = "Internal",
        ["TmTimeline_JustNow"]     = "Just now",
        ["TmTimeline_MinutesAgo"]  = "{0} min ago",
        ["TmTimeline_HoursAgo"]    = "{0} h ago",
        ["TmTimeline_DaysAgo"]     = "{0} days ago",
        ["TmTimeline_DateFormat"]  = "MMM d, yyyy",

        // TmTreeView
        ["TmTreeView_Search"]    = "Search...",
        ["TmTreeView_NoResults"] = "No items found",
        ["TmTreeView_Loading"]   = "Loading...",
        ["TmTreeView_Expand"]    = "Expand",
        ["TmTreeView_Collapse"]  = "Collapse",

        // TmTagPicker
        ["TmTagPicker_Search"]    = "Search tags...",
        ["TmTagPicker_CreateNew"] = "Create \"{0}\"",
        ["TmTagPicker_NoTags"]    = "No tags found",
        ["TmTagPicker_AddTag"]    = "Add tag",

        // TmCommandPalette
        ["TmCommandPalette_Placeholder"] = "Type a command or search...",
        ["TmCommandPalette_NoResults"]   = "No commands found",

        // TmStepper
        ["TmStepper_Step"]      = "Step {0} of {1}",
        ["TmStepper_Completed"] = "Completed",

        // TmAvatar
        ["TmAvatar_ImageAlt"] = "User avatar",

        // TmNotificationBell
        ["TmNotificationBell_AriaLabel"]        = "Notifications",
        ["TmNotificationBell_NewCount"]         = "{0} new notifications",
        ["TmNotificationBell_NoNotifications"]  = "No notifications",
        ["TmNotificationBell_MarkAllRead"]      = "Mark all as read",

        // TmImageGallery
        ["TmImageGallery_PreviousImage"] = "Previous image",
        ["TmImageGallery_NextImage"]     = "Next image",
        ["TmImageGallery_Close"]         = "Close gallery",
        ["TmImageGallery_Counter"]       = "{0} of {1}",
        ["TmImageGallery_LoadingImage"]  = "Loading image...",
        ["TmImageGallery_ErrorLoading"]  = "Failed to load image",
        ["TmImageGallery_ZoomIn"]        = "Zoom in",
        ["TmImageGallery_ZoomOut"]       = "Zoom out",
        ["TmImageGallery_Download"]      = "Download image",
        ["TmImageGallery_Delete"]        = "Delete image",
        ["TmImageGallery_NoImages"]      = "No images available",
        ["TmImageGallery_UploadImages"]  = "Upload images",
        ["TmImageGallery_GridView"]      = "Grid view",
        ["TmImageGallery_GalleryView"]   = "Gallery view",

        // TmLayout
        ["TmSidebar_CollapseMenu"]       = "Collapse menu",
        ["TmSidebar_ExpandMenu"]         = "Expand menu",
        ["TmTopBar_OpenSearch"]          = "Search (Ctrl+K)",
        ["TmTopBar_OpenNotifications"]   = "Open notifications",
        ["TmTopBar_OpenUserMenu"]        = "Open user menu",

        // TmCheckbox
        ["TmCheckbox_Indeterminate"] = "Partially selected",

        // Validation
        ["TmValidation_Required"] = "This field is required",
        ["TmValidation_Invalid"]  = "This field contains an invalid value",

        // TmTimePicker
        ["TmTimePicker_Hours"]              = "Hours",
        ["TmTimePicker_Minutes"]            = "Minutes",
        ["TmTimePicker_Seconds"]            = "Seconds",
        ["TmTimePicker_Placeholder"]        = "HH:mm",
        ["TmTimePicker_PlaceholderSeconds"] = "HH:mm:ss",
        ["TmTimePicker_Clear"]              = "Clear time",

        // TmDatePicker
        ["TmDatePicker_Placeholder"]    = "dd.MM.yyyy",
        ["TmDatePicker_Clear"]          = "Clear date",
        ["TmDatePicker_Today"]          = "Today",
        ["TmDatePicker_PreviousMonth"]  = "Previous month",
        ["TmDatePicker_NextMonth"]      = "Next month",

        // TmDateTimePicker
        ["TmDateTimePicker_Placeholder"] = "dd.MM.yyyy HH:mm",
        ["TmDateTimePicker_Clear"]       = "Clear",

        // TmTimeRangePicker
        ["TmTimeRangePicker_From"]         = "From",
        ["TmTimeRangePicker_To"]           = "To",
        ["TmTimeRangePicker_Duration"]     = "Duration",
        ["TmTimeRangePicker_Swap"]         = "Swap",
        ["TmTimeRangePicker_InvalidRange"] = "End time must be after start time",

        // TmDateRangePicker
        ["TmDateRangePicker_From"]   = "From",
        ["TmDateRangePicker_To"]     = "To",
        ["TmDateRangePicker_Clear"]  = "Clear range",

        // TmDateTimeRangePicker
        ["TmDateTimeRangePicker_StartLabel"]      = "Start",
        ["TmDateTimeRangePicker_EndLabel"]        = "End",
        ["TmDateTimeRangePicker_Clear"]           = "Clear range",
        ["TmDateTimeRangePicker_ValidationError"] = "End must be after start",

        // TmMultiSelect
        ["TmMultiSelect_ConfirmButton"] = "Done",

        // TmMultiSelect
        ["TmMultiSelect_ConfirmButton"] = "Hotovo",

        // TmFilterBuilder operators
        ["TmFilter_Contains"]      = "contains",
        ["TmFilter_NotContains"]   = "does not contain",
        ["TmFilter_Equals"]        = "equals",
        ["TmFilter_NotEquals"]     = "not equals",
        ["TmFilter_GreaterThan"]   = "greater than",
        ["TmFilter_LessThan"]      = "less than",
        ["TmFilter_GreaterOrEqual"]= "greater or equal",
        ["TmFilter_LessOrEqual"]   = "less or equal",
        ["TmFilter_Between"]       = "between",
        ["TmFilter_IsEmpty"]       = "is empty",
        ["TmFilter_IsNotEmpty"]    = "is not empty",
        ["TmFilter_In"]            = "in",
        ["TmFilter_NotIn"]         = "not in",

        // TmMultiViewList
        ["TmMvl_TableView"]   = "Table view",
        ["TmMvl_CardView"]    = "Card view",
        ["TmMvl_ListView"]    = "List view",
        ["TmMvl_ColTitle"]    = "Title",
        ["TmMvl_ColSubTitle"] = "Subtitle",
        ["TmMvl_ColStatus"]   = "Status",
        ["TmMvl_ColDate"]     = "Date",

        // TmValidationSummary
        ["TmValidationSummary_Title"] = "There were errors with your submission",

        // TmPasswordStrengthIndicator
        ["TmPasswordStrength_VeryWeak"]                = "Very weak",
        ["TmPasswordStrength_Weak"]                    = "Weak",
        ["TmPasswordStrength_Medium"]                  = "Medium",
        ["TmPasswordStrength_Strong"]                  = "Strong",
        ["TmPasswordStrength_VeryStrong"]              = "Very strong",
        ["TmPasswordStrength_HintUseAtLeast8Chars"]    = "Use at least 8 characters",
        ["TmPasswordStrength_HintAddLetters"]          = "Add letters",
        ["TmPasswordStrength_HintAddNumbers"]          = "Add numbers",
        ["TmPasswordStrength_HintAddSpecialChars"]     = "Add special characters",
        ["TmPasswordStrength_HintAddUppercase"]        = "Add uppercase letters",
        ["TmPasswordStrength_HintAddLowercase"]        = "Add lowercase letters",
        ["TmPasswordStrength_HintMakeItLonger"]        = "Make it longer",
        ["TmPasswordStrength_HintAvoidCommonPatterns"] = "Avoid common patterns",
        ["TmPasswordStrength_HintAvoidCommonWords"]    = "Avoid common words",
        ["TmPasswordStrength_HintExcellent"]           = "Excellent password!",

        // TmToast
        ["TmToast_Close"] = "Dismiss",

        // TmAlert
        ["TmAlert_Dismiss"] = "Dismiss",

        // TmDrawer
        ["TmDrawer_Close"] = "Close panel",

        // TmBulkActionBar
        ["TmBulkAction_Toolbar"] = "Bulk actions",
        ["TmBulkAction_Selected"] = "selected",
        ["TmBulkAction_ClearSelection"] = "Clear selection",

        // TmDataTable Grouping
        ["TmDataTable_GroupDropPlaceholder"] = "Drag column headers here to group",
        ["TmDataTable_ExpandAll"] = "Expand all",
        ["TmDataTable_CollapseAll"] = "Collapse all",
        ["TmDataTable_GroupCount"] = "{0} items",
        ["TmDataTable_SearchPlaceholder"] = "Search...",
        ["TmDataTable_ShowingItems"] = "{0}–{1} of {2}",
        ["TmDataTable_CurrentViewName"] = "Current",

        // TmMultiViewList Grouping
        ["TmMvl_GroupBy"] = "Group by",
        ["TmMvl_GroupNone"] = "No grouping",

        // TmViewManager Grouping
        ["TmViewManager_Grouping"] = "Grouping",
        ["TmViewManager_GroupByColumns"] = "Group by columns",

        // TmInlineEdit
        ["TmInlineEdit_Placeholder"] = "Click to edit",

        // TmRichEditor - Tokens
        ["TmRichEditor_Token"]          = "Insert variable",
        ["TmRichEditor_TokenEmpty"]     = "No variables found",
        ["TmRichEditor_TokenCreateNew"] = "Create new variable...",
        ["TmRichEditor_TokenSearch"]    = "Search variables...",
        ["TmRichEditor_MentionEmpty"]   = "No users found",
        ["TmRichEditor_Bold"]           = "Bold",
        ["TmRichEditor_Italic"]         = "Italic",
        ["TmRichEditor_Underline"]      = "Underline",
        ["TmRichEditor_Link"]           = "Link",
        ["TmRichEditor_TaskList"]       = "Task list",
        ["TmRichEditor_Emoji"]          = "Emoji",
        ["TmRichEditor_UnorderedList"]  = "Bullet list",
        ["TmRichEditor_OrderedList"]    = "Numbered list",
        ["TmRichEditor_Undo"]          = "Undo",
        ["TmRichEditor_Redo"]          = "Redo",
        ["TmRichEditor_Heading1"]      = "Heading 1",
        ["TmRichEditor_Heading2"]      = "Heading 2",
        ["TmRichEditor_Heading3"]      = "Heading 3",
        ["TmRichEditor_Heading4"]      = "Heading 4",
        ["TmRichEditor_Strikethrough"] = "Strikethrough",
        ["TmRichEditor_Subscript"]     = "Subscript",
        ["TmRichEditor_Superscript"]   = "Superscript",
        ["TmRichEditor_Indent"]        = "Indent",
        ["TmRichEditor_Outdent"]       = "Outdent",
        ["TmRichEditor_Code"]          = "Code block",
        ["TmRichEditor_Blockquote"]    = "Blockquote",
        ["TmRichEditor_HorizontalRule"]= "Horizontal line",
        ["TmRichEditor_TextColor"]     = "Text color",
        ["TmRichEditor_Highlight"]     = "Highlight",
        ["TmRichEditor_Image"]         = "Image",
        ["TmRichEditor_Table"]         = "Table",
        ["TmRichEditor_Video"]         = "Video",
        ["TmRichEditor_RemoveFormat"]  = "Remove formatting",

        // TmDashboard
        ["TmDashboard_Edit"]                  = "Edit",
        ["TmDashboard_EditMode"]              = "Edit Mode",
        ["TmDashboard_CancelEdit"]            = "Cancel",
        ["TmDashboard_SaveChanges"]           = "Save Changes",
        ["TmDashboard_AddWidget"]             = "Add Widget",
        ["TmDashboard_AddWidgets"]            = "Add Widgets",
        ["TmDashboard_Dashboards"]            = "Dashboards",
        ["TmDashboard_MyDashboards"]          = "My Dashboards",
        ["TmDashboard_CreateNewDashboard"]    = "Create New Dashboard",
        ["TmDashboard_DashboardName"]         = "Dashboard Name",
        ["TmDashboard_DefaultDashboard"]      = "Default",
        ["TmDashboard_SetAsDefault"]          = "Set as Default",
        ["TmDashboard_Delete"]                = "Delete",
        ["TmDashboard_DeleteDashboard"]       = "Delete Dashboard",
        ["TmDashboard_DeleteDashboardConfirm"]= "Are you sure you want to delete this dashboard?",
        ["TmDashboard_NoWidgets"]             = "No widgets added yet",

        // TmDiagramEditor
        ["TmDiagramEditor_ToolbarAriaLabel"] = "Diagram editor toolbar",
        ["TmDiagramEditor_UntitledPlaceholder"] = "Untitled diagram",
        ["TmDiagramEditor_DocumentTitleLabel"] = "Document title",
        ["TmDiagramEditor_SelectTool"] = "Select tool (V)",
        ["TmDiagramEditor_PanTool"] = "Pan tool (H)",
        ["TmDiagramEditor_PanToolHint"] = "Pan tool (H) — or hold Space",
        ["TmDiagramEditor_EdgeTool"] = "Edge tool (L)",
        ["TmDiagramEditor_EdgeToolHint"] = "Edge tool (L / C) — click a node, drag for a single line, or click-click-... for a polyline (finish with double-click / Enter)",
        ["TmDiagramEditor_Undo"] = "Undo",
        ["TmDiagramEditor_Redo"] = "Redo",
        ["TmDiagramEditor_ZoomOut"] = "Zoom out",
        ["TmDiagramEditor_ZoomIn"] = "Zoom in",
        ["TmDiagramEditor_FitToView"] = "Fit to view",
        ["TmDiagramEditor_ToggleRulers"] = "Toggle rulers",
        ["TmDiagramEditor_RulerUnitLabel"] = "Ruler unit",
        ["TmDiagramEditor_CanvasWidth"] = "Canvas width",
        ["TmDiagramEditor_CanvasHeight"] = "Canvas height",
        ["TmDiagramEditor_Apply"] = "Apply",
        ["TmDiagramEditor_Cancel"] = "Cancel",
        ["TmDiagramEditor_ChangeCanvasSize"] = "Change canvas size",
        ["TmDiagramEditor_Export"] = "Export",
        ["TmDiagramEditor_ExportJson"] = "Export JSON",
        ["TmDiagramEditor_ExportSvg"] = "Export SVG",
        ["TmDiagramEditor_ExportPng"] = "Export PNG",
        ["TmDiagramEditor_ExportPdf"] = "Export PDF",
        ["TmDiagramEditor_ImportJson"] = "Import JSON",
        ["TmDiagramEditor_ImportSql"] = "Import SQL → ER",
        ["TmDiagramEditor_VirtualBend"] = "Virtual bend",
        ["TmDiagramSqlImportDialog_Title"] = "Import SQL to ER Diagram",
        ["TmDiagramSqlImportDialog_SqlLabel"] = "SQL DDL",
        ["TmDiagramSqlImportDialog_SqlPlaceholder"] = "Paste CREATE TABLE statements here...",
        ["TmDiagramSqlImportDialog_LayoutLabel"] = "Layout direction",
        ["TmDiagramSqlImportDialog_PreviewTables"] = "Tables: {0}",
        ["TmDiagramSqlImportDialog_PreviewRelations"] = "Relations: {0}",
        ["TmDiagramSqlImportDialog_ImportButton"] = "Import",
        ["TmDiagramSqlImportDialog_ErrorEmpty"] = "Please enter SQL DDL.",
        ["TmDiagramSqlImportDialog_ErrorNoTables"] = "No tables found in the provided SQL.",
        ["TmDiagramSqlImportDialog_ErrorParse"] = "Failed to parse SQL: {0}",
        ["TmDiagramEditor_SwitchToEditMode"] = "Switch to edit mode",
        ["TmDiagramEditor_SwitchToReadOnlyMode"] = "Switch to read-only mode",
        ["TmDiagramEditor_ReadOnly"] = "Read-only",
        ["TmDiagramEditor_Edit"] = "Edit",
        ["TmDiagramEditor_ShowToolbox"] = "Show toolbox",
        ["TmDiagramEditor_HideToolbox"] = "Hide toolbox",
        ["TmDiagramEditor_ToggleToolbox"] = "Toggle toolbox",
        ["TmDiagramEditor_ShowProperties"] = "Show properties panel",
        ["TmDiagramEditor_HideProperties"] = "Hide properties panel",
        ["TmDiagramEditor_ToggleProperties"] = "Toggle properties panel",
        ["TmDiagramEditor_ShowLayers"] = "Show layers",
        ["TmDiagramEditor_HideLayers"] = "Hide layers",
        ["TmDiagramEditor_ToggleLayers"] = "Toggle layers",
        ["TmDiagramEditor_ShowMinimap"] = "Show minimap",
        ["TmDiagramEditor_HideMinimap"] = "Hide minimap",
        ["TmDiagramEditor_ToggleMinimap"] = "Toggle minimap",
        ["TmDiagramEditor_DismissError"] = "Dismiss error",
        ["TmDiagramEditor_ImportError_InvalidJson"] = "Failed to import: the file is not a valid diagram JSON.",
        ["TmDiagramEditor_ImportError_Generic"] = "Failed to import: {0}.",
        ["TmDiagramEditor_ExportError"] = "Export failed: {0}.",
        ["TmDiagramEditor_BringToFront"] = "Bring to front",
        ["TmDiagramEditor_SendToBack"] = "Send to back",
        ["TmDiagramEditor_Delete"] = "Delete",
        ["TmDiagramEditor_Cut"] = "Cut",
        ["TmDiagramEditor_Copy"] = "Copy",
        ["TmDiagramEditor_Duplicate"] = "Duplicate",
        ["TmDiagramEditor_Paste"] = "Paste",
        ["TmDiagramEditor_PasteHere"] = "Paste Here",
        ["TmDiagramEditor_SelectAll"] = "Select All",
        ["TmDiagramEditor_Lock"] = "Lock",
        ["TmDiagramEditor_Unlock"] = "Unlock",
        ["TmDiagramEditor_Group"] = "Group",
        ["TmDiagramEditor_Ungroup"] = "Ungroup",
        ["TmDiagramEditor_PasteStyle"] = "Paste Style",
        ["TmDiagramEditor_PasteSize"] = "Paste Size",
        ["TmDiagramEditor_ChangeShape"] = "Change Shape",
        ["TmDiagramEditor_Rectangle"] = "Rectangle",
        ["TmDiagramEditor_Ellipse"] = "Ellipse",
        ["TmDiagramEditor_Text"] = "Text",
        ["TmDiagramEditor_Diamond"] = "Diamond",
        ["TmDiagramEditor_EditLabel"] = "Edit Label",
        ["TmDiagramEditor_Connector"] = "Connector",
        ["TmDiagramEditor_Straight"] = "Straight",
        ["TmDiagramEditor_Orthogonal"] = "Orthogonal",
        ["TmDiagramEditor_Curved"] = "Curved",
        ["TmDiagramEditor_StartArrow"] = "Start Arrow",
        ["TmDiagramEditor_EndArrow"] = "End Arrow",
        ["TmDiagramEditor_ArrowNone"] = "None",
        ["TmDiagramEditor_ArrowClassic"] = "Classic",
        ["TmDiagramEditor_ArrowBlock"] = "Block",
        ["TmDiagramEditor_ArrowCrow"] = "Crow",
        ["TmDiagramEditor_LineStyle"] = "Line Style",
        ["TmDiagramEditor_LineSolid"] = "Solid",
        ["TmDiagramEditor_LineDashed"] = "Dashed",
        ["TmDiagramEditor_LineDotted"] = "Dotted",
        ["TmDiagramEditor_Insert"] = "Insert",
        ["TmDiagramEditor_InsertTable"] = "Table",
        ["TmDiagramEditor_InsertText"] = "Text",
        ["TmDiagramEditor_InsertGroup"] = "Group",
        ["TmDiagramTableInserter_Title"] = "Insert table",
        ["TmDiagramEditor_Layout"] = "Layout",
        ["TmDiagramEditor_LayoutDagreTb"] = "Dagre Top-Bottom",
        ["TmDiagramEditor_LayoutDagreLr"] = "Dagre Left-Right",
        ["TmDiagramEditor_LayoutTree"] = "Tree",
        ["TmDiagramEditor_LayoutForce"] = "Force",
        ["TmDiagramEditor_LayoutCircle"] = "Circle",
        ["TmDiagramEditor_ShowGrid"] = "Show Grid",
        ["TmDiagramEditor_HideGrid"] = "Hide Grid",
        ["TmDiagramEditor_ShowPageView"] = "Show Page View",
        ["TmDiagramEditor_HidePageView"] = "Hide Page View",
        ["TmDiagramEditor_EnableSnap"] = "Enable Snap to Grid",
        ["TmDiagramEditor_DisableSnap"] = "Disable Snap to Grid",
        ["TmDiagramEditor_MergeCells"] = "Merge Cells",
        ["TmDiagramEditor_SplitCell"] = "Split Cell",
        ["TmDiagramEditor_FormatCell"] = "Format Cell",
        ["TmDiagramEditor_CellWhite"] = "White",
        ["TmDiagramEditor_CellLightGray"] = "Light Gray",
        ["TmDiagramEditor_CellGray"] = "Gray",
        ["TmDiagramEditor_ImportCsv"] = "Import CSV",
        ["TmDiagramEditor_Templates"] = "Templates",
        ["TmDiagramTemplateGallery_Title"] = "Choose a Template",
        ["TmDiagramTemplateGallery_SearchPlaceholder"] = "Search templates...",
        ["TmDiagramTemplateGallery_All"] = "All",
        ["TmDiagramTemplateGallery_NoResults"] = "No templates match your search.",
        ["TmDiagramTemplateGallery_CreateButton"] = "Create",
        ["TmDiagramCsvImportDialog_Title"] = "Import CSV to Diagram",
        ["TmDiagramCsvImportDialog_CsvLabel"] = "CSV Data",
        ["TmDiagramCsvImportDialog_CsvPlaceholder"] = "Paste CSV data here...",
        ["TmDiagramCsvImportDialog_TypeLabel"] = "Diagram type",
        ["TmDiagramCsvImportDialog_MappingsTitle"] = "Column mapping",
        ["TmDiagramCsvImportDialog_SelectColumn"] = "Select column",
        ["TmDiagramCsvImportDialog_PreviewTitle"] = "Preview (first 5 rows)",
        ["TmDiagramCsvImportDialog_PreviewNodes"] = "Nodes: {0}",
        ["TmDiagramCsvImportDialog_PreviewEdges"] = "Edges: {0}",
        ["TmDiagramCsvImportDialog_ImportButton"] = "Import",
        ["TmDiagramCsvImportDialog_ErrorEmpty"] = "Please enter CSV data.",
        ["TmDiagramCsvImportDialog_ErrorNoData"] = "No data rows found in the provided CSV.",
        ["TmDiagramCsvImportDialog_ErrorMinColumns"] = "CSV must contain at least 2 columns.",
        ["TmDiagramCsvImportDialog_ErrorMappings"] = "Please map all required columns.",
        ["TmDiagramCsvImportDialog_ErrorParse"] = "Failed to parse CSV: {0}",
        ["TmDiagramMinimap_Title"] = "Minimap",
        ["TmDiagramMinimap_Empty"] = "No diagram to show",
        ["TmDiagramLayers_Title"] = "Layers",
        ["TmDiagramLayers_AddLayer"] = "Add layer",
        ["TmDiagramLayers_Show"] = "Show",
        ["TmDiagramLayers_Hide"] = "Hide",
        ["TmDiagramLayers_Lock"] = "Lock",
        ["TmDiagramLayers_Unlock"] = "Unlock",
        ["TmDiagramLayers_DefaultLayer"] = "Default Layer",
        ["TmDiagramLayers_DeleteLayer"] = "Delete layer",
        ["TmDiagramLayers_AssignToLayer"] = "Assign to layer",
        ["TmDiagramLayers_Layer"] = "Layer",
        ["TmDiagramProperties_Layer"] = "Layer",
        ["TmDiagramProperties_Title"] = "Properties",
        ["TmDiagramProperties_NodeTitle"] = "Node",
        ["TmDiagramProperties_EdgeTitle"] = "Edge",
        ["TmDiagramProperties_Label"] = "Label",
        ["TmDiagramProperties_LabelOffsetX"] = "Label Offset X",
        ["TmDiagramProperties_LabelOffsetY"] = "Label Offset Y",
        ["TmDiagramProperties_ArcSize"] = "Corner Radius",
        ["TmDiagramProperties_Style"] = "Style",
        ["TmDiagramProperties_ZIndex"] = "Z-Index",
        ["TmDiagramProperties_Empty"] = "Nothing selected",
        ["TmDiagramProperties_ReadOnly"] = "Read-only mode",
        ["TmDiagramProperties_Routing"] = "Routing",
        ["TmDiagramProperties_Routing_Straight"] = "Straight",
        ["TmDiagramProperties_Routing_Orthogonal"] = "Orthogonal",
        ["TmDiagramProperties_Routing_Curved"] = "Curved",
        ["TmDiagramProperties_Routing_Isometric"] = "Isometric",
        ["TmDiagramProperties_Routing_EntityRelation"] = "Entity Relation",
        ["TmDiagramProperties_CubicBezier"] = "Cubic Bézier",
        ["TmDiagramProperties_ConnectorType"] = "Connector type",
        ["TmDiagramProperties_ConnectorType_Association"] = "Association",
        ["TmDiagramProperties_ConnectorType_Dependency"] = "Dependency",
        ["TmDiagramProperties_ConnectorType_Inheritance"] = "Inheritance",
        ["TmDiagramProperties_ConnectorType_Composition"] = "Composition",
        ["TmDiagramProperties_ConnectorType_Aggregation"] = "Aggregation",
        ["TmDiagramProperties_EdgePreset"] = "Preset",
        ["TmDiagramProperties_Preset_Custom"] = "Custom",
        ["TmDiagramProperties_Preset_ArrowRight"] = "→ Arrow",
        ["TmDiagramProperties_Preset_Line"] = "─ Line",
        ["TmDiagramProperties_Preset_DoubleArrow"] = "⇒ Double Arrow",
        ["TmDiagramProperties_Preset_CrossArrow"] = "⊣→ Cross Arrow",
        ["TmDiagramProperties_Preset_DoubleLine"] = "═ Double Line",
        ["TmDiagramProperties_Preset_ThickDoubleLine"] = "══ Thick Double",
        ["TmDiagramProperties_Preset_Dashed"] = "- - Dashed",
        ["TmDiagramProperties_EdgeShape"] = "Connection",
        ["TmDiagramProperties_EdgeShape_Connector"] = "Connector",
        ["TmDiagramProperties_EdgeShape_Link"] = "Double Line",
        ["TmDiagramProperties_EdgeShape_FilledEdge"] = "Filled Bar",
        ["TmDiagramProperties_EdgeShape_Pipe"] = "Pipe",
        ["TmDiagramProperties_EdgeShape_Wire"] = "Wire",
        ["TmDiagramProperties_FillArrow"] = "Fill",
        ["TmDiagram_EnableMathJax"] = "MathJax",
        ["TmDiagramProperties_Link"] = "Link",
        ["TmDiagramProperties_LinkPlaceholder"] = "https://...",
        ["TmDiagramProperties_LinkType_None"] = "None",
        ["TmDiagramProperties_ExternalUrl"] = "External URL",
        ["TmDiagramProperties_PageLink"] = "Page Link",
        ["TmDiagramProperties_Scale"] = "Scale",
        ["TmDiagramProperties_PlaceholdersHint"] = "Placeholders: %page%, %pagenumber%, %totalpages%, %date%",
        ["TmDiagramCanvas_AriaLabel"] = "Diagram canvas",
        ["TmDiagram_SearchPlaceholder"] = "Search diagram...",
        ["TmDiagram_SearchResults"] = "{0} of {1}",
        ["TmDiagram_SearchNoResults"] = "No results",
        ["TmDiagram_SearchPrevious"] = "Previous result",
        ["TmDiagram_SearchNext"] = "Next result",
        ["TmDiagram_SearchClose"] = "Close search",
        ["TmDiagram_SearchAllPages"] = "All pages",
        ["TmDiagram_ReplacePlaceholder"] = "Replace with...",
        ["TmDiagram_Replace"] = "Replace",
        ["TmDiagram_ReplaceAll"] = "Replace All",
        ["TmDiagram_UseRegex"] = "Use regular expressions",
        ["TmDiagram_RegexError"] = "Invalid regex: {0}",
        ["TmDiagram_ReplaceNoMatches"] = "No replaceable matches",
        ["TmDiagramEditor_RotateHandleLabel"] = "Rotate",
        ["TmDiagramEditor_ConnectArrowTop"] = "Connect top",
        ["TmDiagramEditor_ConnectArrowRight"] = "Connect right",
        ["TmDiagramEditor_ConnectArrowBottom"] = "Connect bottom",
        ["TmDiagramEditor_ConnectArrowLeft"] = "Connect left",
        ["TmDiagramEditor_SelectStencilTitle"] = "Select shape to connect",
        ["TmDiagramEditor_AddPage"] = "Add page",
        ["TmDiagramEditor_ClosePage"] = "Close page \"{0}\"",
        ["TmDiagramEditor_PageName"] = "Page",
        ["TmDiagramEditor_DuplicatePage"] = "Duplicate page",
        ["TmDiagramEditor_CopySuffix"] = "copy",

        ["TmDiagramEditor_ToggleRulers"] = "Přepnout pravítka",
        ["TmDiagramEditor_RulerUnitLabel"] = "Jednotka pravítka",

        // TmWireframe
        ["TmWireframe_ToolbarAriaLabel"] = "Wireframe editor toolbar",
        ["TmWireframe_UntitledPlaceholder"] = "Untitled wireframe",
        ["TmWireframe_DocumentTitleLabel"] = "Document title",
        ["TmWireframe_SelectTool"] = "Select tool (V)",
        ["TmWireframe_PanTool"] = "Pan tool (H)",
        ["TmWireframe_PanToolHint"] = "Pan tool (H) — or hold Space",
        ["TmWireframe_Undo"] = "Undo",
        ["TmWireframe_Redo"] = "Redo",
        ["TmWireframe_ZoomOut"] = "Zoom out",
        ["TmWireframe_ZoomIn"] = "Zoom in",
        ["TmWireframe_FitToView"] = "Fit to view",
        ["TmWireframe_CanvasWidth"] = "Canvas width",
        ["TmWireframe_CanvasHeight"] = "Canvas height",
        ["TmWireframe_Apply"] = "Apply",
        ["TmWireframe_Cancel"] = "Cancel",
        ["TmWireframe_ChangeCanvasSize"] = "Change canvas size",
        ["TmWireframe_Export"] = "Export",
        ["TmWireframe_ExportJson"] = "Export JSON",
        ["TmWireframe_ExportSvg"] = "Export SVG",
        ["TmWireframe_ExportPng"] = "Export PNG",
        ["TmWireframe_ExportPdf"] = "Export PDF",
        ["TmWireframe_ExportError"] = "Export failed: {0}.",
        ["TmWireframeExportDialog_Title"] = "Export Wireframe",
        ["TmWireframeExportDialog_FileName"] = "File name",
        ["TmWireframeExportDialog_FileNamePlaceholder"] = "wireframe",
        ["TmWireframeExportDialog_Format"] = "Format",
        ["TmWireframeExportDialog_Scale"] = "Scale",
        ["TmWireframeExportDialog_IncludeBackground"] = "Include background",
        ["TmWireframeExportDialog_ExportButton"] = "Export",
        ["TmWireframe_ImportJson"] = "Import JSON",
        ["TmWireframe_SwitchToEditMode"] = "Switch to edit mode",
        ["TmWireframe_SwitchToReadOnlyMode"] = "Switch to read-only mode",
        ["TmWireframe_ReadOnly"] = "Read-only",
        ["TmWireframe_Edit"] = "Edit",
        ["TmWireframe_ShowToolbox"] = "Show toolbox",
        ["TmWireframe_HideToolbox"] = "Hide toolbox",
        ["TmWireframe_ToggleToolbox"] = "Toggle toolbox",
        ["TmWireframe_ShowProperties"] = "Show properties panel",
        ["TmWireframe_HideProperties"] = "Hide properties panel",
        ["TmWireframe_ToggleProperties"] = "Toggle properties panel",
        ["TmWireframe_DismissError"] = "Dismiss error",
        ["TmWireframe_DefaultTitle"] = "Untitled wireframe",
        ["TmWireframe_ExportFilename"] = "wireframe",
        ["TmWireframe_ImportError_InvalidJson"] = "Failed to import: the file is not a valid wireframe JSON.",
        ["TmWireframe_ImportError_Generic"] = "Failed to import: {0}.",
        ["TmWireframeToolbox_SearchPlaceholder"] = "Search components…",
        ["TmWireframeToolbox_ClearSearch"] = "Clear search",
        ["TmWireframeToolbox_FilterAll"] = "All",
        ["TmWireframeToolbox_FilterBuiltIn"] = "Built-in",
        ["TmWireframeToolbox_FilterCustom"] = "Custom",
        ["TmWireframeToolbox_NoComponentsMatch"] = "No components match \"{0}\"",
        ["TmWireframeToolbox_CustomComponentTooltip"] = "Custom component",
        ["TmWireframeToolbox_DragOntoCanvas"] = "Drag {0} onto canvas",
        ["TmWireframeProps_NoSelectionTitle"] = "No selection",
        ["TmWireframeProps_NoSelectionHint"] = "Select an element on the canvas to edit its properties.",
        ["TmWireframeProps_ElementsCount"] = "{0} elements",
        ["TmWireframeProps_MixedTypes"] = "Mixed types",
        ["TmWireframeProps_SectionElement"] = "Element",
        ["TmWireframeProps_SectionLayout"] = "Layout",
        ["TmWireframeProps_SectionGeneral"] = "General",
        ["TmWireframeProps_Type"] = "Type",
        ["TmWireframeProps_Types"] = "Types",
        ["TmWireframeProps_ZIndex"] = "Z-Index",
        ["TmWireframeProps_X"] = "X",
        ["TmWireframeProps_Y"] = "Y",
        ["TmWireframeProps_W"] = "W",
        ["TmWireframeProps_H"] = "H",
        ["TmWireframeProps_MixedPlaceholder"] = "Mixed",
        ["TmWireframeProps_CommaSeparatedPlaceholder"] = "comma, separated",
        ["TmWireframeProps_ValidationRegexError"] = "Value does not match pattern: {0}",
        ["TmWireframeProps_CommandChangeZIndex"] = "Change Z-Index",
        ["TmWireframeCanvas_AriaLabel"] = "Wireframe canvas",
        ["TmWireframeCanvas_UnknownComponent"] = "Unknown: {0}",
        ["TmWireframeProps_CatContent"] = "Content",
        ["TmWireframeProps_CatAppearance"] = "Appearance",
        ["TmWireframeProps_CatBehavior"] = "Behavior",
        ["TmWireframeProps_CatState"] = "State",

        ["TmWireframe_LayersToggle"] = "Toggle layers panel",
        ["TmWireframe_LayersTitle"] = "Layers",
        ["TmWireframe_AddLayer"] = "Add layer",
        ["TmWireframe_SetActiveLayer"] = "Set as active layer",
        ["TmWireframe_HideLayer"] = "Hide layer",
        ["TmWireframe_ShowLayer"] = "Show layer",
        ["TmWireframe_UnlockLayer"] = "Unlock layer",
        ["TmWireframe_LockLayer"] = "Lock layer",
        ["TmWireframe_DoubleClickToEdit"] = "Double-click to edit name",
        ["TmWireframe_DeleteLayer"] = "Delete layer",
        ["TmWireframe_MoveToLayer"] = "Move to layer",
        ["TmWireframe_SelectLayer"] = "Select layer",
        ["TmWireframe_Layer"] = "Layer",
        ["TmWireframeProps_Layer"] = "Layer",
        ["TmWireframe_ShowRulers"] = "Show rulers",
        ["TmWireframe_HorizontalRuler"] = "Horizontal ruler",
        ["TmWireframe_VerticalRuler"] = "Vertical ruler",
    });

    private static MockTmLocalizer BuildCzechLocalizer() => new(new Dictionary<string, string>
    {
        // Shared
        ["Tm_Loading"]     = "Načítání...",
        ["Tm_Close"]       = "Zavřít",
        ["Tm_Cancel"]      = "Zrušit",
        ["Tm_Save"]        = "Uložit",
        ["Tm_Delete"]      = "Smazat",
        ["Tm_Confirm"]     = "Potvrdit",
        ["Tm_NoResults"]   = "Žádné výsledky",
        ["Tm_Error"]       = "Došlo k chybě",
        ["Tm_Retry"]       = "Zkusit znovu",
        ["Tm_Search"]      = "Hledat",
        ["Tm_Clear"]       = "Vymazat",
        ["Tm_Select"]      = "Vybrat",
        ["Tm_SelectAll"]   = "Vybrat vše",
        ["Tm_DeselectAll"] = "Zrušit výběr",
        ["Tm_Edit"]        = "Upravit",
        ["Tm_Add"]         = "Přidat",
        ["Tm_Remove"]      = "Odebrat",
        ["Tm_Apply"]       = "Použít",
        ["Tm_Reset"]       = "Obnovit",
        ["Tm_Previous"]    = "Předchozí",
        ["Tm_Next"]        = "Další",
        ["Tm_Download"]    = "Stáhnout",
        ["Tm_Upload"]      = "Nahrát",
        ["Tm_Create"]      = "Vytvořit",
        ["Tm_Optional"]    = "Volitelné",
        ["Tm_Required"]    = "Povinné",
        ["Tm_Yes"]         = "Ano",
        ["Tm_No"]          = "Ne",

        // TmButton
        ["TmButton_Loading"] = "Načítání",

        // TmSearchInput
        ["TmSearchInput_Placeholder"] = "Hledat...",
        ["TmSearchInput_Clear"]       = "Vymazat hledání",

        // TmEmptyState
        ["TmEmptyState_DefaultTitle"] = "Žádná data",

        // TmDataTable
        ["TmDataTable_NoResults"]          = "Žádné výsledky",
        ["TmDataTable_Loading"]            = "Načítání dat...",
        ["TmDataTable_PageSize"]           = "Položek na stránku",
        ["TmDataTable_Pagination"]         = "{0}–{1} z {2}",
        ["TmDataTable_SelectAll"]          = "Vybrat všechny řádky",
        ["TmDataTable_DeselectAll"]        = "Zrušit výběr",
        ["TmDataTable_ColumnPicker"]       = "Vybrat sloupce",
        ["TmDataTable_ResetColumns"]       = "Obnovit výchozí",
        ["TmDataTable_SaveView"]           = "Uložit pohled",
        ["TmDataTable_ManageViews"]        = "Spravovat pohledy",
        ["TmDataTable_DefaultView"]        = "Výchozí pohled",
        ["TmDataTable_Filter"]             = "Filtr",
        ["TmDataTable_ClearFilters"]       = "Zrušit filtry",
        ["TmDataTable_SortAscending"]      = "Řadit vzestupně",
        ["TmDataTable_SortDescending"]     = "Řadit sestupně",
        ["TmDataTable_BulkActions"]        = "{0} vybráno",
        ["TmDataTable_DeleteSelected"]     = "Smazat vybrané",
        ["TmDataTable_EditInline"]         = "Upravit",
        ["TmDataTable_SaveInline"]         = "Uložit změny",
        ["TmDataTable_CancelInline"]       = "Zrušit úpravy",
        ["TmDataTable_FirstPage"]          = "První stránka",
        ["TmDataTable_LastPage"]           = "Poslední stránka",
        ["TmDataTable_ViewName"]           = "Název pohledu",
        ["TmDataTable_ViewNamePlaceholder"]= "Zadejte název pohledu...",
        ["TmDataTable_DeleteView"]         = "Smazat pohled",

        // TmFilterableDropdown
        ["TmFilterableDropdown_Search"]        = "Hledat...",
        ["TmFilterableDropdown_NoResults"]     = "Žádné výsledky",
        ["TmFilterableDropdown_Loading"]       = "Načítání...",
        ["TmFilterableDropdown_Error"]         = "Nepodařilo se načíst možnosti",
        ["TmFilterableDropdown_Retry"]         = "Zkusit znovu",
        ["TmFilterableDropdown_CreateNew"]     = "Vytvořit \"{0}\"",
        ["TmFilterableDropdown_ClearSelection"]= "Zrušit výběr",
        ["TmFilterableDropdown_Placeholder"]   = "Vyberte možnost...",

        // TmFileDropZone
        ["TmFileDropZone_DragDrop"]      = "Přetáhněte soubory sem",
        ["TmFileDropZone_Or"]            = "nebo",
        ["TmFileDropZone_Browse"]        = "Vybrat soubory",
        ["TmFileDropZone_Uploading"]     = "Nahrávání...",
        ["TmFileDropZone_Remove"]        = "Odebrat soubor",
        ["TmFileDropZone_MaxSize"]       = "Maximální velikost: {0}",
        ["TmFileDropZone_AcceptedTypes"] = "Povolené typy: {0}",

        // TmTimeline
        ["TmTimeline_NoEntries"]  = "Žádná aktivita",
        ["TmTimeline_Internal"]   = "Interní",
        ["TmTimeline_JustNow"]    = "Právě teď",
        ["TmTimeline_MinutesAgo"] = "před {0} min",
        ["TmTimeline_HoursAgo"]   = "před {0} h",
        ["TmTimeline_DaysAgo"]    = "před {0} dny",
        ["TmTimeline_DateFormat"] = "d. M. yyyy",

        // TmTreeView
        ["TmTreeView_Search"]    = "Hledat...",
        ["TmTreeView_NoResults"] = "Žádné položky",
        ["TmTreeView_Loading"]   = "Načítání...",
        ["TmTreeView_Expand"]    = "Rozbalit",
        ["TmTreeView_Collapse"]  = "Sbalit",

        // TmTagPicker
        ["TmTagPicker_Search"]    = "Hledat štítky...",
        ["TmTagPicker_CreateNew"] = "Vytvořit \"{0}\"",
        ["TmTagPicker_NoTags"]    = "Žádné štítky",
        ["TmTagPicker_AddTag"]    = "Přidat štítek",

        // TmCommandPalette
        ["TmCommandPalette_Placeholder"] = "Zadejte příkaz nebo hledejte...",
        ["TmCommandPalette_NoResults"]   = "Žádné příkazy nenalezeny",

        // TmStepper
        ["TmStepper_Step"]      = "Krok {0} z {1}",
        ["TmStepper_Completed"] = "Dokončeno",

        // TmAvatar
        ["TmAvatar_ImageAlt"] = "Avatar uživatele",

        // TmNotificationBell
        ["TmNotificationBell_AriaLabel"]       = "Oznámení",
        ["TmNotificationBell_NewCount"]        = "{0} nových oznámení",
        ["TmNotificationBell_NoNotifications"] = "Žádná oznámení",
        ["TmNotificationBell_MarkAllRead"]     = "Označit vše jako přečtené",

        // TmImageGallery
        ["TmImageGallery_PreviousImage"] = "Předchozí obrázek",
        ["TmImageGallery_NextImage"]     = "Další obrázek",
        ["TmImageGallery_Close"]         = "Zavřít galerii",
        ["TmImageGallery_Counter"]       = "{0} z {1}",
        ["TmImageGallery_LoadingImage"]  = "Načítání obrázku...",
        ["TmImageGallery_ErrorLoading"]  = "Obrázek se nepodařilo načíst",
        ["TmImageGallery_ZoomIn"]        = "Přiblížit",
        ["TmImageGallery_ZoomOut"]       = "Oddálit",
        ["TmImageGallery_Download"]      = "Stáhnout obrázek",
        ["TmImageGallery_Delete"]        = "Smazat obrázek",
        ["TmImageGallery_NoImages"]      = "Žádné obrázky",
        ["TmImageGallery_UploadImages"]  = "Nahrát obrázky",
        ["TmImageGallery_GridView"]      = "Mřížka",
        ["TmImageGallery_GalleryView"]   = "Galerie",

        // TmLayout
        ["TmSidebar_CollapseMenu"]     = "Sbalit menu",
        ["TmSidebar_ExpandMenu"]       = "Rozbalit menu",
        ["TmTopBar_OpenSearch"]        = "Hledat (Ctrl+K)",
        ["TmTopBar_OpenNotifications"] = "Otevřít oznámení",
        ["TmTopBar_OpenUserMenu"]      = "Otevřít nabídku uživatele",

        // TmCheckbox
        ["TmCheckbox_Indeterminate"] = "Částečně vybráno",

        // Validation
        ["TmValidation_Required"] = "Toto pole je povinné",
        ["TmValidation_Invalid"]  = "Toto pole obsahuje neplatnou hodnotu",

        // TmTimePicker
        ["TmTimePicker_Hours"]              = "Hodiny",
        ["TmTimePicker_Minutes"]            = "Minuty",
        ["TmTimePicker_Seconds"]            = "Sekundy",
        ["TmTimePicker_Placeholder"]        = "HH:mm",
        ["TmTimePicker_PlaceholderSeconds"] = "HH:mm:ss",
        ["TmTimePicker_Clear"]              = "Vymazat čas",

        // TmDatePicker
        ["TmDatePicker_Placeholder"]   = "dd.MM.yyyy",
        ["TmDatePicker_Clear"]         = "Vymazat datum",
        ["TmDatePicker_Today"]         = "Dnes",
        ["TmDatePicker_PreviousMonth"] = "Předchozí měsíc",
        ["TmDatePicker_NextMonth"]     = "Další měsíc",

        // TmDateTimePicker
        ["TmDateTimePicker_Placeholder"] = "dd.MM.yyyy HH:mm",
        ["TmDateTimePicker_Clear"]       = "Vymazat",

        // TmTimeRangePicker
        ["TmTimeRangePicker_From"]         = "Od",
        ["TmTimeRangePicker_To"]           = "Do",
        ["TmTimeRangePicker_Duration"]     = "Trvání",
        ["TmTimeRangePicker_Swap"]         = "Prohodit",
        ["TmTimeRangePicker_InvalidRange"] = "Konec musí být po začátku",

        // TmDateRangePicker
        ["TmDateRangePicker_From"]  = "Od",
        ["TmDateRangePicker_To"]    = "Do",
        ["TmDateRangePicker_Clear"] = "Vymazat rozsah",

        // TmDateTimeRangePicker
        ["TmDateTimeRangePicker_StartLabel"]      = "Začátek",
        ["TmDateTimeRangePicker_EndLabel"]        = "Konec",
        ["TmDateTimeRangePicker_Clear"]           = "Vymazat rozsah",
        ["TmDateTimeRangePicker_ValidationError"] = "Konec musí být po začátku",

        // TmFilterBuilder operators
        ["TmFilter_Contains"]      = "obsahuje",
        ["TmFilter_NotContains"]   = "neobsahuje",
        ["TmFilter_Equals"]        = "rovná se",
        ["TmFilter_NotEquals"]     = "nerovná se",
        ["TmFilter_GreaterThan"]   = "větší než",
        ["TmFilter_LessThan"]      = "menší než",
        ["TmFilter_GreaterOrEqual"]= "větší nebo rovno",
        ["TmFilter_LessOrEqual"]   = "menší nebo rovno",
        ["TmFilter_Between"]       = "mezi",
        ["TmFilter_IsEmpty"]       = "je prázdné",
        ["TmFilter_IsNotEmpty"]    = "není prázdné",
        ["TmFilter_In"]            = "v",
        ["TmFilter_NotIn"]         = "není v",

        // TmMultiViewList
        ["TmMvl_TableView"]   = "Tabulka",
        ["TmMvl_CardView"]    = "Karty",
        ["TmMvl_ListView"]    = "Seznam",
        ["TmMvl_ColTitle"]    = "Název",
        ["TmMvl_ColSubTitle"] = "Popis",
        ["TmMvl_ColStatus"]   = "Stav",
        ["TmMvl_ColDate"]     = "Datum",

        // TmValidationSummary
        ["TmValidationSummary_Title"] = "Při odesílání formuláře došlo k chybám",

        // TmPasswordStrengthIndicator
        ["TmPasswordStrength_VeryWeak"]                = "Velmi slabé",
        ["TmPasswordStrength_Weak"]                    = "Slabé",
        ["TmPasswordStrength_Medium"]                  = "Střední",
        ["TmPasswordStrength_Strong"]                  = "Silné",
        ["TmPasswordStrength_VeryStrong"]              = "Velmi silné",
        ["TmPasswordStrength_HintUseAtLeast8Chars"]    = "Použijte alespoň 8 znaků",
        ["TmPasswordStrength_HintAddLetters"]          = "Přidejte písmena",
        ["TmPasswordStrength_HintAddNumbers"]          = "Přidejte čísla",
        ["TmPasswordStrength_HintAddSpecialChars"]     = "Přidejte speciální znaky",
        ["TmPasswordStrength_HintAddUppercase"]        = "Přidejte velká písmena",
        ["TmPasswordStrength_HintAddLowercase"]        = "Přidejte malá písmena",
        ["TmPasswordStrength_HintMakeItLonger"]        = "Prodlužte heslo",
        ["TmPasswordStrength_HintAvoidCommonPatterns"] = "Vyhněte se běžným vzorům",
        ["TmPasswordStrength_HintAvoidCommonWords"]    = "Vyhněte se běžným slovům",
        ["TmPasswordStrength_HintExcellent"]           = "Vynikající heslo!",

        // TmToast
        ["TmToast_Close"] = "Zavřít",

        // TmAlert
        ["TmAlert_Dismiss"] = "Zavřít",

        // TmDrawer
        ["TmDrawer_Close"] = "Zavřít panel",

        // TmBulkActionBar
        ["TmBulkAction_Toolbar"] = "Hromadné akce",
        ["TmBulkAction_Selected"] = "vybráno",
        ["TmBulkAction_ClearSelection"] = "Zrušit výběr",

        // TmDataTable Grouping
        ["TmDataTable_GroupDropPlaceholder"] = "Přetáhněte záhlaví sloupce pro seskupení",
        ["TmDataTable_ExpandAll"] = "Rozbalit vše",
        ["TmDataTable_CollapseAll"] = "Sbalit vše",
        ["TmDataTable_GroupCount"] = "{0} položek",
        ["TmDataTable_SearchPlaceholder"] = "Hledat...",
        ["TmDataTable_ShowingItems"] = "{0}–{1} z {2}",
        ["TmDataTable_CurrentViewName"] = "Aktuální",

        // TmMultiViewList Grouping
        ["TmMvl_GroupBy"] = "Seskupit podle",
        ["TmMvl_GroupNone"] = "Bez seskupení",

        // TmViewManager Grouping
        ["TmViewManager_Grouping"] = "Seskupování",
        ["TmViewManager_GroupByColumns"] = "Seskupit podle sloupců",

        // TmInlineEdit
        ["TmInlineEdit_Placeholder"] = "Klikněte pro úpravu",

        // TmRichEditor - Tokens
        ["TmRichEditor_Token"]          = "Vložit proměnnou",
        ["TmRichEditor_TokenEmpty"]     = "Žádné proměnné nenalezeny",
        ["TmRichEditor_TokenCreateNew"] = "Vytvořit novou proměnnou...",
        ["TmRichEditor_TokenSearch"]    = "Hledat proměnné...",
        ["TmRichEditor_MentionEmpty"]   = "Uživatelé nenalezeni",
        ["TmRichEditor_Bold"]           = "Tučné",
        ["TmRichEditor_Italic"]         = "Kurzíva",
        ["TmRichEditor_Underline"]      = "Podtržené",
        ["TmRichEditor_Link"]           = "Odkaz",
        ["TmRichEditor_TaskList"]       = "Seznam úkolů",
        ["TmRichEditor_Emoji"]          = "Emoji",
        ["TmRichEditor_UnorderedList"]  = "Odrážkový seznam",
        ["TmRichEditor_OrderedList"]    = "Číslovaný seznam",
        ["TmRichEditor_Undo"]          = "Zpět",
        ["TmRichEditor_Redo"]          = "Znovu",
        ["TmRichEditor_Heading1"]      = "Nadpis 1",
        ["TmRichEditor_Heading2"]      = "Nadpis 2",
        ["TmRichEditor_Heading3"]      = "Nadpis 3",
        ["TmRichEditor_Heading4"]      = "Nadpis 4",
        ["TmRichEditor_Strikethrough"] = "Přeškrtnuté",
        ["TmRichEditor_Subscript"]     = "Dolní index",
        ["TmRichEditor_Superscript"]   = "Horní index",
        ["TmRichEditor_Indent"]        = "Odsadit",
        ["TmRichEditor_Outdent"]       = "Předsadit",
        ["TmRichEditor_Code"]          = "Blok kódu",
        ["TmRichEditor_Blockquote"]    = "Citace",
        ["TmRichEditor_HorizontalRule"]= "Vodorovná čára",
        ["TmRichEditor_TextColor"]     = "Barva textu",
        ["TmRichEditor_Highlight"]     = "Zvýraznění",
        ["TmRichEditor_Image"]         = "Obrázek",
        ["TmRichEditor_Table"]         = "Tabulka",
        ["TmRichEditor_Video"]         = "Video",
        ["TmRichEditor_RemoveFormat"]  = "Odstranit formátování",

        // TmDashboard
        ["TmDashboard_Edit"]                  = "Upravit",
        ["TmDashboard_EditMode"]              = "Režim úprav",
        ["TmDashboard_CancelEdit"]            = "Zrušit",
        ["TmDashboard_SaveChanges"]           = "Uložit změny",
        ["TmDashboard_AddWidget"]             = "Přidat widget",
        ["TmDashboard_AddWidgets"]            = "Přidat widgety",
        ["TmDashboard_Dashboards"]            = "Dashboardy",
        ["TmDashboard_MyDashboards"]          = "Moje dashboardy",
        ["TmDashboard_CreateNewDashboard"]    = "Vytvořit nový dashboard",
        ["TmDashboard_DashboardName"]         = "Název dashboardu",
        ["TmDashboard_DefaultDashboard"]      = "Výchozí",
        ["TmDashboard_SetAsDefault"]          = "Nastavit jako výchozí",
        ["TmDashboard_Delete"]                = "Smazat",
        ["TmDashboard_DeleteDashboard"]       = "Smazat dashboard",
        ["TmDashboard_DeleteDashboardConfirm"]= "Opravdu chcete smazat tento dashboard?",
        ["TmDashboard_NoWidgets"]             = "Zatím nebyly přidány žádné widgety",

        // TmWireframe
        ["TmDiagramEditor_AddPage"] = "Přidat stránku",
        ["TmDiagramEditor_ClosePage"] = "Zavřít stránku \"{0}\"",
        ["TmDiagramEditor_PageName"] = "Stránka",
        ["TmDiagramProperties_Link"] = "Odkaz",
        ["TmDiagramProperties_LinkPlaceholder"] = "https://...",
        ["TmDiagramProperties_LinkType_None"] = "Žádný",
        ["TmDiagramProperties_ExternalUrl"] = "Externí URL",
        ["TmDiagramProperties_PageLink"] = "Odkaz na stránku",
        ["TmDiagramProperties_Scale"] = "Měřítko",
        ["TmDiagramProperties_EdgePreset"] = "Předvolba",
        ["TmDiagramProperties_Preset_Custom"] = "Vlastní",
        ["TmDiagramProperties_Preset_ArrowRight"] = "→ Šipka",
        ["TmDiagramProperties_Preset_Line"] = "─ Čára",
        ["TmDiagramProperties_Preset_DoubleArrow"] = "⇒ Dvojitá šipka",
        ["TmDiagramProperties_Preset_CrossArrow"] = "⊣→ Křížek šipka",
        ["TmDiagramProperties_Preset_DoubleLine"] = "═ Dvojitá čára",
        ["TmDiagramProperties_Preset_ThickDoubleLine"] = "══ Tlustá dvojitá",
        ["TmDiagramProperties_Preset_Dashed"] = "- - Čárkovaná",
        ["TmDiagramProperties_EdgeShape"] = "Typ připojení",
        ["TmDiagramProperties_EdgeShape_Connector"] = "Spojnice",
        ["TmDiagramProperties_EdgeShape_Link"] = "Dvojitá čára",
        ["TmDiagramProperties_EdgeShape_FilledEdge"] = "Vyplněný pruh",
        ["TmDiagramProperties_EdgeShape_Pipe"] = "Roura",
        ["TmDiagramProperties_EdgeShape_Wire"] = "Vodič",
        ["TmDiagramProperties_ElbowOrientation"] = "Orientace lomené čáry",
        ["TmDiagramProperties_ElbowOrientation_Auto"] = "Auto",
        ["TmDiagramProperties_ElbowOrientation_Horizontal"] = "Nejprve vodorovně",
        ["TmDiagramProperties_ElbowOrientation_Vertical"] = "Nejprve svisle",
        ["TmDiagramProperties_FillArrow"] = "Vyplnit",
        ["TmDiagramProperties_LabelOffsetX"] = "Posun popisku X",
        ["TmDiagramProperties_LabelOffsetY"] = "Posun popisku Y",
        ["TmDiagramProperties_PlaceholdersHint"] = "Placeholdery: %page%, %pagenumber%, %totalpages%, %date%",
        ["TmDiagramEditor_DuplicatePage"] = "Duplikovat stránku",
        ["TmDiagramEditor_CopySuffix"] = "kopie",
        ["TmDiagramEditor_Cut"] = "Vyjmout",
        ["TmDiagramEditor_Copy"] = "Kopírovat",
        ["TmDiagramEditor_Duplicate"] = "Duplikovat",
        ["TmDiagramEditor_Paste"] = "Vložit",
        ["TmDiagramEditor_PasteHere"] = "Vložit sem",
        ["TmDiagramEditor_SelectAll"] = "Vybrat vše",
        ["TmDiagramEditor_Lock"] = "Uzamknout",
        ["TmDiagramEditor_Unlock"] = "Odemknout",
        ["TmDiagramEditor_Group"] = "Seskupit",
        ["TmDiagramEditor_Ungroup"] = "Rozdělit skupinu",
        ["TmDiagramEditor_PasteStyle"] = "Vložit styl",
        ["TmDiagramEditor_PasteSize"] = "Vložit velikost",
        ["TmDiagramEditor_ChangeShape"] = "Změnit tvar",
        ["TmDiagramEditor_Rectangle"] = "Obdélník",
        ["TmDiagramEditor_Ellipse"] = "Elipsa",
        ["TmDiagramEditor_Text"] = "Text",
        ["TmDiagramEditor_Diamond"] = "Kosočtverec",
        ["TmDiagramEditor_EditLabel"] = "Upravit popisek",
        ["TmDiagramEditor_Connector"] = "Spojnice",
        ["TmDiagramEditor_Straight"] = "Přímá",
        ["TmDiagramEditor_Orthogonal"] = "Orthogonální",
        ["TmDiagramEditor_Curved"] = "Křivka",
        ["TmDiagramEditor_StartArrow"] = "Počáteční šipka",
        ["TmDiagramEditor_EndArrow"] = "Koncová šipka",
        ["TmDiagramEditor_ArrowNone"] = "Žádná",
        ["TmDiagramEditor_ArrowClassic"] = "Klasická",
        ["TmDiagramEditor_ArrowBlock"] = "Blok",
        ["TmDiagramEditor_ArrowCrow"] = "Vraní noha",
        ["TmDiagramEditor_LineStyle"] = "Styl čáry",
        ["TmDiagramEditor_LineSolid"] = "Souvislá",
        ["TmDiagramEditor_LineDashed"] = "Čárkovaná",
        ["TmDiagramEditor_LineDotted"] = "Tečkovaná",
        ["TmDiagramEditor_Insert"] = "Vložit",
        ["TmDiagramEditor_Layout"] = "Rozvržení",
        ["TmDiagramEditor_LayoutDagreTb"] = "Dagre shora dolů",
        ["TmDiagramEditor_LayoutDagreLr"] = "Dagre zleva doprava",
        ["TmDiagramEditor_LayoutTree"] = "Strom",
        ["TmDiagramEditor_LayoutForce"] = "Síla",
        ["TmDiagramEditor_LayoutCircle"] = "Kruh",
        ["TmDiagramEditor_ShowGrid"] = "Zobrazit mřížku",
        ["TmDiagramEditor_HideGrid"] = "Skrýt mřížku",
        ["TmDiagramEditor_ShowPageView"] = "Zobrazit stránku",
        ["TmDiagramEditor_HidePageView"] = "Skrýt stránku",
        ["TmDiagramEditor_EnableSnap"] = "Zapnout přichycení",
        ["TmDiagramEditor_DisableSnap"] = "Vypnout přichycení",
        ["TmDiagramEditor_MergeCells"] = "Sloučit buňky",
        ["TmDiagramEditor_SplitCell"] = "Rozdělit buňku",
        ["TmDiagramEditor_FormatCell"] = "Formátovat buňku",
        ["TmDiagramEditor_CellWhite"] = "Bílá",
        ["TmDiagramEditor_CellLightGray"] = "Světle šedá",
        ["TmDiagramEditor_CellGray"] = "Šedá",
        ["TmDiagramEditor_ImportCsv"] = "Import CSV",
        ["TmDiagramEditor_Templates"] = "Šablony",
        ["TmDiagramTemplateGallery_Title"] = "Vyberte šablonu",
        ["TmDiagramTemplateGallery_SearchPlaceholder"] = "Hledat šablony...",
        ["TmDiagramTemplateGallery_All"] = "Vše",
        ["TmDiagramTemplateGallery_NoResults"] = "Žádná šablona neodpovídá hledání.",
        ["TmDiagramTemplateGallery_CreateButton"] = "Vytvořit",
        ["TmDiagramCsvImportDialog_Title"] = "Import CSV do diagramu",
        ["TmDiagramCsvImportDialog_CsvLabel"] = "CSV data",
        ["TmDiagramCsvImportDialog_CsvPlaceholder"] = "Vložte CSV data zde...",
        ["TmDiagramCsvImportDialog_TypeLabel"] = "Typ diagramu",
        ["TmDiagramCsvImportDialog_MappingsTitle"] = "Mapování sloupců",
        ["TmDiagramCsvImportDialog_SelectColumn"] = "Vyberte sloupec",
        ["TmDiagramCsvImportDialog_PreviewTitle"] = "Náhled (prvních 5 řádků)",
        ["TmDiagramCsvImportDialog_PreviewNodes"] = "Uzly: {0}",
        ["TmDiagramCsvImportDialog_PreviewEdges"] = "Hrany: {0}",
        ["TmDiagramCsvImportDialog_ImportButton"] = "Importovat",
        ["TmDiagramCsvImportDialog_ErrorEmpty"] = "Zadejte CSV data.",
        ["TmDiagramCsvImportDialog_ErrorNoData"] = "V zadaném CSV nebyly nalezeny žádné datové řádky.",
        ["TmDiagramCsvImportDialog_ErrorMinColumns"] = "CSV musí obsahovat alespoň 2 sloupce.",
        ["TmDiagramCsvImportDialog_ErrorMappings"] = "Přiřaďte všechny povinné sloupce.",
        ["TmDiagramCsvImportDialog_ErrorParse"] = "Nepodařilo se zpracovat CSV: {0}",
        ["TmDiagramEditor_ImportSql"] = "Import SQL → ER",
        ["TmDiagramSqlImportDialog_Title"] = "Import SQL do ER diagramu",
        ["TmDiagramSqlImportDialog_SqlLabel"] = "SQL DDL",
        ["TmDiagramSqlImportDialog_SqlPlaceholder"] = "Vložte příkazy CREATE TABLE...",
        ["TmDiagramSqlImportDialog_LayoutLabel"] = "Směr rozvržení",
        ["TmDiagramSqlImportDialog_PreviewTables"] = "Tabulky: {0}",
        ["TmDiagramSqlImportDialog_PreviewRelations"] = "Vztahy: {0}",
        ["TmDiagramSqlImportDialog_ImportButton"] = "Importovat",
        ["TmDiagramSqlImportDialog_ErrorEmpty"] = "Zadejte SQL DDL.",
        ["TmDiagramSqlImportDialog_ErrorNoTables"] = "V zadaném SQL nebyly nalezeny žádné tabulky.",
        ["TmDiagramSqlImportDialog_ErrorParse"] = "Nepodařilo se zpracovat SQL: {0}",
        ["TmDiagram_SearchPlaceholder"] = "Hledat v diagramu...",
        ["TmDiagram_SearchResults"] = "{0} z {1}",
        ["TmDiagram_SearchNoResults"] = "Žádné výsledky",
        ["TmDiagram_SearchPrevious"] = "Předchozí výsledek",
        ["TmDiagram_SearchNext"] = "Další výsledek",
        ["TmDiagram_SearchClose"] = "Zavřít hledání",
        ["TmDiagram_SearchAllPages"] = "Všechny stránky",
        ["TmDiagram_ReplacePlaceholder"] = "Nahradit za...",
        ["TmDiagram_Replace"] = "Nahradit",
        ["TmDiagram_ReplaceAll"] = "Nahradit vše",
        ["TmDiagram_UseRegex"] = "Použít regulární výrazy",
        ["TmDiagram_RegexError"] = "Neplatný regex: {0}",
        ["TmDiagram_ReplaceNoMatches"] = "Žádné nahraditelné výsledky",
        ["TmDiagram_EnableMathJax"] = "MathJax",

        // TmWireframe
        ["TmWireframe_UntitledPlaceholder"] = "Nepojmenovaný wireframe",
        ["TmWireframe_DocumentTitleLabel"] = "Název dokumentu",
        ["TmWireframe_SelectTool"] = "Nástroj výběru (V)",
        ["TmWireframe_PanTool"] = "Nástroj posunu (H)",
        ["TmWireframe_PanToolHint"] = "Nástroj posunu (H) — nebo podržte mezerník",
        ["TmWireframe_Undo"] = "Zpět",
        ["TmWireframe_Redo"] = "Znovu",
        ["TmWireframe_ZoomOut"] = "Oddálit",
        ["TmWireframe_ZoomIn"] = "Přiblížit",
        ["TmWireframe_FitToView"] = "Přizpůsobit zobrazení",
        ["TmWireframe_CanvasWidth"] = "Šířka plátna",
        ["TmWireframe_CanvasHeight"] = "Výška plátna",
        ["TmWireframe_Apply"] = "Použít",
        ["TmWireframe_Cancel"] = "Zrušit",
        ["TmWireframe_ChangeCanvasSize"] = "Změnit velikost plátna",
        ["TmWireframe_Export"] = "Exportovat",
        ["TmWireframe_ExportJson"] = "Exportovat JSON",
        ["TmWireframe_ExportSvg"] = "Exportovat SVG",
        ["TmWireframe_ExportPng"] = "Exportovat PNG",
        ["TmWireframe_ExportPdf"] = "Exportovat PDF",
        ["TmWireframe_ExportError"] = "Export selhal: {0}.",
        ["TmWireframeExportDialog_Title"] = "Exportovat wireframe",
        ["TmWireframeExportDialog_FileName"] = "Název souboru",
        ["TmWireframeExportDialog_FileNamePlaceholder"] = "wireframe",
        ["TmWireframeExportDialog_Format"] = "Formát",
        ["TmWireframeExportDialog_Scale"] = "Měřítko",
        ["TmWireframeExportDialog_IncludeBackground"] = "Zahrnout pozadí",
        ["TmWireframeExportDialog_ExportButton"] = "Exportovat",
        ["TmWireframe_ImportJson"] = "Importovat JSON",
        ["TmWireframe_SwitchToEditMode"] = "Přepnout do režimu úprav",
        ["TmWireframe_SwitchToReadOnlyMode"] = "Přepnout do režimu pouze pro čtení",
        ["TmWireframe_ReadOnly"] = "Pouze pro čtení",
        ["TmWireframe_Edit"] = "Upravit",
        ["TmWireframe_ShowToolbox"] = "Zobrazit panel nástrojů",
        ["TmWireframe_HideToolbox"] = "Skrýt panel nástrojů",
        ["TmWireframe_ToggleToolbox"] = "Přepnout panel nástrojů",
        ["TmWireframe_ShowProperties"] = "Zobrazit panel vlastností",
        ["TmWireframe_HideProperties"] = "Skrýt panel vlastností",
        ["TmWireframe_ToggleProperties"] = "Přepnout panel vlastností",
        ["TmWireframe_DismissError"] = "Zavřít chybu",
        ["TmWireframe_DefaultTitle"] = "Nepojmenovaný wireframe",
        ["TmWireframe_ExportFilename"] = "wireframe",
        ["TmWireframe_ImportError_InvalidJson"] = "Import se nezdařil: soubor není platný wireframe JSON.",
        ["TmWireframe_ImportError_Generic"] = "Import se nezdařil: {0}.",
        ["TmWireframeToolbox_SearchPlaceholder"] = "Hledat komponenty…",
        ["TmWireframeToolbox_ClearSearch"] = "Vymazat hledání",
        ["TmWireframeToolbox_FilterAll"] = "Vše",
        ["TmWireframeToolbox_FilterBuiltIn"] = "Vestavěné",
        ["TmWireframeToolbox_FilterCustom"] = "Vlastní",
        ["TmWireframeToolbox_NoComponentsMatch"] = "Žádné komponenty neodpovídají \"{0}\"",
        ["TmWireframeToolbox_CustomComponentTooltip"] = "Vlastní komponenta",
        ["TmWireframeToolbox_DragOntoCanvas"] = "Přetáhněte {0} na plátno",
        ["TmWireframeProps_NoSelectionTitle"] = "Nic není vybráno",
        ["TmWireframeProps_NoSelectionHint"] = "Vyberte prvek na plátně pro úpravu jeho vlastností.",
        ["TmWireframeProps_ElementsCount"] = "{0} prvků",
        ["TmWireframeProps_MixedTypes"] = "Smíšené typy",
        ["TmWireframeProps_SectionElement"] = "Prvek",
        ["TmWireframeProps_SectionLayout"] = "Rozvržení",
        ["TmWireframeProps_SectionGeneral"] = "Obecné",
        ["TmWireframeProps_Type"] = "Typ",
        ["TmWireframeProps_Types"] = "Typy",
        ["TmWireframeProps_ZIndex"] = "Z-Index",
        ["TmWireframeProps_X"] = "X",
        ["TmWireframeProps_Y"] = "Y",
        ["TmWireframeProps_W"] = "Š",
        ["TmWireframeProps_H"] = "V",
        ["TmWireframeProps_MixedPlaceholder"] = "Smíšené",
        ["TmWireframeProps_CommaSeparatedPlaceholder"] = "oddělené čárkou",
        ["TmWireframeProps_ValidationRegexError"] = "Hodnota neodpovídá vzoru: {0}",
        ["TmWireframeProps_CommandChangeZIndex"] = "Změnit Z-Index",
        ["TmWireframeCanvas_AriaLabel"] = "Plátno wireframe",
        ["TmWireframeCanvas_UnknownComponent"] = "Neznámá: {0}",
        ["TmWireframeProps_CatContent"] = "Obsah",
        ["TmWireframeProps_CatAppearance"] = "Vzhled",
        ["TmWireframeProps_CatBehavior"] = "Chování",
        ["TmWireframeProps_CatState"] = "Stav",

        ["TmWireframe_LayersToggle"] = "Přepnout panel vrstev",
        ["TmWireframe_LayersTitle"] = "Vrstvy",
        ["TmWireframe_AddLayer"] = "Přidat vrstvu",
        ["TmWireframe_SetActiveLayer"] = "Nastavit jako aktivní vrstvu",
        ["TmWireframe_HideLayer"] = "Skrýt vrstvu",
        ["TmWireframe_ShowLayer"] = "Zobrazit vrstvu",
        ["TmWireframe_UnlockLayer"] = "Odemknout vrstvu",
        ["TmWireframe_LockLayer"] = "Zamknout vrstvu",
        ["TmWireframe_DoubleClickToEdit"] = "Dvojklikem upravte název",
        ["TmWireframe_DeleteLayer"] = "Smazat vrstvu",
        ["TmWireframe_MoveToLayer"] = "Přesunout do vrstvy",
        ["TmWireframe_SelectLayer"] = "Vyberte vrstvu",
        ["TmWireframe_Layer"] = "Vrstva",
        ["TmWireframeProps_Layer"] = "Vrstva",
        ["TmWireframe_ShowRulers"] = "Zobrazit pravítka",
        ["TmWireframe_HorizontalRuler"] = "Vodorovné pravítko",
        ["TmWireframe_VerticalRuler"] = "Svislé pravítko",
    });
}

/// <summary>
/// Minimal in-memory ITmLocalizer for testing. Returns [key] for unknown keys.
/// </summary>
public sealed class MockTmLocalizer : ITmLocalizer
{
    private readonly Dictionary<string, string> _data;

    public MockTmLocalizer(Dictionary<string, string> data) => _data = data;

    public string this[string key] =>
        _data.TryGetValue(key, out var v) ? v : $"[{key}]";

    public string this[string key, params object[] arguments]
    {
        get
        {
            var template = _data.TryGetValue(key, out var v) ? v : $"[{key}]";
            return arguments.Length > 0 ? string.Format(template, arguments) : template;
        }
    }
}
