using Bunit;
using Microsoft.Extensions.DependencyInjection;
using Tempo.Blazor.Localization;
using Tempo.Blazor.Services;

namespace Tempo.Blazor.Tests.Localization;

/// <summary>
/// Base class for all bUnit component tests.
/// Registers a default English MockTmLocalizer so that @inject ITmLocalizer Loc
/// is always resolved in the test DI container.
/// Tests can override specific keys by calling Services.AddSingleton&lt;ITmLocalizer&gt;(...)
/// AFTER base registration (last registration wins in .NET DI).
/// </summary>
public abstract class LocalizationTestBase : TestContext
{
    protected LocalizationTestBase()
    {
        Services.AddSingleton<ITmLocalizer>(BuildEnglishLocalizer());
        Services.AddScoped<DragDropService>();
        Services.AddSingleton<Tempo.Blazor.Components.Diagram.Stencils.DiagramStencilRegistry>();
        Services.AddSingleton<Tempo.Blazor.Components.Diagram.Templates.DiagramTemplateRegistry>();
        Services.AddHttpClient();
        JSInterop.Mode = JSRuntimeMode.Loose;
    }

    /// <summary>Registers a Czech localizer for this test context.</summary>
    protected void UseCzechLocalization()
    {
        Services.AddSingleton<ITmLocalizer>(BuildCzechLocalizer());
    }

    /// <summary>Registers a custom localizer with the provided key/value pairs.</summary>
    protected void UseCustomLocalization(Dictionary<string, string> keys)
    {
        Services.AddSingleton<ITmLocalizer>(new MockTmLocalizer(keys));
    }

    private static MockTmLocalizer BuildEnglishLocalizer() => new(new Dictionary<string, string>
    {
        // Shared
        ["Tm_Loading"]          = "Loading...",
        ["Tm_Close"]            = "Close",
        ["Tm_Cancel"]           = "Cancel",
        ["Tm_Save"]             = "Save",
        ["Tm_Delete"]           = "Delete",
        ["Tm_Confirm"]          = "Confirm",
        ["Tm_NoResults"]        = "No results found",
        ["Tm_Error"]            = "An error occurred",
        ["Tm_Retry"]            = "Retry",
        ["Tm_Search"]           = "Search",
        ["Tm_Clear"]            = "Clear",
        ["Tm_Select"]           = "Select",
        ["Tm_SelectAll"]        = "Select all",
        ["Tm_DeselectAll"]      = "Deselect all",
        ["Tm_Edit"]             = "Edit",
        ["Tm_Add"]              = "Add",
        ["Tm_Remove"]           = "Remove",
        ["Tm_Apply"]            = "Apply",
        ["Tm_Reset"]            = "Reset",
        ["Tm_Previous"]         = "Previous",
        ["Tm_Next"]             = "Next",
        ["Tm_Download"]         = "Download",
        ["Tm_Upload"]           = "Upload",
        ["Tm_Create"]           = "Create",
        ["Tm_Optional"]         = "Optional",
        ["Tm_Required"]         = "Required",
        ["Tm_Yes"]              = "Yes",
        ["Tm_No"]               = "No",

        // TmButton
        ["TmButton_Loading"] = "Loading",

        // TmSearchInput
        ["TmSearchInput_Placeholder"] = "Search...",
        ["TmSearchInput_Clear"]       = "Clear search",

        // TmEmptyState
        ["TmEmptyState_DefaultTitle"] = "No data available",

        // TmDataTable
        ["TmDataTable_NoResults"]          = "No results found",
        ["TmDataTable_Loading"]            = "Loading data...",
        ["TmDataTable_PageSize"]           = "Items per page",
        ["TmDataTable_Pagination"]         = "{0}â€“{1} of {2}",
        ["TmDataTable_SelectAll"]          = "Select all rows",
        ["TmDataTable_DeselectAll"]        = "Deselect all rows",
        ["TmDataTable_ColumnPicker"]       = "Choose columns",
        ["TmDataTable_ResetColumns"]       = "Reset to default",
        ["TmDataTable_SaveView"]           = "Save view",
        ["TmDataTable_ManageViews"]        = "Manage views",
        ["TmDataTable_DefaultView"]        = "Default view",
        ["TmDataTable_Filter"]             = "Filter",
        ["TmDataTable_ClearFilters"]       = "Clear filters",
        ["TmDataTable_SortAscending"]      = "Sort ascending",
        ["TmDataTable_SortDescending"]     = "Sort descending",
        ["TmDataTable_BulkActions"]        = "{0} selected",
        ["TmDataTable_DeleteSelected"]     = "Delete selected",
        ["TmDataTable_EditInline"]         = "Edit",
        ["TmDataTable_SaveInline"]         = "Save changes",
        ["TmDataTable_CancelInline"]       = "Cancel edit",
        ["TmDataTable_FirstPage"]          = "First page",
        ["TmDataTable_LastPage"]           = "Last page",
        ["TmDataTable_ViewName"]           = "View name",
        ["TmDataTable_ViewNamePlaceholder"]= "Enter view name...",
        ["TmDataTable_DeleteView"]         = "Delete view",

        // TmFilterableDropdown
        ["TmFilterableDropdown_Search"]        = "Search...",
        ["TmFilterableDropdown_NoResults"]     = "No results found",
        ["TmFilterableDropdown_Loading"]       = "Loading...",
        ["TmFilterableDropdown_Error"]         = "Failed to load options",
        ["TmFilterableDropdown_Retry"]         = "Retry",
        ["TmFilterableDropdown_CreateNew"]     = "Create \"{0}\"",
        ["TmFilterableDropdown_ClearSelection"]= "Clear selection",
        ["TmFilterableDropdown_Placeholder"]   = "Select an option...",

        // TmFileDropZone
        ["TmFileDropZone_DragDrop"]      = "Drag and drop files here",
        ["TmFileDropZone_Or"]            = "or",
        ["TmFileDropZone_Browse"]        = "Browse files",
        ["TmFileDropZone_Uploading"]     = "Uploading...",
        ["TmFileDropZone_Remove"]        = "Remove file",
        ["TmFileDropZone_MaxSize"]       = "Maximum file size: {0}",
        ["TmFileDropZone_AcceptedTypes"] = "Accepted types: {0}",

        // TmTimeline
        ["TmTimeline_NoEntries"]   = "No activity yet",
        ["TmTimeline_Internal"]    = "Internal",
        ["TmTimeline_JustNow"]     = "Just now",
        ["TmTimeline_MinutesAgo"]  = "{0} min ago",
        ["TmTimeline_HoursAgo"]    = "{0} h ago",
        ["TmTimeline_DaysAgo"]     = "{0} days ago",
        ["TmTimeline_DateFormat"]  = "MMM d, yyyy",

        // TmTreeView
        ["TmTreeView_Search"]    = "Search...",
        ["TmTreeView_NoResults"] = "No items found",
        ["TmTreeView_Loading"]   = "Loading...",
        ["TmTreeView_Expand"]    = "Expand",
        ["TmTreeView_Collapse"]  = "Collapse",

        // TmTagPicker
        ["TmTagPicker_Search"]    = "Search tags...",
        ["TmTagPicker_CreateNew"] = "Create \"{0}\"",
        ["TmTagPicker_NoTags"]    = "No tags found",
        ["TmTagPicker_AddTag"]    = "Add tag",

        // TmCommandPalette
        ["TmCommandPalette_Placeholder"] = "Type a command or search...",
        ["TmCommandPalette_NoResults"]   = "No commands found",

        // TmStepper
        ["TmStepper_Step"]      = "Step {0} of {1}",
        ["TmStepper_Completed"] = "Completed",

        // TmAvatar
        ["TmAvatar_ImageAlt"] = "User avatar",

        // TmNotificationBell
        ["TmNotificationBell_AriaLabel"]        = "Notifications",
        ["TmNotificationBell_NewCount"]         = "{0} new notifications",
        ["TmNotificationBell_NoNotifications"]  = "No notifications",
        ["TmNotificationBell_MarkAllRead"]      = "Mark all as read",

        // TmImageGallery
        ["TmImageGallery_PreviousImage"] = "Previous image",
        ["TmImageGallery_NextImage"]     = "Next image",
        ["TmImageGallery_Close"]         = "Close gallery",
        ["TmImageGallery_Counter"]       = "{0} of {1}",
        ["TmImageGallery_LoadingImage"]  = "Loading image...",
        ["TmImageGallery_ErrorLoading"]  = "Failed to load image",
        ["TmImageGallery_ZoomIn"]        = "Zoom in",
        ["TmImageGallery_ZoomOut"]       = "Zoom out",
        ["TmImageGallery_Download"]      = "Download image",
        ["TmImageGallery_Delete"]        = "Delete image",
        ["TmImageGallery_NoImages"]      = "No images available",
        ["TmImageGallery_UploadImages"]  = "Upload images",
        ["TmImageGallery_GridView"]      = "Grid view",
        ["TmImageGallery_GalleryView"]   = "Gallery view",

        // TmLayout
        ["TmSidebar_CollapseMenu"]       = "Collapse menu",
        ["TmSidebar_ExpandMenu"]         = "Expand menu",
        ["TmTopBar_OpenSearch"]          = "Search (Ctrl+K)",
        ["TmTopBar_OpenNotifications"]   = "Open notifications",
        ["TmTopBar_OpenUserMenu"]        = "Open user menu",

        // TmCheckbox
        ["TmCheckbox_Indeterminate"] = "Partially selected",

        // Validation
        ["TmValidation_Required"] = "This field is required",
        ["TmValidation_Invalid"]  = "This field contains an invalid value",

        // TmTimePicker
        ["TmTimePicker_Hours"]              = "Hours",
        ["TmTimePicker_Minutes"]            = "Minutes",
        ["TmTimePicker_Seconds"]            = "Seconds",
        ["TmTimePicker_Placeholder"]        = "HH:mm",
        ["TmTimePicker_PlaceholderSeconds"] = "HH:mm:ss",
        ["TmTimePicker_Clear"]              = "Clear time",

        // TmDatePicker
        ["TmDatePicker_Placeholder"]    = "dd.MM.yyyy",
        ["TmDatePicker_Clear"]          = "Clear date",
        ["TmDatePicker_Today"]          = "Today",
        ["TmDatePicker_PreviousMonth"]  = "Previous month",
        ["TmDatePicker_NextMonth"]      = "Next month",

        // TmDateTimePicker
        ["TmDateTimePicker_Placeholder"] = "dd.MM.yyyy HH:mm",
        ["TmDateTimePicker_Clear"]       = "Clear",

        // TmTimeRangePicker
        ["TmTimeRangePicker_From"]         = "From",
        ["TmTimeRangePicker_To"]           = "To",
        ["TmTimeRangePicker_Duration"]     = "Duration",
        ["TmTimeRangePicker_Swap"]         = "Swap",
        ["TmTimeRangePicker_InvalidRange"] = "End time must be after start time",

        // TmDateRangePicker
        ["TmDateRangePicker_From"]   = "From",
        ["TmDateRangePicker_To"]     = "To",
        ["TmDateRangePicker_Clear"]  = "Clear range",

        // TmDateTimeRangePicker
        ["TmDateTimeRangePicker_StartLabel"]      = "Start",
        ["TmDateTimeRangePicker_EndLabel"]        = "End",
        ["TmDateTimeRangePicker_Clear"]           = "Clear range",
        ["TmDateTimeRangePicker_ValidationError"] = "End must be after start",

        // TmRating
        ["TmRating_AriaLabel"] = "Rating",

        // TmBottomNavigation
        ["TmBottomNavigation_AriaLabel"] = "Bottom navigation",

        // TmMultiSelect
        ["TmMultiSelect_ConfirmButton"] = "Done",

        // TmMultiSelect
        ["TmMultiSelect_ConfirmButton"] = "Hotovo",

        // TmFilterBuilder operators
        ["TmFilter_Contains"]      = "contains",
        ["TmFilter_NotContains"]   = "does not contain",
        ["TmFilter_Equals"]        = "equals",
        ["TmFilter_NotEquals"]     = "not equals",
        ["TmFilter_GreaterThan"]   = "greater than",
        ["TmFilter_LessThan"]      = "less than",
        ["TmFilter_GreaterOrEqual"]= "greater or equal",
        ["TmFilter_LessOrEqual"]   = "less or equal",
        ["TmFilter_Between"]       = "between",
        ["TmFilter_IsEmpty"]       = "is empty",
        ["TmFilter_IsNotEmpty"]    = "is not empty",
        ["TmFilter_In"]            = "in",
        ["TmFilter_NotIn"]         = "not in",

        // TmMultiViewList
        ["TmMvl_TableView"]   = "Table view",
        ["TmMvl_CardView"]    = "Card view",
        ["TmMvl_ListView"]    = "List view",
        ["TmMvl_ColTitle"]    = "Title",
        ["TmMvl_ColSubTitle"] = "Subtitle",
        ["TmMvl_ColStatus"]   = "Status",
        ["TmMvl_ColDate"]     = "Date",

        // TmValidationSummary
        ["TmValidationSummary_Title"] = "There were errors with your submission",

        // TmPasswordStrengthIndicator
        ["TmPasswordStrength_VeryWeak"]                = "Very weak",
        ["TmPasswordStrength_Weak"]                    = "Weak",
        ["TmPasswordStrength_Medium"]                  = "Medium",
        ["TmPasswordStrength_Strong"]                  = "Strong",
        ["TmPasswordStrength_VeryStrong"]              = "Very strong",
        ["TmPasswordStrength_HintUseAtLeast8Chars"]    = "Use at least 8 characters",
        ["TmPasswordStrength_HintAddLetters"]          = "Add letters",
        ["TmPasswordStrength_HintAddNumbers"]          = "Add numbers",
        ["TmPasswordStrength_HintAddSpecialChars"]     = "Add special characters",
        ["TmPasswordStrength_HintAddUppercase"]        = "Add uppercase letters",
        ["TmPasswordStrength_HintAddLowercase"]        = "Add lowercase letters",
        ["TmPasswordStrength_HintMakeItLonger"]        = "Make it longer",
        ["TmPasswordStrength_HintAvoidCommonPatterns"] = "Avoid common patterns",
        ["TmPasswordStrength_HintAvoidCommonWords"]    = "Avoid common words",
        ["TmPasswordStrength_HintExcellent"]           = "Excellent password!",

        // TmToast
        ["TmToast_Close"] = "Dismiss",

        // TmAlert
        ["TmAlert_Dismiss"] = "Dismiss",

        // TmDrawer
        ["TmDrawer_Close"] = "Close panel",

        // TmBulkActionBar
        ["TmBulkAction_Toolbar"] = "Bulk actions",
        ["TmBulkAction_Selected"] = "selected",
        ["TmBulkAction_ClearSelection"] = "Clear selection",

        // TmDataTable Grouping
        ["TmDataTable_GroupDropPlaceholder"] = "Drag column headers here to group",
        ["TmDataTable_ExpandAll"] = "Expand all",
        ["TmDataTable_CollapseAll"] = "Collapse all",
        ["TmDataTable_GroupCount"] = "{0} items",
        ["TmDataTable_SearchPlaceholder"] = "Search...",
        ["TmDataTable_ShowingItems"] = "{0}â€“{1} of {2}",
        ["TmDataTable_CurrentViewName"] = "Current",

        // TmMultiViewList Grouping
        ["TmMvl_GroupBy"] = "Group by",
        ["TmMvl_GroupNone"] = "No grouping",

        // TmViewManager Grouping
        ["TmViewManager_Grouping"] = "Grouping",
        ["TmViewManager_GroupByColumns"] = "Group by columns",

        // TmInlineEdit
        ["TmInlineEdit_Placeholder"] = "Click to edit",

        // TmRichEditor - Tokens
        ["TmRichEditor_Token"]          = "Insert variable",
        ["TmRichEditor_TokenEmpty"]     = "No variables found",
        ["TmRichEditor_TokenCreateNew"] = "Create new variable...",
        ["TmRichEditor_TokenSearch"]    = "Search variables...",
        ["TmRichEditor_MentionEmpty"]   = "No users found",
        ["TmRichEditor_Bold"]           = "Bold",
        ["TmRichEditor_Italic"]         = "Italic",
        ["TmRichEditor_Underline"]      = "Underline",
        ["TmRichEditor_Link"]           = "Link",
        ["TmRichEditor_TaskList"]       = "Task list",
        ["TmRichEditor_Emoji"]          = "Emoji",
        ["TmRichEditor_UnorderedList"]  = "Bullet list",
        ["TmRichEditor_OrderedList"]    = "Numbered list",
        ["TmRichEditor_Undo"]          = "Undo",
        ["TmRichEditor_Redo"]          = "Redo",
        ["TmRichEditor_Heading1"]      = "Heading 1",
        ["TmRichEditor_Heading2"]      = "Heading 2",
        ["TmRichEditor_Heading3"]      = "Heading 3",
        ["TmRichEditor_Heading4"]      = "Heading 4",
        ["TmRichEditor_Strikethrough"] = "Strikethrough",
        ["TmRichEditor_Subscript"]     = "Subscript",
        ["TmRichEditor_Superscript"]   = "Superscript",
        ["TmRichEditor_Indent"]        = "Indent",
        ["TmRichEditor_Outdent"]       = "Outdent",
        ["TmRichEditor_Code"]          = "Code block",
        ["TmRichEditor_Blockquote"]    = "Blockquote",
        ["TmRichEditor_HorizontalRule"]= "Horizontal line",
        ["TmRichEditor_TextColor"]     = "Text color",
        ["TmRichEditor_Highlight"]     = "Highlight",
        ["TmRichEditor_Image"]         = "Image",
        ["TmRichEditor_Table"]         = "Table",
        ["TmRichEditor_Video"]         = "Video",
        ["TmRichEditor_RemoveFormat"]  = "Remove formatting",

        // TmDashboard
        ["TmDashboard_Edit"]                  = "Edit",
        ["TmDashboard_EditMode"]              = "Edit Mode",
        ["TmDashboard_CancelEdit"]            = "Cancel",
        ["TmDashboard_SaveChanges"]           = "Save Changes",
        ["TmDashboard_AddWidget"]             = "Add Widget",
        ["TmDashboard_AddWidgets"]            = "Add Widgets",
        ["TmDashboard_Dashboards"]            = "Dashboards",
        ["TmDashboard_MyDashboards"]          = "My Dashboards",
        ["TmDashboard_CreateNewDashboard"]    = "Create New Dashboard",
        ["TmDashboard_DashboardName"]         = "Dashboard Name",
        ["TmDashboard_DefaultDashboard"]      = "Default",
        ["TmDashboard_SetAsDefault"]          = "Set as Default",
        ["TmDashboard_Delete"]                = "Delete",
        ["TmDashboard_DeleteDashboard"]       = "Delete Dashboard",
        ["TmDashboard_DeleteDashboardConfirm"]= "Are you sure you want to delete this dashboard?",
        ["TmDashboard_NoWidgets"]             = "No widgets added yet",

        // TmDiagramEditor
        ["TmDiagramEditor_ToolbarAriaLabel"] = "Diagram editor toolbar",
        ["TmDiagramEditor_UntitledPlaceholder"] = "Untitled diagram",
        ["TmDiagramEditor_DocumentTitleLabel"] = "Document title",
        ["TmDiagramEditor_SelectTool"] = "Select tool (V)",
        ["TmDiagramEditor_PanTool"] = "Pan tool (H)",
        ["TmDiagramEditor_PanToolHint"] = "Pan tool (H) â€” or hold Space",
        ["TmDiagramEditor_EdgeTool"] = "Edge tool (L)",
        ["TmDiagramEditor_EdgeToolHint"] = "Edge tool (L / C) â€” click a node, drag for a single line, or click-click-... for a polyline (finish with double-click / Enter)",
        ["TmDiagramEditor_Undo"] = "Undo",
        ["TmDiagramEditor_Redo"] = "Redo",
        ["TmDiagramEditor_ZoomOut"] = "Zoom out",
        ["TmDiagramEditor_ZoomIn"] = "Zoom in",
        ["TmDiagramEditor_FitToView"] = "Fit to view",
        ["TmDiagramEditor_ToggleRulers"] = "Toggle rulers",
        ["TmDiagramEditor_RulerUnitLabel"] = "Ruler unit",
        ["TmDiagramEditor_CanvasWidth"] = "Canvas width",
        ["TmDiagramEditor_CanvasHeight"] = "Canvas height",
        ["TmDiagramEditor_Apply"] = "Apply",
        ["TmDiagramEditor_Cancel"] = "Cancel",
        ["TmDiagramEditor_ChangeCanvasSize"] = "Change canvas size",
        ["TmDiagramEditor_Export"] = "Export",
        ["TmDiagramEditor_ExportJson"] = "Export JSON",
        ["TmDiagramEditor_ExportSvg"] = "Export SVG",
        ["TmDiagramEditor_ExportPng"] = "Export PNG",
        ["TmDiagramEditor_ExportPdf"] = "Export PDF",
        ["TmDiagramEditor_ImportJson"] = "Import JSON",
        ["TmDiagramEditor_ImportSql"] = "Import SQL â†’ ER",
        ["TmDiagramEditor_VirtualBend"] = "Virtual bend",
        ["TmDiagramSqlImportDialog_Title"] = "Import SQL to ER Diagram",
        ["TmDiagramSqlImportDialog_SqlLabel"] = "SQL DDL",
        ["TmDiagramSqlImportDialog_SqlPlaceholder"] = "Paste CREATE TABLE statements here...",
        ["TmDiagramSqlImportDialog_LayoutLabel"] = "Layout direction",
        ["TmDiagramSqlImportDialog_PreviewTables"] = "Tables: {0}",
        ["TmDiagramSqlImportDialog_PreviewRelations"] = "Relations: {0}",
        ["TmDiagramSqlImportDialog_ImportButton"] = "Import",
        ["TmDiagramSqlImportDialog_ErrorEmpty"] = "Please enter SQL DDL.",
        ["TmDiagramSqlImportDialog_ErrorNoTables"] = "No tables found in the provided SQL.",
        ["TmDiagramSqlImportDialog_ErrorParse"] = "Failed to parse SQL: {0}",
        ["TmDiagramEditor_SwitchToEditMode"] = "Switch to edit mode",
        ["TmDiagramEditor_SwitchToReadOnlyMode"] = "Switch to read-only mode",
        ["TmDiagramEditor_ReadOnly"] = "Read-only",
        ["TmDiagramEditor_Edit"] = "Edit",
        ["TmDiagramEditor_ShowToolbox"] = "Show toolbox",
        ["TmDiagramEditor_HideToolbox"] = "Hide toolbox",
        ["TmDiagramEditor_ToggleToolbox"] = "Toggle toolbox",
        ["TmDiagramEditor_ShowProperties"] = "Show properties panel",
        ["TmDiagramEditor_HideProperties"] = "Hide properties panel",
        ["TmDiagramEditor_ToggleProperties"] = "Toggle properties panel",
        ["TmDiagramEditor_ShowLayers"] = "Show layers",
        ["TmDiagramEditor_HideLayers"] = "Hide layers",
        ["TmDiagramEditor_ToggleLayers"] = "Toggle layers",
        ["TmDiagramEditor_ShowMinimap"] = "Show minimap",
        ["TmDiagramEditor_HideMinimap"] = "Hide minimap",
        ["TmDiagramEditor_ToggleMinimap"] = "Toggle minimap",
        ["TmDiagramEditor_DismissError"] = "Dismiss error",
        ["TmDiagramEditor_ImportError_InvalidJson"] = "Failed to import: the file is not a valid diagram JSON.",
        ["TmDiagramEditor_ImportError_Generic"] = "Failed to import: {0}.",
        ["TmDiagramEditor_ExportError"] = "Export failed: {0}.",
        ["TmDiagramEditor_BringToFront"] = "Bring to front",
        ["TmDiagramEditor_SendToBack"] = "Send to back",
        ["TmDiagramEditor_Delete"] = "Delete",
        ["TmDiagramEditor_Cut"] = "Cut",
        ["TmDiagramEditor_Copy"] = "Copy",
        ["TmDiagramEditor_Duplicate"] = "Duplicate",
        ["TmDiagramEditor_Paste"] = "Paste",
        ["TmDiagramEditor_PasteHere"] = "Paste Here",
        ["TmDiagramEditor_SelectAll"] = "Select All",
        ["TmDiagramEditor_Lock"] = "Lock",
        ["TmDiagramEditor_Unlock"] = "Unlock",
        ["TmDiagramEditor_Group"] = "Group",
        ["TmDiagramEditor_Ungroup"] = "Ungroup",
        ["TmDiagramEditor_PasteStyle"] = "Paste Style",
        ["TmDiagramEditor_PasteSize"] = "Paste Size",
        ["TmDiagramEditor_ChangeShape"] = "Change Shape",
        ["TmDiagramEditor_Rectangle"] = "Rectangle",
        ["TmDiagramEditor_Ellipse"] = "Ellipse",
        ["TmDiagramEditor_Text"] = "Text",
        ["TmDiagramEditor_Diamond"] = "Diamond",
        ["TmDiagramEditor_EditLabel"] = "Edit Label",
        ["TmDiagramEditor_Connector"] = "Connector",
        ["TmDiagramEditor_Straight"] = "Straight",
        ["TmDiagramEditor_Orthogonal"] = "Orthogonal",
        ["TmDiagramEditor_Curved"] = "Curved",
        ["TmDiagramEditor_StartArrow"] = "Start Arrow",
        ["TmDiagramEditor_EndArrow"] = "End Arrow",
        ["TmDiagramEditor_ArrowNone"] = "None",
        ["TmDiagramEditor_ArrowClassic"] = "Classic",
        ["TmDiagramEditor_ArrowBlock"] = "Block",
        ["TmDiagramEditor_ArrowCrow"] = "Crow",
        ["TmDiagramEditor_LineStyle"] = "Line Style",
        ["TmDiagramEditor_LineSolid"] = "Solid",
        ["TmDiagramEditor_LineDashed"] = "Dashed",
        ["TmDiagramEditor_LineDotted"] = "Dotted",
        ["TmDiagramEditor_Insert"] = "Insert",
        ["TmDiagramEditor_InsertTable"] = "Table",
        ["TmDiagramEditor_InsertText"] = "Text",
        ["TmDiagramEditor_InsertGroup"] = "Group",
        ["TmDiagramTableInserter_Title"] = "Insert table",
        ["TmDiagramEditor_Layout"] = "Layout",
        ["TmDiagramEditor_LayoutDagreTb"] = "Dagre Top-Bottom",
        ["TmDiagramEditor_LayoutDagreLr"] = "Dagre Left-Right",
        ["TmDiagramEditor_LayoutTree"] = "Tree",
        ["TmDiagramEditor_LayoutForce"] = "Force",
        ["TmDiagramEditor_LayoutCircle"] = "Circle",
        ["TmDiagramEditor_ShowGrid"] = "Show Grid",
        ["TmDiagramEditor_HideGrid"] = "Hide Grid",
        ["TmDiagramEditor_ShowPageView"] = "Show Page View",
        ["TmDiagramEditor_HidePageView"] = "Hide Page View",
        ["TmDiagramEditor_EnableSnap"] = "Enable Snap to Grid",
        ["TmDiagramEditor_DisableSnap"] = "Disable Snap to Grid",
        ["TmDiagramEditor_MergeCells"] = "Merge Cells",
        ["TmDiagramEditor_SplitCell"] = "Split Cell",
        ["TmDiagramEditor_FormatCell"] = "Format Cell",
        ["TmDiagramEditor_CellWhite"] = "White",
        ["TmDiagramEditor_CellLightGray"] = "Light Gray",
        ["TmDiagramEditor_CellGray"] = "Gray",
        ["TmDiagramEditor_ImportCsv"] = "Import CSV",
        ["TmDiagramEditor_Templates"] = "Templates",
        ["TmDiagramTemplateGallery_Title"] = "Choose a Template",
        ["TmDiagramTemplateGallery_SearchPlaceholder"] = "Search templates...",
        ["TmDiagramTemplateGallery_All"] = "All",
        ["TmDiagramTemplateGallery_NoResults"] = "No templates match your search.",
        ["TmDiagramTemplateGallery_CreateButton"] = "Create",
        ["TmDiagramCsvImportDialog_Title"] = "Import CSV to Diagram",
        ["TmDiagramCsvImportDialog_CsvLabel"] = "CSV Data",
        ["TmDiagramCsvImportDialog_CsvPlaceholder"] = "Paste CSV data here...",
        ["TmDiagramCsvImportDialog_TypeLabel"] = "Diagram type",
        ["TmDiagramCsvImportDialog_MappingsTitle"] = "Column mapping",
        ["TmDiagramCsvImportDialog_SelectColumn"] = "Select column",
        ["TmDiagramCsvImportDialog_PreviewTitle"] = "Preview (first 5 rows)",
        ["TmDiagramCsvImportDialog_PreviewNodes"] = "Nodes: {0}",
        ["TmDiagramCsvImportDialog_PreviewEdges"] = "Edges: {0}",
        ["TmDiagramCsvImportDialog_ImportButton"] = "Import",
        ["TmDiagramCsvImportDialog_ErrorEmpty"] = "Please enter CSV data.",
        ["TmDiagramCsvImportDialog_ErrorNoData"] = "No data rows found in the provided CSV.",
        ["TmDiagramCsvImportDialog_ErrorMinColumns"] = "CSV must contain at least 2 columns.",
        ["TmDiagramCsvImportDialog_ErrorMappings"] = "Please map all required columns.",
        ["TmDiagramCsvImportDialog_ErrorParse"] = "Failed to parse CSV: {0}",
        ["TmDiagramMinimap_Title"] = "Minimap",
        ["TmDiagramMinimap_Empty"] = "No diagram to show",
        ["TmDiagramLayers_Title"] = "Layers",
        ["TmDiagramLayers_AddLayer"] = "Add layer",
        ["TmDiagramLayers_Show"] = "Show",
        ["TmDiagramLayers_Hide"] = "Hide",
        ["TmDiagramLayers_Lock"] = "Lock",
        ["TmDiagramLayers_Unlock"] = "Unlock",
        ["TmDiagramLayers_DefaultLayer"] = "Default Layer",
        ["TmDiagramLayers_DeleteLayer"] = "Delete layer",
        ["TmDiagramLayers_AssignToLayer"] = "Assign to layer",
        ["TmDiagramLayers_Layer"] = "Layer",
        ["TmDiagramProperties_Layer"] = "Layer",
        ["TmDiagramProperties_Title"] = "Properties",
        ["TmDiagramProperties_NodeTitle"] = "Node",
        ["TmDiagramProperties_EdgeTitle"] = "Edge",
        ["TmDiagramProperties_Label"] = "Label",
        ["TmDiagramProperties_LabelOffsetX"] = "Label Offset X",
        ["TmDiagramProperties_LabelOffsetY"] = "Label Offset Y",
        ["TmDiagramProperties_ArcSize"] = "Corner Radius",
        ["TmDiagramProperties_Style"] = "Style",
        ["TmDiagramProperties_ZIndex"] = "Z-Index",
        ["TmDiagramProperties_Empty"] = "Nothing selected",
        ["TmDiagramProperties_ReadOnly"] = "Read-only mode",
        ["TmDiagramProperties_Routing"] = "Routing",
        ["TmDiagramProperties_Routing_Straight"] = "Straight",
        ["TmDiagramProperties_Routing_Orthogonal"] = "Orthogonal",
        ["TmDiagramProperties_Routing_Curved"] = "Curved",
        ["TmDiagramProperties_Routing_Isometric"] = "Isometric",
        ["TmDiagramProperties_Routing_EntityRelation"] = "Entity Relation",
        ["TmDiagramProperties_CubicBezier"] = "Cubic BÃ©zier",
        ["TmDiagramProperties_ConnectorType"] = "Connector type",
        ["TmDiagramProperties_ConnectorType_Association"] = "Association",
        ["TmDiagramProperties_ConnectorType_Dependency"] = "Dependency",
        ["TmDiagramProperties_ConnectorType_Inheritance"] = "Inheritance",
        ["TmDiagramProperties_ConnectorType_Composition"] = "Composition",
        ["TmDiagramProperties_ConnectorType_Aggregation"] = "Aggregation",
        ["TmDiagramProperties_EdgePreset"] = "Preset",
        ["TmDiagramProperties_Preset_Custom"] = "Custom",
        ["TmDiagramProperties_Preset_ArrowRight"] = "â†’ Arrow",
        ["TmDiagramProperties_Preset_Line"] = "â”€ Line",
        ["TmDiagramProperties_Preset_DoubleArrow"] = "â‡’ Double Arrow",
        ["TmDiagramProperties_Preset_CrossArrow"] = "âŠ£â†’ Cross Arrow",
        ["TmDiagramProperties_Preset_DoubleLine"] = "â• Double Line",
        ["TmDiagramProperties_Preset_ThickDoubleLine"] = "â•â• Thick Double",
        ["TmDiagramProperties_Preset_Dashed"] = "- - Dashed",
        ["TmDiagramProperties_EdgeShape"] = "Connection",
        ["TmDiagramProperties_EdgeShape_Connector"] = "Connector",
        ["TmDiagramProperties_EdgeShape_Link"] = "Double Line",
        ["TmDiagramProperties_EdgeShape_FilledEdge"] = "Filled Bar",
        ["TmDiagramProperties_EdgeShape_Pipe"] = "Pipe",
        ["TmDiagramProperties_EdgeShape_Wire"] = "Wire",
        ["TmDiagramProperties_FillArrow"] = "Fill",
        ["TmDiagram_EnableMathJax"] = "MathJax",
        ["TmDiagramProperties_Link"] = "Link",
        ["TmDiagramProperties_LinkPlaceholder"] = "https://...",
        ["TmDiagramProperties_LinkType_None"] = "None",
        ["TmDiagramProperties_ExternalUrl"] = "External URL",
        ["TmDiagramProperties_PageLink"] = "Page Link",
        ["TmDiagramProperties_Scale"] = "Scale",
        ["TmDiagramProperties_PlaceholdersHint"] = "Placeholders: %page%, %pagenumber%, %totalpages%, %date%",
        ["TmDiagramCanvas_AriaLabel"] = "Diagram canvas",
        ["TmDiagram_SearchPlaceholder"] = "Search diagram...",
        ["TmDiagram_SearchResults"] = "{0} of {1}",
        ["TmDiagram_SearchNoResults"] = "No results",
        ["TmDiagram_SearchPrevious"] = "Previous result",
        ["TmDiagram_SearchNext"] = "Next result",
        ["TmDiagram_SearchClose"] = "Close search",
        ["TmDiagram_SearchAllPages"] = "All pages",
        ["TmDiagram_ReplacePlaceholder"] = "Replace with...",
        ["TmDiagram_Replace"] = "Replace",
        ["TmDiagram_ReplaceAll"] = "Replace All",
        ["TmDiagram_UseRegex"] = "Use regular expressions",
        ["TmDiagram_RegexError"] = "Invalid regex: {0}",
        ["TmDiagram_ReplaceNoMatches"] = "No replaceable matches",
        ["TmDiagramEditor_RotateHandleLabel"] = "Rotate",
        ["TmDiagramEditor_ConnectArrowTop"] = "Connect top",
        ["TmDiagramEditor_ConnectArrowRight"] = "Connect right",
        ["TmDiagramEditor_ConnectArrowBottom"] = "Connect bottom",
        ["TmDiagramEditor_ConnectArrowLeft"] = "Connect left",
        ["TmDiagramEditor_SelectStencilTitle"] = "Select shape to connect",
        ["TmDiagramEditor_AddPage"] = "Add page",
        ["TmDiagramEditor_ClosePage"] = "Close page \"{0}\"",
        ["TmDiagramEditor_PageName"] = "Page",
        ["TmDiagramEditor_DuplicatePage"] = "Duplicate page",
        ["TmDiagramEditor_CopySuffix"] = "copy",

        ["TmDiagramEditor_ToggleRulers"] = "PÅ™epnout pravÃ­tka",
        ["TmDiagramEditor_RulerUnitLabel"] = "Jednotka pravÃ­tka",

        // TmPivotTable
        ["TmPivotTable_Loading"] = "Loading pivot data...",
        ["TmPivotTable_NoData"] = "No data to display",
        ["TmPivotTable_AvailableFields"] = "Available Fields",
        ["TmPivotTable_RowFields"] = "Row Fields",
        ["TmPivotTable_ColumnFields"] = "Column Fields",
        ["TmPivotTable_ValueFields"] = "Values",
        ["TmPivotTable_FilterFields"] = "Filters",
        ["TmPivotTable_Apply"] = "Apply",
        ["TmPivotTable_Reset"] = "Reset",
        ["TmPivotTable_ClearAll"] = "Clear All",
        ["TmPivotTable_DragHint"] = "Drag fields to areas",
        ["TmPivotTable_ValueSettings"] = "Value Settings",
        ["TmPivotTable_Aggregation_Sum"] = "Sum",
        ["TmPivotTable_Aggregation_Count"] = "Count",
        ["TmPivotTable_Aggregation_Average"] = "Average",
        ["TmPivotTable_Aggregation_Min"] = "Min",
        ["TmPivotTable_Aggregation_Max"] = "Max",
        ["TmPivotTable_SelectAll"] = "Select All",
        ["TmPivotTable_Clear"] = "Clear",
        ["TmPivotTable_Cancel"] = "Cancel",
        ["TmPivotTable_Format"] = "Format",
        ["TmPivotTable_Format_Custom"] = "Custom",
        ["TmPivotTable_Format_Number"] = "Number",
        ["TmPivotTable_Format_Currency"] = "Currency",
        ["TmPivotTable_Format_Percent"] = "Percent",
        ["TmPivotTable_Format_Date"] = "Date",
        ["TmPivotTable_Format_None"] = "None",
        ["TmPivotTable_SortMenu"] = "Sort options",
        ["TmPivotTable_Sort_Ascending"] = "Sort Ascending",
        ["TmPivotTable_Sort_Descending"] = "Sort Descending",
        ["TmPivotTable_Sort_AscendingByAggregate"] = "Sort Ascending by Total",
        ["TmPivotTable_Sort_DescendingByAggregate"] = "Sort Descending by Total",
        ["TmPivotTable_Sort_Clear"] = "Clear Sort",
        ["TmPivotTable_RowShort"] = "Row",
        ["TmPivotTable_ColumnShort"] = "Col",
        ["TmPivotTable_DataShort"] = "Val",
        ["TmPivotTable_FilterShort"] = "Flt",
        ["TmPivotTable_FieldActions"] = "Field actions",
        ["TmPivotTable_AddToRow"] = "Add to Row Fields",
        ["TmPivotTable_AddToColumn"] = "Add to Column Fields",
        ["TmPivotTable_AddToValue"] = "Add to Values",
        ["TmPivotTable_AddToFilter"] = "Add to Filters",
        ["TmPivotTable_RemoveFromAll"] = "Remove from all areas",

        // TmWireframe
        ["TmWireframe_ToolbarAriaLabel"] = "Wireframe editor toolbar",
        ["TmWireframe_UntitledPlaceholder"] = "Untitled wireframe",
        ["TmWireframe_DocumentTitleLabel"] = "Document title",
        ["TmWireframe_SelectTool"] = "Select tool (V)",
        ["TmWireframe_PanTool"] = "Pan tool (H)",
        ["TmWireframe_PanToolHint"] = "Pan tool (H) â€” or hold Space",
        ["TmWireframe_Undo"] = "Undo",
        ["TmWireframe_Redo"] = "Redo",
        ["TmWireframe_ZoomOut"] = "Zoom out",
        ["TmWireframe_ZoomIn"] = "Zoom in",
        ["TmWireframe_FitToView"] = "Fit to view",
        ["TmWireframe_CanvasWidth"] = "Canvas width",
        ["TmWireframe_CanvasHeight"] = "Canvas height",
        ["TmWireframe_Apply"] = "Apply",
        ["TmWireframe_Cancel"] = "Cancel",
        ["TmWireframe_ChangeCanvasSize"] = "Change canvas size",
        ["TmWireframe_Export"] = "Export",
        ["TmWireframe_ExportJson"] = "Export JSON",
        ["TmWireframe_ExportSvg"] = "Export SVG",
        ["TmWireframe_ExportPng"] = "Export PNG",
        ["TmWireframe_ExportPdf"] = "Export PDF",
        ["TmWireframe_ExportError"] = "Export failed: {0}.",
        ["TmWireframeExportDialog_Title"] = "Export Wireframe",
        ["TmWireframeExportDialog_FileName"] = "File name",
        ["TmWireframeExportDialog_FileNamePlaceholder"] = "wireframe",
        ["TmWireframeExportDialog_Format"] = "Format",
        ["TmWireframeExportDialog_Scale"] = "Scale",
        ["TmWireframeExportDialog_IncludeBackground"] = "Include background",
        ["TmWireframeExportDialog_ExportButton"] = "Export",
        ["TmWireframe_ImportJson"] = "Import JSON",
        ["TmWireframe_SwitchToEditMode"] = "Switch to edit mode",
        ["TmWireframe_SwitchToReadOnlyMode"] = "Switch to read-only mode",
        ["TmWireframe_ReadOnly"] = "Read-only",
        ["TmWireframe_Edit"] = "Edit",
        ["TmWireframe_ShowToolbox"] = "Show toolbox",
        ["TmWireframe_HideToolbox"] = "Hide toolbox",
        ["TmWireframe_ToggleToolbox"] = "Toggle toolbox",
        ["TmWireframe_ShowProperties"] = "Show properties panel",
        ["TmWireframe_HideProperties"] = "Hide properties panel",
        ["TmWireframe_ToggleProperties"] = "Toggle properties panel",
        ["TmWireframe_DismissError"] = "Dismiss error",
        ["TmWireframe_DefaultTitle"] = "Untitled wireframe",
        ["TmWireframe_ExportFilename"] = "wireframe",
        ["TmWireframe_ImportError_InvalidJson"] = "Failed to import: the file is not a valid wireframe JSON.",
        ["TmWireframe_ImportError_Generic"] = "Failed to import: {0}.",
        ["TmWireframeToolbox_SearchPlaceholder"] = "Search componentsâ€¦",
        ["TmWireframeToolbox_ClearSearch"] = "Clear search",
        ["TmWireframeToolbox_FilterAll"] = "All",
        ["TmWireframeToolbox_FilterBuiltIn"] = "Built-in",
        ["TmWireframeToolbox_FilterCustom"] = "Custom",
        ["TmWireframeToolbox_NoComponentsMatch"] = "No components match \"{0}\"",
        ["TmWireframeToolbox_CustomComponentTooltip"] = "Custom component",
        ["TmWireframeToolbox_DragOntoCanvas"] = "Drag {0} onto canvas",
        ["TmWireframeProps_NoSelectionTitle"] = "No selection",
        ["TmWireframeProps_NoSelectionHint"] = "Select an element on the canvas to edit its properties.",
        ["TmWireframeProps_ElementsCount"] = "{0} elements",
        ["TmWireframeProps_MixedTypes"] = "Mixed types",
        ["TmWireframeProps_SectionElement"] = "Element",
        ["TmWireframeProps_SectionLayout"] = "Layout",
        ["TmWireframeProps_SectionGeneral"] = "General",
        ["TmWireframeProps_Type"] = "Type",
        ["TmWireframeProps_Types"] = "Types",
        ["TmWireframeProps_ZIndex"] = "Z-Index",
        ["TmWireframeProps_X"] = "X",
        ["TmWireframeProps_Y"] = "Y",
        ["TmWireframeProps_W"] = "W",
        ["TmWireframeProps_H"] = "H",
        ["TmWireframeProps_MixedPlaceholder"] = "Mixed",
        ["TmWireframeProps_CommaSeparatedPlaceholder"] = "comma, separated",
        ["TmWireframeProps_ValidationRegexError"] = "Value does not match pattern: {0}",
        ["TmWireframeProps_CommandChangeZIndex"] = "Change Z-Index",
        ["TmWireframeCanvas_AriaLabel"] = "Wireframe canvas",
        ["TmWireframeCanvas_UnknownComponent"] = "Unknown: {0}",
        ["TmWireframeProps_CatContent"] = "Content",
        ["TmWireframeProps_CatAppearance"] = "Appearance",
        ["TmWireframeProps_CatBehavior"] = "Behavior",
        ["TmWireframeProps_CatState"] = "State",

        ["TmWireframe_LayersToggle"] = "Toggle layers panel",
        ["TmWireframe_LayersTitle"] = "Layers",
        ["TmWireframe_AddLayer"] = "Add layer",
        ["TmWireframe_SetActiveLayer"] = "Set as active layer",
        ["TmWireframe_HideLayer"] = "Hide layer",
        ["TmWireframe_ShowLayer"] = "Show layer",
        ["TmWireframe_UnlockLayer"] = "Unlock layer",
        ["TmWireframe_LockLayer"] = "Lock layer",
        ["TmWireframe_DoubleClickToEdit"] = "Double-click to edit name",
        ["TmWireframe_DeleteLayer"] = "Delete layer",
        ["TmWireframe_MoveToLayer"] = "Move to layer",
        ["TmWireframe_SelectLayer"] = "Select layer",
        ["TmWireframe_Layer"] = "Layer",
        ["TmWireframeProps_Layer"] = "Layer",
        ["TmWireframe_ShowRulers"] = "Show rulers",
        ["TmWireframe_HorizontalRuler"] = "Horizontal ruler",
        ["TmWireframe_VerticalRuler"] = "Vertical ruler",

        // TmSpreadsheet
        ["TmSpreadsheet_NoSheet"] = "No sheet available",
        ["TmSpreadsheet_Name"] = "Spreadsheet",
        ["TmSpreadsheet_CellReference"] = "Cell reference",
        ["TmSpreadsheet_FormulaBarPlaceholder"] = "Enter formula or value...",
        ["TmSpreadsheet_SheetTab"] = "Sheet",
        ["TmSpreadsheet_AddSheet"] = "Add sheet",
        ["TmSpreadsheet_RenameSheet"] = "Rename sheet",
        ["TmSpreadsheet_DeleteSheet"] = "Delete sheet",
        ["TmSpreadsheet_DeleteSheetConfirm"] = "Are you sure you want to delete this sheet?",
        ["TmSpreadsheet_GridLines"] = "Grid lines",
        ["TmSpreadsheet_MergeCells"] = "Merge cells",
        ["TmSpreadsheet_Undo"] = "Undo",
        ["TmSpreadsheet_Redo"] = "Redo",
        ["TmSpreadsheet_Copy"] = "Copy",
        ["TmSpreadsheet_Cut"] = "Cut",
        ["TmSpreadsheet_Paste"] = "Paste",
        ["TmSpreadsheet_InsertRow"] = "Insert row",
        ["TmSpreadsheet_DeleteRow"] = "Delete row",
        ["TmSpreadsheet_InsertColumn"] = "Insert column",
        ["TmSpreadsheet_DeleteColumn"] = "Delete column",
        ["TmSpreadsheet_Bold"] = "Bold",
        ["TmSpreadsheet_Italic"] = "Italic",
        ["TmSpreadsheet_Underline"] = "Underline",
        ["TmSpreadsheet_TextColor"] = "Text color",
        ["TmSpreadsheet_BackgroundColor"] = "Background color",
        ["TmSpreadsheet_AlignLeft"] = "Align left",
        ["TmSpreadsheet_AlignCenter"] = "Align center",
        ["TmSpreadsheet_AlignRight"] = "Align right",
        ["TmSpreadsheet_NumberFormat"] = "Number format",
        ["TmSpreadsheet_IncreaseDecimals"] = "Increase decimal places",
        ["TmSpreadsheet_DecreaseDecimals"] = "Decrease decimal places",
        ["TmSpreadsheet_Open"] = "Open file",
        ["TmSpreadsheet_Download"] = "Download",
        ["TmSpreadsheet_TabHome"] = "Home",
        ["TmSpreadsheet_TabInsert"] = "Insert",
        ["TmSpreadsheet_TabView"] = "View",
        ["TmSpreadsheet_TabFile"] = "File",
        ["TmSpreadsheet_InsertLink"] = "Insert link",
        ["TmSpreadsheet_InsertImage"] = "Insert image",
        ["TmSpreadsheet_LinkUrl"] = "URL",
        ["TmSpreadsheet_LinkText"] = "Display text",
        ["TmSpreadsheet_LinkTextPlaceholder"] = "Click here",
        ["TmSpreadsheet_ImageUrl"] = "Image URL",
    });

    private static MockTmLocalizer BuildCzechLocalizer() => new(new Dictionary<string, string>
    {
        // Shared
        ["Tm_Loading"]     = "NaÄÃ­tÃ¡nÃ­...",
        ["Tm_Close"]       = "ZavÅ™Ã­t",
        ["Tm_Cancel"]      = "ZruÅ¡it",
        ["Tm_Save"]        = "UloÅ¾it",
        ["Tm_Delete"]      = "Smazat",
        ["Tm_Confirm"]     = "Potvrdit",
        ["Tm_NoResults"]   = "Å½Ã¡dnÃ© vÃ½sledky",
        ["Tm_Error"]       = "DoÅ¡lo k chybÄ›",
        ["Tm_Retry"]       = "Zkusit znovu",
        ["Tm_Search"]      = "Hledat",
        ["Tm_Clear"]       = "Vymazat",
        ["Tm_Select"]      = "Vybrat",
        ["Tm_SelectAll"]   = "Vybrat vÅ¡e",
        ["Tm_DeselectAll"] = "ZruÅ¡it vÃ½bÄ›r",
        ["Tm_Edit"]        = "Upravit",
        ["Tm_Add"]         = "PÅ™idat",
        ["Tm_Remove"]      = "Odebrat",
        ["Tm_Apply"]       = "PouÅ¾Ã­t",
        ["Tm_Reset"]       = "Obnovit",
        ["Tm_Previous"]    = "PÅ™edchozÃ­",
        ["Tm_Next"]        = "DalÅ¡Ã­",
        ["Tm_Download"]    = "StÃ¡hnout",
        ["Tm_Upload"]      = "NahrÃ¡t",
        ["Tm_Create"]      = "VytvoÅ™it",
        ["Tm_Optional"]    = "VolitelnÃ©",
        ["Tm_Required"]    = "PovinnÃ©",
        ["Tm_Yes"]         = "Ano",
        ["Tm_No"]          = "Ne",

        // TmButton
        ["TmButton_Loading"] = "NaÄÃ­tÃ¡nÃ­",

        // TmSearchInput
        ["TmSearchInput_Placeholder"] = "Hledat...",
        ["TmSearchInput_Clear"]       = "Vymazat hledÃ¡nÃ­",

        // TmEmptyState
        ["TmEmptyState_DefaultTitle"] = "Å½Ã¡dnÃ¡ data",

        // TmDataTable
        ["TmDataTable_NoResults"]          = "Å½Ã¡dnÃ© vÃ½sledky",
        ["TmDataTable_Loading"]            = "NaÄÃ­tÃ¡nÃ­ dat...",
        ["TmDataTable_PageSize"]           = "PoloÅ¾ek na strÃ¡nku",
        ["TmDataTable_Pagination"]         = "{0}â€“{1} z {2}",
        ["TmDataTable_SelectAll"]          = "Vybrat vÅ¡echny Å™Ã¡dky",
        ["TmDataTable_DeselectAll"]        = "ZruÅ¡it vÃ½bÄ›r",
        ["TmDataTable_ColumnPicker"]       = "Vybrat sloupce",
        ["TmDataTable_ResetColumns"]       = "Obnovit vÃ½chozÃ­",
        ["TmDataTable_SaveView"]           = "UloÅ¾it pohled",
        ["TmDataTable_ManageViews"]        = "Spravovat pohledy",
        ["TmDataTable_DefaultView"]        = "VÃ½chozÃ­ pohled",
        ["TmDataTable_Filter"]             = "Filtr",
        ["TmDataTable_ClearFilters"]       = "ZruÅ¡it filtry",
        ["TmDataTable_SortAscending"]      = "Å˜adit vzestupnÄ›",
        ["TmDataTable_SortDescending"]     = "Å˜adit sestupnÄ›",
        ["TmDataTable_BulkActions"]        = "{0} vybrÃ¡no",
        ["TmDataTable_DeleteSelected"]     = "Smazat vybranÃ©",
        ["TmDataTable_EditInline"]         = "Upravit",
        ["TmDataTable_SaveInline"]         = "UloÅ¾it zmÄ›ny",
        ["TmDataTable_CancelInline"]       = "ZruÅ¡it Ãºpravy",
        ["TmDataTable_FirstPage"]          = "PrvnÃ­ strÃ¡nka",
        ["TmDataTable_LastPage"]           = "PoslednÃ­ strÃ¡nka",
        ["TmDataTable_ViewName"]           = "NÃ¡zev pohledu",
        ["TmDataTable_ViewNamePlaceholder"]= "Zadejte nÃ¡zev pohledu...",
        ["TmDataTable_DeleteView"]         = "Smazat pohled",

        // TmFilterableDropdown
        ["TmFilterableDropdown_Search"]        = "Hledat...",
        ["TmFilterableDropdown_NoResults"]     = "Å½Ã¡dnÃ© vÃ½sledky",
        ["TmFilterableDropdown_Loading"]       = "NaÄÃ­tÃ¡nÃ­...",
        ["TmFilterableDropdown_Error"]         = "NepodaÅ™ilo se naÄÃ­st moÅ¾nosti",
        ["TmFilterableDropdown_Retry"]         = "Zkusit znovu",
        ["TmFilterableDropdown_CreateNew"]     = "VytvoÅ™it \"{0}\"",
        ["TmFilterableDropdown_ClearSelection"]= "ZruÅ¡it vÃ½bÄ›r",
        ["TmFilterableDropdown_Placeholder"]   = "Vyberte moÅ¾nost...",

        // TmFileDropZone
        ["TmFileDropZone_DragDrop"]      = "PÅ™etÃ¡hnÄ›te soubory sem",
        ["TmFileDropZone_Or"]            = "nebo",
        ["TmFileDropZone_Browse"]        = "Vybrat soubory",
        ["TmFileDropZone_Uploading"]     = "NahrÃ¡vÃ¡nÃ­...",
        ["TmFileDropZone_Remove"]        = "Odebrat soubor",
        ["TmFileDropZone_MaxSize"]       = "MaximÃ¡lnÃ­ velikost: {0}",
        ["TmFileDropZone_AcceptedTypes"] = "PovolenÃ© typy: {0}",

        // TmTimeline
        ["TmTimeline_NoEntries"]  = "Å½Ã¡dnÃ¡ aktivita",
        ["TmTimeline_Internal"]   = "InternÃ­",
        ["TmTimeline_JustNow"]    = "PrÃ¡vÄ› teÄ",
        ["TmTimeline_MinutesAgo"] = "pÅ™ed {0} min",
        ["TmTimeline_HoursAgo"]   = "pÅ™ed {0} h",
        ["TmTimeline_DaysAgo"]    = "pÅ™ed {0} dny",
        ["TmTimeline_DateFormat"] = "d. M. yyyy",

        // TmTreeView
        ["TmTreeView_Search"]    = "Hledat...",
        ["TmTreeView_NoResults"] = "Å½Ã¡dnÃ© poloÅ¾ky",
        ["TmTreeView_Loading"]   = "NaÄÃ­tÃ¡nÃ­...",
        ["TmTreeView_Expand"]    = "Rozbalit",
        ["TmTreeView_Collapse"]  = "Sbalit",

        // TmTagPicker
        ["TmTagPicker_Search"]    = "Hledat Å¡tÃ­tky...",
        ["TmTagPicker_CreateNew"] = "VytvoÅ™it \"{0}\"",
        ["TmTagPicker_NoTags"]    = "Å½Ã¡dnÃ© Å¡tÃ­tky",
        ["TmTagPicker_AddTag"]    = "PÅ™idat Å¡tÃ­tek",

        // TmCommandPalette
        ["TmCommandPalette_Placeholder"] = "Zadejte pÅ™Ã­kaz nebo hledejte...",
        ["TmCommandPalette_NoResults"]   = "Å½Ã¡dnÃ© pÅ™Ã­kazy nenalezeny",

        // TmStepper
        ["TmStepper_Step"]      = "Krok {0} z {1}",
        ["TmStepper_Completed"] = "DokonÄeno",

        // TmAvatar
        ["TmAvatar_ImageAlt"] = "Avatar uÅ¾ivatele",

        // TmNotificationBell
        ["TmNotificationBell_AriaLabel"]       = "OznÃ¡menÃ­",
        ["TmNotificationBell_NewCount"]        = "{0} novÃ½ch oznÃ¡menÃ­",
        ["TmNotificationBell_NoNotifications"] = "Å½Ã¡dnÃ¡ oznÃ¡menÃ­",
        ["TmNotificationBell_MarkAllRead"]     = "OznaÄit vÅ¡e jako pÅ™eÄtenÃ©",

        // TmImageGallery
        ["TmImageGallery_PreviousImage"] = "PÅ™edchozÃ­ obrÃ¡zek",
        ["TmImageGallery_NextImage"]     = "DalÅ¡Ã­ obrÃ¡zek",
        ["TmImageGallery_Close"]         = "ZavÅ™Ã­t galerii",
        ["TmImageGallery_Counter"]       = "{0} z {1}",
        ["TmImageGallery_LoadingImage"]  = "NaÄÃ­tÃ¡nÃ­ obrÃ¡zku...",
        ["TmImageGallery_ErrorLoading"]  = "ObrÃ¡zek se nepodaÅ™ilo naÄÃ­st",
        ["TmImageGallery_ZoomIn"]        = "PÅ™iblÃ­Å¾it",
        ["TmImageGallery_ZoomOut"]       = "OddÃ¡lit",
        ["TmImageGallery_Download"]      = "StÃ¡hnout obrÃ¡zek",
        ["TmImageGallery_Delete"]        = "Smazat obrÃ¡zek",
        ["TmImageGallery_NoImages"]      = "Å½Ã¡dnÃ© obrÃ¡zky",
        ["TmImageGallery_UploadImages"]  = "NahrÃ¡t obrÃ¡zky",
        ["TmImageGallery_GridView"]      = "MÅ™Ã­Å¾ka",
        ["TmImageGallery_GalleryView"]   = "Galerie",

        // TmLayout
        ["TmSidebar_CollapseMenu"]     = "Sbalit menu",
        ["TmSidebar_ExpandMenu"]       = "Rozbalit menu",
        ["TmTopBar_OpenSearch"]        = "Hledat (Ctrl+K)",
        ["TmTopBar_OpenNotifications"] = "OtevÅ™Ã­t oznÃ¡menÃ­",
        ["TmTopBar_OpenUserMenu"]      = "OtevÅ™Ã­t nabÃ­dku uÅ¾ivatele",

        // TmCheckbox
        ["TmCheckbox_Indeterminate"] = "ÄŒÃ¡steÄnÄ› vybrÃ¡no",

        // Validation
        ["TmValidation_Required"] = "Toto pole je povinnÃ©",
        ["TmValidation_Invalid"]  = "Toto pole obsahuje neplatnou hodnotu",

        // TmTimePicker
        ["TmTimePicker_Hours"]              = "Hodiny",
        ["TmTimePicker_Minutes"]            = "Minuty",
        ["TmTimePicker_Seconds"]            = "Sekundy",
        ["TmTimePicker_Placeholder"]        = "HH:mm",
        ["TmTimePicker_PlaceholderSeconds"] = "HH:mm:ss",
        ["TmTimePicker_Clear"]              = "Vymazat Äas",

        // TmDatePicker
        ["TmDatePicker_Placeholder"]   = "dd.MM.yyyy",
        ["TmDatePicker_Clear"]         = "Vymazat datum",
        ["TmDatePicker_Today"]         = "Dnes",
        ["TmDatePicker_PreviousMonth"] = "PÅ™edchozÃ­ mÄ›sÃ­c",
        ["TmDatePicker_NextMonth"]     = "DalÅ¡Ã­ mÄ›sÃ­c",

        // TmDateTimePicker
        ["TmDateTimePicker_Placeholder"] = "dd.MM.yyyy HH:mm",
        ["TmDateTimePicker_Clear"]       = "Vymazat",

        // TmTimeRangePicker
        ["TmTimeRangePicker_From"]         = "Od",
        ["TmTimeRangePicker_To"]           = "Do",
        ["TmTimeRangePicker_Duration"]     = "TrvÃ¡nÃ­",
        ["TmTimeRangePicker_Swap"]         = "Prohodit",
        ["TmTimeRangePicker_InvalidRange"] = "Konec musÃ­ bÃ½t po zaÄÃ¡tku",

        // TmDateRangePicker
        ["TmDateRangePicker_From"]  = "Od",
        ["TmDateRangePicker_To"]    = "Do",
        ["TmDateRangePicker_Clear"] = "Vymazat rozsah",

        // TmDateTimeRangePicker
        ["TmDateTimeRangePicker_StartLabel"]      = "ZaÄÃ¡tek",
        ["TmDateTimeRangePicker_EndLabel"]        = "Konec",
        ["TmDateTimeRangePicker_Clear"]           = "Vymazat rozsah",
        ["TmDateTimeRangePicker_ValidationError"] = "Konec musÃ­ bÃ½t po zaÄÃ¡tku",

        // TmFilterBuilder operators
        ["TmFilter_Contains"]      = "obsahuje",
        ["TmFilter_NotContains"]   = "neobsahuje",
        ["TmFilter_Equals"]        = "rovnÃ¡ se",
        ["TmFilter_NotEquals"]     = "nerovnÃ¡ se",
        ["TmFilter_GreaterThan"]   = "vÄ›tÅ¡Ã­ neÅ¾",
        ["TmFilter_LessThan"]      = "menÅ¡Ã­ neÅ¾",
        ["TmFilter_GreaterOrEqual"]= "vÄ›tÅ¡Ã­ nebo rovno",
        ["TmFilter_LessOrEqual"]   = "menÅ¡Ã­ nebo rovno",
        ["TmFilter_Between"]       = "mezi",
        ["TmFilter_IsEmpty"]       = "je prÃ¡zdnÃ©",
        ["TmFilter_IsNotEmpty"]    = "nenÃ­ prÃ¡zdnÃ©",
        ["TmFilter_In"]            = "v",
        ["TmFilter_NotIn"]         = "nenÃ­ v",

        // TmMultiViewList
        ["TmMvl_TableView"]   = "Tabulka",
        ["TmMvl_CardView"]    = "Karty",
        ["TmMvl_ListView"]    = "Seznam",
        ["TmMvl_ColTitle"]    = "NÃ¡zev",
        ["TmMvl_ColSubTitle"] = "Popis",
        ["TmMvl_ColStatus"]   = "Stav",
        ["TmMvl_ColDate"]     = "Datum",

        // TmValidationSummary
        ["TmValidationSummary_Title"] = "PÅ™i odesÃ­lÃ¡nÃ­ formulÃ¡Å™e doÅ¡lo k chybÃ¡m",

        // TmPasswordStrengthIndicator
        ["TmPasswordStrength_VeryWeak"]                = "Velmi slabÃ©",
        ["TmPasswordStrength_Weak"]                    = "SlabÃ©",
        ["TmPasswordStrength_Medium"]                  = "StÅ™ednÃ­",
        ["TmPasswordStrength_Strong"]                  = "SilnÃ©",
        ["TmPasswordStrength_VeryStrong"]              = "Velmi silnÃ©",
        ["TmPasswordStrength_HintUseAtLeast8Chars"]    = "PouÅ¾ijte alespoÅˆ 8 znakÅ¯",
        ["TmPasswordStrength_HintAddLetters"]          = "PÅ™idejte pÃ­smena",
        ["TmPasswordStrength_HintAddNumbers"]          = "PÅ™idejte ÄÃ­sla",
        ["TmPasswordStrength_HintAddSpecialChars"]     = "PÅ™idejte speciÃ¡lnÃ­ znaky",
        ["TmPasswordStrength_HintAddUppercase"]        = "PÅ™idejte velkÃ¡ pÃ­smena",
        ["TmPasswordStrength_HintAddLowercase"]        = "PÅ™idejte malÃ¡ pÃ­smena",
        ["TmPasswordStrength_HintMakeItLonger"]        = "ProdluÅ¾te heslo",
        ["TmPasswordStrength_HintAvoidCommonPatterns"] = "VyhnÄ›te se bÄ›Å¾nÃ½m vzorÅ¯m",
        ["TmPasswordStrength_HintAvoidCommonWords"]    = "VyhnÄ›te se bÄ›Å¾nÃ½m slovÅ¯m",
        ["TmPasswordStrength_HintExcellent"]           = "VynikajÃ­cÃ­ heslo!",

        // TmToast
        ["TmToast_Close"] = "ZavÅ™Ã­t",

        // TmAlert
        ["TmAlert_Dismiss"] = "ZavÅ™Ã­t",

        // TmDrawer
        ["TmDrawer_Close"] = "ZavÅ™Ã­t panel",

        // TmBulkActionBar
        ["TmBulkAction_Toolbar"] = "HromadnÃ© akce",
        ["TmBulkAction_Selected"] = "vybrÃ¡no",
        ["TmBulkAction_ClearSelection"] = "ZruÅ¡it vÃ½bÄ›r",

        // TmDataTable Grouping
        ["TmDataTable_GroupDropPlaceholder"] = "PÅ™etÃ¡hnÄ›te zÃ¡hlavÃ­ sloupce pro seskupenÃ­",
        ["TmDataTable_ExpandAll"] = "Rozbalit vÅ¡e",
        ["TmDataTable_CollapseAll"] = "Sbalit vÅ¡e",
        ["TmDataTable_GroupCount"] = "{0} poloÅ¾ek",
        ["TmDataTable_SearchPlaceholder"] = "Hledat...",
        ["TmDataTable_ShowingItems"] = "{0}â€“{1} z {2}",
        ["TmDataTable_CurrentViewName"] = "AktuÃ¡lnÃ­",

        // TmMultiViewList Grouping
        ["TmMvl_GroupBy"] = "Seskupit podle",
        ["TmMvl_GroupNone"] = "Bez seskupenÃ­",

        // TmViewManager Grouping
        ["TmViewManager_Grouping"] = "SeskupovÃ¡nÃ­",
        ["TmViewManager_GroupByColumns"] = "Seskupit podle sloupcÅ¯",

        // TmInlineEdit
        ["TmInlineEdit_Placeholder"] = "KliknÄ›te pro Ãºpravu",

        // TmRichEditor - Tokens
        ["TmRichEditor_Token"]          = "VloÅ¾it promÄ›nnou",
        ["TmRichEditor_TokenEmpty"]     = "Å½Ã¡dnÃ© promÄ›nnÃ© nenalezeny",
        ["TmRichEditor_TokenCreateNew"] = "VytvoÅ™it novou promÄ›nnou...",
        ["TmRichEditor_TokenSearch"]    = "Hledat promÄ›nnÃ©...",
        ["TmRichEditor_MentionEmpty"]   = "UÅ¾ivatelÃ© nenalezeni",
        ["TmRichEditor_Bold"]           = "TuÄnÃ©",
        ["TmRichEditor_Italic"]         = "KurzÃ­va",
        ["TmRichEditor_Underline"]      = "PodtrÅ¾enÃ©",
        ["TmRichEditor_Link"]           = "Odkaz",
        ["TmRichEditor_TaskList"]       = "Seznam ÃºkolÅ¯",
        ["TmRichEditor_Emoji"]          = "Emoji",
        ["TmRichEditor_UnorderedList"]  = "OdrÃ¡Å¾kovÃ½ seznam",
        ["TmRichEditor_OrderedList"]    = "ÄŒÃ­slovanÃ½ seznam",
        ["TmRichEditor_Undo"]          = "ZpÄ›t",
        ["TmRichEditor_Redo"]          = "Znovu",
        ["TmRichEditor_Heading1"]      = "Nadpis 1",
        ["TmRichEditor_Heading2"]      = "Nadpis 2",
        ["TmRichEditor_Heading3"]      = "Nadpis 3",
        ["TmRichEditor_Heading4"]      = "Nadpis 4",
        ["TmRichEditor_Strikethrough"] = "PÅ™eÅ¡krtnutÃ©",
        ["TmRichEditor_Subscript"]     = "DolnÃ­ index",
        ["TmRichEditor_Superscript"]   = "HornÃ­ index",
        ["TmRichEditor_Indent"]        = "Odsadit",
        ["TmRichEditor_Outdent"]       = "PÅ™edsadit",
        ["TmRichEditor_Code"]          = "Blok kÃ³du",
        ["TmRichEditor_Blockquote"]    = "Citace",
        ["TmRichEditor_HorizontalRule"]= "VodorovnÃ¡ ÄÃ¡ra",
        ["TmRichEditor_TextColor"]     = "Barva textu",
        ["TmRichEditor_Highlight"]     = "ZvÃ½raznÄ›nÃ­",
        ["TmRichEditor_Image"]         = "ObrÃ¡zek",
        ["TmRichEditor_Table"]         = "Tabulka",
        ["TmRichEditor_Video"]         = "Video",
        ["TmRichEditor_RemoveFormat"]  = "Odstranit formÃ¡tovÃ¡nÃ­",

        // TmDashboard
        ["TmDashboard_Edit"]                  = "Upravit",
        ["TmDashboard_EditMode"]              = "ReÅ¾im Ãºprav",
        ["TmDashboard_CancelEdit"]            = "ZruÅ¡it",
        ["TmDashboard_SaveChanges"]           = "UloÅ¾it zmÄ›ny",
        ["TmDashboard_AddWidget"]             = "PÅ™idat widget",
        ["TmDashboard_AddWidgets"]            = "PÅ™idat widgety",
        ["TmDashboard_Dashboards"]            = "Dashboardy",
        ["TmDashboard_MyDashboards"]          = "Moje dashboardy",
        ["TmDashboard_CreateNewDashboard"]    = "VytvoÅ™it novÃ½ dashboard",
        ["TmDashboard_DashboardName"]         = "NÃ¡zev dashboardu",
        ["TmDashboard_DefaultDashboard"]      = "VÃ½chozÃ­",
        ["TmDashboard_SetAsDefault"]          = "Nastavit jako vÃ½chozÃ­",
        ["TmDashboard_Delete"]                = "Smazat",
        ["TmDashboard_DeleteDashboard"]       = "Smazat dashboard",
        ["TmDashboard_DeleteDashboardConfirm"]= "Opravdu chcete smazat tento dashboard?",
        ["TmDashboard_NoWidgets"]             = "ZatÃ­m nebyly pÅ™idÃ¡ny Å¾Ã¡dnÃ© widgety",

        // TmWireframe
        ["TmDiagramEditor_AddPage"] = "PÅ™idat strÃ¡nku",
        ["TmDiagramEditor_ClosePage"] = "ZavÅ™Ã­t strÃ¡nku \"{0}\"",
        ["TmDiagramEditor_PageName"] = "StrÃ¡nka",
        ["TmDiagramProperties_Link"] = "Odkaz",
        ["TmDiagramProperties_LinkPlaceholder"] = "https://...",
        ["TmDiagramProperties_LinkType_None"] = "Å½Ã¡dnÃ½",
        ["TmDiagramProperties_ExternalUrl"] = "ExternÃ­ URL",
        ["TmDiagramProperties_PageLink"] = "Odkaz na strÃ¡nku",
        ["TmDiagramProperties_Scale"] = "MÄ›Å™Ã­tko",
        ["TmDiagramProperties_EdgePreset"] = "PÅ™edvolba",
        ["TmDiagramProperties_Preset_Custom"] = "VlastnÃ­",
        ["TmDiagramProperties_Preset_ArrowRight"] = "â†’ Å ipka",
        ["TmDiagramProperties_Preset_Line"] = "â”€ ÄŒÃ¡ra",
        ["TmDiagramProperties_Preset_DoubleArrow"] = "â‡’ DvojitÃ¡ Å¡ipka",
        ["TmDiagramProperties_Preset_CrossArrow"] = "âŠ£â†’ KÅ™Ã­Å¾ek Å¡ipka",
        ["TmDiagramProperties_Preset_DoubleLine"] = "â• DvojitÃ¡ ÄÃ¡ra",
        ["TmDiagramProperties_Preset_ThickDoubleLine"] = "â•â• TlustÃ¡ dvojitÃ¡",
        ["TmDiagramProperties_Preset_Dashed"] = "- - ÄŒÃ¡rkovanÃ¡",
        ["TmDiagramProperties_EdgeShape"] = "Typ pÅ™ipojenÃ­",
        ["TmDiagramProperties_EdgeShape_Connector"] = "Spojnice",
        ["TmDiagramProperties_EdgeShape_Link"] = "DvojitÃ¡ ÄÃ¡ra",
        ["TmDiagramProperties_EdgeShape_FilledEdge"] = "VyplnÄ›nÃ½ pruh",
        ["TmDiagramProperties_EdgeShape_Pipe"] = "Roura",
        ["TmDiagramProperties_EdgeShape_Wire"] = "VodiÄ",
        ["TmDiagramProperties_ElbowOrientation"] = "Orientace lomenÃ© ÄÃ¡ry",
        ["TmDiagramProperties_ElbowOrientation_Auto"] = "Auto",
        ["TmDiagramProperties_ElbowOrientation_Horizontal"] = "Nejprve vodorovnÄ›",
        ["TmDiagramProperties_ElbowOrientation_Vertical"] = "Nejprve svisle",
        ["TmDiagramProperties_FillArrow"] = "Vyplnit",
        ["TmDiagramProperties_LabelOffsetX"] = "Posun popisku X",
        ["TmDiagramProperties_LabelOffsetY"] = "Posun popisku Y",
        ["TmDiagramProperties_PlaceholdersHint"] = "Placeholdery: %page%, %pagenumber%, %totalpages%, %date%",
        ["TmDiagramEditor_DuplicatePage"] = "Duplikovat strÃ¡nku",
        ["TmDiagramEditor_CopySuffix"] = "kopie",
        ["TmDiagramEditor_Cut"] = "Vyjmout",
        ["TmDiagramEditor_Copy"] = "KopÃ­rovat",
        ["TmDiagramEditor_Duplicate"] = "Duplikovat",
        ["TmDiagramEditor_Paste"] = "VloÅ¾it",
        ["TmDiagramEditor_PasteHere"] = "VloÅ¾it sem",
        ["TmDiagramEditor_SelectAll"] = "Vybrat vÅ¡e",
        ["TmDiagramEditor_Lock"] = "Uzamknout",
        ["TmDiagramEditor_Unlock"] = "Odemknout",
        ["TmDiagramEditor_Group"] = "Seskupit",
        ["TmDiagramEditor_Ungroup"] = "RozdÄ›lit skupinu",
        ["TmDiagramEditor_PasteStyle"] = "VloÅ¾it styl",
        ["TmDiagramEditor_PasteSize"] = "VloÅ¾it velikost",
        ["TmDiagramEditor_ChangeShape"] = "ZmÄ›nit tvar",
        ["TmDiagramEditor_Rectangle"] = "ObdÃ©lnÃ­k",
        ["TmDiagramEditor_Ellipse"] = "Elipsa",
        ["TmDiagramEditor_Text"] = "Text",
        ["TmDiagramEditor_Diamond"] = "KosoÄtverec",
        ["TmDiagramEditor_EditLabel"] = "Upravit popisek",
        ["TmDiagramEditor_Connector"] = "Spojnice",
        ["TmDiagramEditor_Straight"] = "PÅ™Ã­mÃ¡",
        ["TmDiagramEditor_Orthogonal"] = "OrthogonÃ¡lnÃ­",
        ["TmDiagramEditor_Curved"] = "KÅ™ivka",
        ["TmDiagramEditor_StartArrow"] = "PoÄÃ¡teÄnÃ­ Å¡ipka",
        ["TmDiagramEditor_EndArrow"] = "KoncovÃ¡ Å¡ipka",
        ["TmDiagramEditor_ArrowNone"] = "Å½Ã¡dnÃ¡",
        ["TmDiagramEditor_ArrowClassic"] = "KlasickÃ¡",
        ["TmDiagramEditor_ArrowBlock"] = "Blok",
        ["TmDiagramEditor_ArrowCrow"] = "VranÃ­ noha",
        ["TmDiagramEditor_LineStyle"] = "Styl ÄÃ¡ry",
        ["TmDiagramEditor_LineSolid"] = "SouvislÃ¡",
        ["TmDiagramEditor_LineDashed"] = "ÄŒÃ¡rkovanÃ¡",
        ["TmDiagramEditor_LineDotted"] = "TeÄkovanÃ¡",
        ["TmDiagramEditor_Insert"] = "VloÅ¾it",
        ["TmDiagramEditor_Layout"] = "RozvrÅ¾enÃ­",
        ["TmDiagramEditor_LayoutDagreTb"] = "Dagre shora dolÅ¯",
        ["TmDiagramEditor_LayoutDagreLr"] = "Dagre zleva doprava",
        ["TmDiagramEditor_LayoutTree"] = "Strom",
        ["TmDiagramEditor_LayoutForce"] = "SÃ­la",
        ["TmDiagramEditor_LayoutCircle"] = "Kruh",
        ["TmDiagramEditor_ShowGrid"] = "Zobrazit mÅ™Ã­Å¾ku",
        ["TmDiagramEditor_HideGrid"] = "SkrÃ½t mÅ™Ã­Å¾ku",
        ["TmDiagramEditor_ShowPageView"] = "Zobrazit strÃ¡nku",
        ["TmDiagramEditor_HidePageView"] = "SkrÃ½t strÃ¡nku",
        ["TmDiagramEditor_EnableSnap"] = "Zapnout pÅ™ichycenÃ­",
        ["TmDiagramEditor_DisableSnap"] = "Vypnout pÅ™ichycenÃ­",
        ["TmDiagramEditor_MergeCells"] = "SlouÄit buÅˆky",
        ["TmDiagramEditor_SplitCell"] = "RozdÄ›lit buÅˆku",
        ["TmDiagramEditor_FormatCell"] = "FormÃ¡tovat buÅˆku",
        ["TmDiagramEditor_CellWhite"] = "BÃ­lÃ¡",
        ["TmDiagramEditor_CellLightGray"] = "SvÄ›tle Å¡edÃ¡",
        ["TmDiagramEditor_CellGray"] = "Å edÃ¡",
        ["TmDiagramEditor_ImportCsv"] = "Import CSV",
        ["TmDiagramEditor_Templates"] = "Å ablony",
        ["TmDiagramTemplateGallery_Title"] = "Vyberte Å¡ablonu",
        ["TmDiagramTemplateGallery_SearchPlaceholder"] = "Hledat Å¡ablony...",
        ["TmDiagramTemplateGallery_All"] = "VÅ¡e",
        ["TmDiagramTemplateGallery_NoResults"] = "Å½Ã¡dnÃ¡ Å¡ablona neodpovÃ­dÃ¡ hledÃ¡nÃ­.",
        ["TmDiagramTemplateGallery_CreateButton"] = "VytvoÅ™it",
        ["TmDiagramCsvImportDialog_Title"] = "Import CSV do diagramu",
        ["TmDiagramCsvImportDialog_CsvLabel"] = "CSV data",
        ["TmDiagramCsvImportDialog_CsvPlaceholder"] = "VloÅ¾te CSV data zde...",
        ["TmDiagramCsvImportDialog_TypeLabel"] = "Typ diagramu",
        ["TmDiagramCsvImportDialog_MappingsTitle"] = "MapovÃ¡nÃ­ sloupcÅ¯",
        ["TmDiagramCsvImportDialog_SelectColumn"] = "Vyberte sloupec",
        ["TmDiagramCsvImportDialog_PreviewTitle"] = "NÃ¡hled (prvnÃ­ch 5 Å™Ã¡dkÅ¯)",
        ["TmDiagramCsvImportDialog_PreviewNodes"] = "Uzly: {0}",
        ["TmDiagramCsvImportDialog_PreviewEdges"] = "Hrany: {0}",
        ["TmDiagramCsvImportDialog_ImportButton"] = "Importovat",
        ["TmDiagramCsvImportDialog_ErrorEmpty"] = "Zadejte CSV data.",
        ["TmDiagramCsvImportDialog_ErrorNoData"] = "V zadanÃ©m CSV nebyly nalezeny Å¾Ã¡dnÃ© datovÃ© Å™Ã¡dky.",
        ["TmDiagramCsvImportDialog_ErrorMinColumns"] = "CSV musÃ­ obsahovat alespoÅˆ 2 sloupce.",
        ["TmDiagramCsvImportDialog_ErrorMappings"] = "PÅ™iÅ™aÄte vÅ¡echny povinnÃ© sloupce.",
        ["TmDiagramCsvImportDialog_ErrorParse"] = "NepodaÅ™ilo se zpracovat CSV: {0}",
        ["TmDiagramEditor_ImportSql"] = "Import SQL â†’ ER",
        ["TmDiagramSqlImportDialog_Title"] = "Import SQL do ER diagramu",
        ["TmDiagramSqlImportDialog_SqlLabel"] = "SQL DDL",
        ["TmDiagramSqlImportDialog_SqlPlaceholder"] = "VloÅ¾te pÅ™Ã­kazy CREATE TABLE...",
        ["TmDiagramSqlImportDialog_LayoutLabel"] = "SmÄ›r rozvrÅ¾enÃ­",
        ["TmDiagramSqlImportDialog_PreviewTables"] = "Tabulky: {0}",
        ["TmDiagramSqlImportDialog_PreviewRelations"] = "Vztahy: {0}",
        ["TmDiagramSqlImportDialog_ImportButton"] = "Importovat",
        ["TmDiagramSqlImportDialog_ErrorEmpty"] = "Zadejte SQL DDL.",
        ["TmDiagramSqlImportDialog_ErrorNoTables"] = "V zadanÃ©m SQL nebyly nalezeny Å¾Ã¡dnÃ© tabulky.",
        ["TmDiagramSqlImportDialog_ErrorParse"] = "NepodaÅ™ilo se zpracovat SQL: {0}",
        ["TmDiagram_SearchPlaceholder"] = "Hledat v diagramu...",
        ["TmDiagram_SearchResults"] = "{0} z {1}",
        ["TmDiagram_SearchNoResults"] = "Å½Ã¡dnÃ© vÃ½sledky",
        ["TmDiagram_SearchPrevious"] = "PÅ™edchozÃ­ vÃ½sledek",
        ["TmDiagram_SearchNext"] = "DalÅ¡Ã­ vÃ½sledek",
        ["TmDiagram_SearchClose"] = "ZavÅ™Ã­t hledÃ¡nÃ­",
        ["TmDiagram_SearchAllPages"] = "VÅ¡echny strÃ¡nky",
        ["TmDiagram_ReplacePlaceholder"] = "Nahradit za...",
        ["TmDiagram_Replace"] = "Nahradit",
        ["TmDiagram_ReplaceAll"] = "Nahradit vÅ¡e",
        ["TmDiagram_UseRegex"] = "PouÅ¾Ã­t regulÃ¡rnÃ­ vÃ½razy",
        ["TmDiagram_RegexError"] = "NeplatnÃ½ regex: {0}",
        ["TmDiagram_ReplaceNoMatches"] = "Å½Ã¡dnÃ© nahraditelnÃ© vÃ½sledky",
        ["TmDiagram_EnableMathJax"] = "MathJax",

        // TmWireframe
        ["TmWireframe_UntitledPlaceholder"] = "NepojmenovanÃ½ wireframe",
        ["TmWireframe_DocumentTitleLabel"] = "NÃ¡zev dokumentu",
        ["TmWireframe_SelectTool"] = "NÃ¡stroj vÃ½bÄ›ru (V)",
        ["TmWireframe_PanTool"] = "NÃ¡stroj posunu (H)",
        ["TmWireframe_PanToolHint"] = "NÃ¡stroj posunu (H) â€” nebo podrÅ¾te mezernÃ­k",
        ["TmWireframe_Undo"] = "ZpÄ›t",
        ["TmWireframe_Redo"] = "Znovu",
        ["TmWireframe_ZoomOut"] = "OddÃ¡lit",
        ["TmWireframe_ZoomIn"] = "PÅ™iblÃ­Å¾it",
        ["TmWireframe_FitToView"] = "PÅ™izpÅ¯sobit zobrazenÃ­",
        ["TmWireframe_CanvasWidth"] = "Å Ã­Å™ka plÃ¡tna",
        ["TmWireframe_CanvasHeight"] = "VÃ½Å¡ka plÃ¡tna",
        ["TmWireframe_Apply"] = "PouÅ¾Ã­t",
        ["TmWireframe_Cancel"] = "ZruÅ¡it",
        ["TmWireframe_ChangeCanvasSize"] = "ZmÄ›nit velikost plÃ¡tna",
        ["TmWireframe_Export"] = "Exportovat",
        ["TmWireframe_ExportJson"] = "Exportovat JSON",
        ["TmWireframe_ExportSvg"] = "Exportovat SVG",
        ["TmWireframe_ExportPng"] = "Exportovat PNG",
        ["TmWireframe_ExportPdf"] = "Exportovat PDF",
        ["TmWireframe_ExportError"] = "Export selhal: {0}.",
        ["TmWireframeExportDialog_Title"] = "Exportovat wireframe",
        ["TmWireframeExportDialog_FileName"] = "NÃ¡zev souboru",
        ["TmWireframeExportDialog_FileNamePlaceholder"] = "wireframe",
        ["TmWireframeExportDialog_Format"] = "FormÃ¡t",
        ["TmWireframeExportDialog_Scale"] = "MÄ›Å™Ã­tko",
        ["TmWireframeExportDialog_IncludeBackground"] = "Zahrnout pozadÃ­",
        ["TmWireframeExportDialog_ExportButton"] = "Exportovat",
        ["TmWireframe_ImportJson"] = "Importovat JSON",
        ["TmWireframe_SwitchToEditMode"] = "PÅ™epnout do reÅ¾imu Ãºprav",
        ["TmWireframe_SwitchToReadOnlyMode"] = "PÅ™epnout do reÅ¾imu pouze pro ÄtenÃ­",
        ["TmWireframe_ReadOnly"] = "Pouze pro ÄtenÃ­",
        ["TmWireframe_Edit"] = "Upravit",
        ["TmWireframe_ShowToolbox"] = "Zobrazit panel nÃ¡strojÅ¯",
        ["TmWireframe_HideToolbox"] = "SkrÃ½t panel nÃ¡strojÅ¯",
        ["TmWireframe_ToggleToolbox"] = "PÅ™epnout panel nÃ¡strojÅ¯",
        ["TmWireframe_ShowProperties"] = "Zobrazit panel vlastnostÃ­",
        ["TmWireframe_HideProperties"] = "SkrÃ½t panel vlastnostÃ­",
        ["TmWireframe_ToggleProperties"] = "PÅ™epnout panel vlastnostÃ­",
        ["TmWireframe_DismissError"] = "ZavÅ™Ã­t chybu",
        ["TmWireframe_DefaultTitle"] = "NepojmenovanÃ½ wireframe",
        ["TmWireframe_ExportFilename"] = "wireframe",
        ["TmWireframe_ImportError_InvalidJson"] = "Import se nezdaÅ™il: soubor nenÃ­ platnÃ½ wireframe JSON.",
        ["TmWireframe_ImportError_Generic"] = "Import se nezdaÅ™il: {0}.",
        ["TmWireframeToolbox_SearchPlaceholder"] = "Hledat komponentyâ€¦",
        ["TmWireframeToolbox_ClearSearch"] = "Vymazat hledÃ¡nÃ­",
        ["TmWireframeToolbox_FilterAll"] = "VÅ¡e",
        ["TmWireframeToolbox_FilterBuiltIn"] = "VestavÄ›nÃ©",
        ["TmWireframeToolbox_FilterCustom"] = "VlastnÃ­",
        ["TmWireframeToolbox_NoComponentsMatch"] = "Å½Ã¡dnÃ© komponenty neodpovÃ­dajÃ­ \"{0}\"",
        ["TmWireframeToolbox_CustomComponentTooltip"] = "VlastnÃ­ komponenta",
        ["TmWireframeToolbox_DragOntoCanvas"] = "PÅ™etÃ¡hnÄ›te {0} na plÃ¡tno",
        ["TmWireframeProps_NoSelectionTitle"] = "Nic nenÃ­ vybrÃ¡no",
        ["TmWireframeProps_NoSelectionHint"] = "Vyberte prvek na plÃ¡tnÄ› pro Ãºpravu jeho vlastnostÃ­.",
        ["TmWireframeProps_ElementsCount"] = "{0} prvkÅ¯",
        ["TmWireframeProps_MixedTypes"] = "SmÃ­Å¡enÃ© typy",
        ["TmWireframeProps_SectionElement"] = "Prvek",
        ["TmWireframeProps_SectionLayout"] = "RozvrÅ¾enÃ­",
        ["TmWireframeProps_SectionGeneral"] = "ObecnÃ©",
        ["TmWireframeProps_Type"] = "Typ",
        ["TmWireframeProps_Types"] = "Typy",
        ["TmWireframeProps_ZIndex"] = "Z-Index",
        ["TmWireframeProps_X"] = "X",
        ["TmWireframeProps_Y"] = "Y",
        ["TmWireframeProps_W"] = "Å ",
        ["TmWireframeProps_H"] = "V",
        ["TmWireframeProps_MixedPlaceholder"] = "SmÃ­Å¡enÃ©",
        ["TmWireframeProps_CommaSeparatedPlaceholder"] = "oddÄ›lenÃ© ÄÃ¡rkou",
        ["TmWireframeProps_ValidationRegexError"] = "Hodnota neodpovÃ­dÃ¡ vzoru: {0}",
        ["TmWireframeProps_CommandChangeZIndex"] = "ZmÄ›nit Z-Index",
        ["TmWireframeCanvas_AriaLabel"] = "PlÃ¡tno wireframe",
        ["TmWireframeCanvas_UnknownComponent"] = "NeznÃ¡mÃ¡: {0}",
        ["TmWireframeProps_CatContent"] = "Obsah",
        ["TmWireframeProps_CatAppearance"] = "Vzhled",
        ["TmWireframeProps_CatBehavior"] = "ChovÃ¡nÃ­",
        ["TmWireframeProps_CatState"] = "Stav",

        ["TmWireframe_LayersToggle"] = "PÅ™epnout panel vrstev",
        ["TmWireframe_LayersTitle"] = "Vrstvy",
        ["TmWireframe_AddLayer"] = "PÅ™idat vrstvu",
        ["TmWireframe_SetActiveLayer"] = "Nastavit jako aktivnÃ­ vrstvu",
        ["TmWireframe_HideLayer"] = "SkrÃ½t vrstvu",
        ["TmWireframe_ShowLayer"] = "Zobrazit vrstvu",
        ["TmWireframe_UnlockLayer"] = "Odemknout vrstvu",
        ["TmWireframe_LockLayer"] = "Zamknout vrstvu",
        ["TmWireframe_DoubleClickToEdit"] = "Dvojklikem upravte nÃ¡zev",
        ["TmWireframe_DeleteLayer"] = "Smazat vrstvu",
        ["TmWireframe_MoveToLayer"] = "PÅ™esunout do vrstvy",
        ["TmWireframe_SelectLayer"] = "Vyberte vrstvu",
        ["TmWireframe_Layer"] = "Vrstva",
        ["TmWireframeProps_Layer"] = "Vrstva",
        ["TmWireframe_ShowRulers"] = "Zobrazit pravÃ­tka",
        ["TmWireframe_HorizontalRuler"] = "VodorovnÃ© pravÃ­tko",
        ["TmWireframe_VerticalRuler"] = "SvislÃ© pravÃ­tko",

        // TmPivotTable
        ["TmPivotTable_Loading"] = "NaÄÃ­tÃ¡nÃ­ kontingenÄnÃ­ tabulky...",
        ["TmPivotTable_NoData"] = "Å½Ã¡dnÃ¡ data k zobrazenÃ­",

        // TmSpreadsheet
        ["TmSpreadsheet_NoSheet"] = "Å½Ã¡dnÃ½ list k dispozici",
        ["TmSpreadsheet_Name"] = "Tabulka",
        ["TmSpreadsheet_CellReference"] = "Odkaz na buÅˆku",
        ["TmSpreadsheet_FormulaBarPlaceholder"] = "Zadejte vzorec nebo hodnotu...",
        ["TmSpreadsheet_SheetTab"] = "List",
        ["TmSpreadsheet_AddSheet"] = "PÅ™idat list",
        ["TmSpreadsheet_RenameSheet"] = "PÅ™ejmenovat list",
        ["TmSpreadsheet_DeleteSheet"] = "Smazat list",
        ["TmSpreadsheet_DeleteSheetConfirm"] = "Opravdu chcete smazat tento list?",
        ["TmSpreadsheet_GridLines"] = "MÅ™Ã­Å¾ka",
        ["TmSpreadsheet_MergeCells"] = "SlouÄit buÅˆky",
        ["TmSpreadsheet_Undo"] = "ZpÄ›t",
        ["TmSpreadsheet_Redo"] = "Znovu",
        ["TmSpreadsheet_Copy"] = "KopÃ­rovat",
        ["TmSpreadsheet_Cut"] = "Vyjmout",
        ["TmSpreadsheet_Paste"] = "VloÅ¾it",
        ["TmSpreadsheet_InsertRow"] = "VloÅ¾it Å™Ã¡dek",
        ["TmSpreadsheet_DeleteRow"] = "Smazat Å™Ã¡dek",
        ["TmSpreadsheet_InsertColumn"] = "VloÅ¾it sloupec",
        ["TmSpreadsheet_DeleteColumn"] = "Smazat sloupec",
        ["TmSpreadsheet_Bold"] = "TuÄnÄ›",
        ["TmSpreadsheet_Italic"] = "KurzÃ­va",
        ["TmSpreadsheet_Underline"] = "PodtrÅ¾enÃ©",
        ["TmSpreadsheet_TextColor"] = "Barva textu",
        ["TmSpreadsheet_BackgroundColor"] = "Barva pozadÃ­",
        ["TmSpreadsheet_AlignLeft"] = "Zarovnat vlevo",
        ["TmSpreadsheet_AlignCenter"] = "Zarovnat na stÅ™ed",
        ["TmSpreadsheet_AlignRight"] = "Zarovnat vpravo",
        ["TmSpreadsheet_NumberFormat"] = "FormÃ¡t ÄÃ­sla",
        ["TmSpreadsheet_IncreaseDecimals"] = "ZvÃ½Å¡it desetinnÃ¡ mÃ­sta",
        ["TmSpreadsheet_DecreaseDecimals"] = "SnÃ­Å¾it desetinnÃ¡ mÃ­sta",
        ["TmSpreadsheet_Open"] = "OtevÅ™Ã­t soubor",
        ["TmSpreadsheet_Download"] = "StÃ¡hnout",
        ["TmSpreadsheet_TabHome"] = "DomÅ¯",
        ["TmSpreadsheet_TabInsert"] = "VloÅ¾it",
        ["TmSpreadsheet_TabView"] = "ZobrazenÃ­",
        ["TmSpreadsheet_TabFile"] = "Soubor",
        ["TmSpreadsheet_InsertLink"] = "VloÅ¾it odkaz",
        ["TmSpreadsheet_InsertImage"] = "VloÅ¾it obrÃ¡zek",
        ["TmSpreadsheet_LinkUrl"] = "URL",
        ["TmSpreadsheet_LinkText"] = "ZobrazenÃ½ text",
        ["TmSpreadsheet_LinkTextPlaceholder"] = "KliknÄ›te zde",
        ["TmSpreadsheet_ImageUrl"] = "URL obrÃ¡zku",

        // TmRating
        ["TmRating_AriaLabel"] = "HodnocenA-",

        // TmBottomNavigation
        ["TmBottomNavigation_AriaLabel"] = "SpodnA- navigace",
    });
}

/// <summary>
/// Minimal in-memory ITmLocalizer for testing. Returns [key] for unknown keys.
/// </summary>
public sealed class MockTmLocalizer : ITmLocalizer
{
    private readonly Dictionary<string, string> _data;

    public MockTmLocalizer(Dictionary<string, string> data) => _data = data;

    public string this[string key] =>
        _data.TryGetValue(key, out var v) ? v : $"[{key}]";

    public string this[string key, params object[] arguments]
    {
        get
        {
            var template = _data.TryGetValue(key, out var v) ? v : $"[{key}]";
            return arguments.Length > 0 ? string.Format(template, arguments) : template;
        }
    }
}
