// Phase 5 (headless document runtime): C#↔JS operation-applier convergence.
//
// The committed fixture (tests/Tempo.Blazor.Tests/DocumentEditor/TestData/
// operation-convergence-fixture.json, generated by DocumentOperationConvergenceFixtureTests)
// carries seeded operation batches, the seed canvas model and the CONTENT SIGNATURE the C#
// DocumentOperationApplier produced. Replaying the identical operations through the JS
// collaboration applier (transform.mjs applyOperation) over the canvas model must yield a deeply
// equal signature — convergence is about content (block order, text, heading levels,
// per-character mark ranges), not run identities.
import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { applyOperation } from '../src/Tempo.Blazor.DocumentEditor/wwwroot/js/document-editor-canvas/collaboration/transform.mjs';
import { createCanvasDocumentModel } from '../src/Tempo.Blazor.DocumentEditor/wwwroot/js/document-editor-canvas/model/canvas-document-model.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const fixture = JSON.parse(readFileSync(
    path.join(repoRoot, 'tests', 'Tempo.Blazor.Tests', 'DocumentEditor', 'TestData', 'operation-convergence-fixture.json'),
    'utf8'));

// Mirrors DocumentOperationConvergenceFixtureTests.ComputeSignature over the CANVAS model shape.
function computeSignature(model) {
    const blocks = [];
    for (const block of model?.body?.blocks || []) {
        blocks.push(signatureEntry('body', block));
        const table = block?.content?.table;
        for (const row of table?.rows || []) {
            for (const cell of row?.cells || []) {
                for (const nested of cell?.blocks || []) {
                    blocks.push(signatureEntry(`cell:${cell.id}`, nested));
                }
            }
        }
    }

    return { blocks };
}

function signatureEntry(container, block) {
    const kind = block?.content?.headingLevel
        ? 'heading'
        : block?.content?.table
            ? 'table'
            : Array.isArray(block?.content?.runs)
                ? 'paragraph'
                : 'other';

    let text = '';
    const marks = {};
    if (Array.isArray(block?.content?.runs) && kind !== 'table') {
        let cursor = 0;
        for (const run of block.content.runs) {
            const runText = typeof run?.text === 'string' ? run.text : '';
            for (const mark of run?.marks || []) {
                const key = String(mark?.type || '');
                if (!key) {
                    continue;
                }

                const ranges = marks[key] ??= [];
                if (ranges.length > 0 && ranges[ranges.length - 1][1] === cursor) {
                    ranges[ranges.length - 1][1] = cursor + runText.length;
                } else {
                    ranges.push([cursor, cursor + runText.length]);
                }
            }

            text += runText;
            cursor += runText.length;
        }
    }

    const sortedMarks = {};
    for (const key of Object.keys(marks).sort()) {
        sortedMarks[key] = marks[key];
    }

    const entry = {
        container,
        id: String(block?.id || ''),
        kind,
        text,
        marks: sortedMarks,
    };
    // The C# fixture omits null values (WhenWritingNull) — mirror that exactly.
    if (kind === 'heading') {
        entry.headingLevel = Number(block.content.headingLevel);
    }

    return entry;
}

test('fixture is present and carries the seeded cases', () => {
    assert.equal(fixture.schemaVersion, 1);
    assert.ok(Array.isArray(fixture.cases) && fixture.cases.length >= 5);
});

for (const convergenceCase of fixture.cases) {
    test(`JS applier converges with the C# applier for seed ${convergenceCase.seed}`, () => {
        let model = createCanvasDocumentModel(convergenceCase.model);
        for (const operation of convergenceCase.operations) {
            const result = applyOperation(model, operation);
            assert.equal(
                result.applied,
                true,
                `seed ${convergenceCase.seed}: ${operation.type} must apply in JS (${result.reason || 'ok'})`);
            model = result.model;
        }

        assert.deepEqual(
            computeSignature(model),
            convergenceCase.expectedSignature,
            `seed ${convergenceCase.seed}: JS content signature must equal the C# applier result`);
    });
}
